// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.BiomassBurner;

public sealed class PackagedLiquidBiofuelBiomassBurner : RecipeBase
{
    public override int SortIndex => 169;
    public override string RecipeName => "Packaged Liquid Biofuel Biomass Burner";
    public override string Machine => "Biomass Burner";
    public override string BatchTime => "25";
    public override string Tier => "5-4";
    public override bool IgnoreInputMultiplier => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Packaged Liquid Biofuel", Amount = "-1" },
    ];
}
