// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.BiomassBurner;

public sealed class SolidBiofuelBiomassBurner : RecipeBase
{
    public override int SortIndex => 98;
    public override string RecipeName => "Solid Biofuel Biomass Burner";
    public override string Machine => "Biomass Burner";
    public override string BatchTime => "15";
    public override string Tier => "2-2";
    public override bool IgnoreInputMultiplier => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Solid Biofuel", Amount = "-1" },
    ];
}
