// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines.Generators;

public sealed class CoalPoweredGenerator : GeneratorBase
{
    public override int SortIndex => 11;
    public override string MachineName => "Coal-Powered Generator";
    public override string Tier => "3-1";
    public override string? AveragePower => "75";
    public override string? OverclockPowerExponent => "1";

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Reinforced Iron Plate", Amount = "20" },
        new() { Part = "Rotor", Amount = "10" },
        new() { Part = "Cable", Amount = "30" },
    ];
}
