// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines.Generators;

public sealed class NuclearPowerPlant : GeneratorBase
{
    public override int SortIndex => 23;
    public override string MachineName => "Nuclear Power Plant";
    public override string Tier => "8-2";
    public override string? AveragePower => "2500";
    public override string? OverclockPowerExponent => "1";

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Supercomputer", Amount = "10" },
        new() { Part = "Heavy Modular Frame", Amount = "25" },
        new() { Part = "Alclad Aluminum Sheet", Amount = "100" },
        new() { Part = "Cable", Amount = "200" },
        new() { Part = "Concrete", Amount = "250" },
    ];
}
