// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Converter;

public sealed class CateriumOreCopper : RecipeBase
{
    public override int SortIndex => 72;
    public override string RecipeName => "Caterium Ore (Copper)";
    public override string Machine => "Converter";
    public override string BatchTime => "6";
    public override string Tier => "9-1";
    public override string? AveragePower => "-250";
    public override string? MinPower => "-400";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Reanimated SAM", Amount = "-1" },
        new() { Part = "Copper Ore", Amount = "-15" },
        new() { Part = "Caterium Ore", Amount = "12" },
    ];
}
