// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Converter;

public sealed class ExcitedPhotonicMatter : RecipeBase
{
    public override int SortIndex => 15;
    public override string RecipeName => "Excited Photonic Matter";
    public override string Machine => "Converter";
    public override string BatchTime => "3";
    public override string Tier => "9-2";
    public override string? AveragePower => "-250";
    public override string? MinPower => "-400";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Excited Photonic Matter", Amount = "10" },
    ];
}
