// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Converter;

public sealed class FicsiteIngotAluminum : RecipeBase
{
    public override int SortIndex => 295;
    public override string RecipeName => "Ficsite Ingot (Aluminum)";
    public override string Machine => "Converter";
    public override string BatchTime => "2";
    public override string Tier => "9-1";
    public override string? AveragePower => "-250";
    public override string? MinPower => "-400";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Reanimated SAM", Amount = "-2" },
        new() { Part = "Aluminum Ingot", Amount = "-4" },
        new() { Part = "Ficsite Ingot", Amount = "1" },
    ];
}
