// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Converter;

public sealed class TimeCrystal : RecipeBase
{
    public override int SortIndex => 293;
    public override string RecipeName => "Time Crystal";
    public override string Machine => "Converter";
    public override string BatchTime => "10";
    public override string Tier => "9-1";
    public override string? AveragePower => "-250";
    public override string? MinPower => "-400";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Diamonds", Amount = "-2" },
        new() { Part = "Time Crystal", Amount = "1" },
    ];
}
