// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Blender;

public sealed class Battery : RecipeBase
{
    public override int SortIndex => 234;
    public override string RecipeName => "Battery";
    public override string Machine => "Blender";
    public override string BatchTime => "3";
    public override string Tier => "7-5";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Sulfuric Acid", Amount = "-5/2" },
        new() { Part = "Alumina Solution", Amount = "-2" },
        new() { Part = "Aluminum Casing", Amount = "-1" },
        new() { Part = "Battery", Amount = "1" },
        new() { Part = "Water", Amount = "3/2" },
    ];
}
