// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Blender;

public sealed class BiochemicalSculptor : RecipeBase
{
    public override int SortIndex => 299;
    public override string RecipeName => "Biochemical Sculptor";
    public override string Machine => "Blender";
    public override string BatchTime => "120";
    public override string Tier => "9-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Assembly Director System", Amount = "-1" },
        new() { Part = "Ficsite Trigon", Amount = "-80" },
        new() { Part = "Water", Amount = "-20" },
        new() { Part = "Biochemical Sculptor", Amount = "4" },
    ];
}
