// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Blender;

public sealed class CoolingSystem : RecipeBase
{
    public override int SortIndex => 258;
    public override string RecipeName => "Cooling System";
    public override string Machine => "Blender";
    public override string BatchTime => "10";
    public override string Tier => "8-3";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Heat Sink", Amount = "-2" },
        new() { Part = "Rubber", Amount = "-2" },
        new() { Part = "Water", Amount = "-5" },
        new() { Part = "Nitrogen Gas", Amount = "-25" },
        new() { Part = "Cooling System", Amount = "1" },
    ];
}
