// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Blender;

public sealed class EncasedUraniumCell : RecipeBase
{
    public override int SortIndex => 246;
    public override string RecipeName => "Encased Uranium Cell";
    public override string Machine => "Blender";
    public override string BatchTime => "12";
    public override string Tier => "8-2";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Uranium", Amount = "-10" },
        new() { Part = "Concrete", Amount = "-3" },
        new() { Part = "Sulfuric Acid", Amount = "-8" },
        new() { Part = "Encased Uranium Cell", Amount = "5" },
        new() { Part = "Sulfuric Acid", Amount = "2" },
    ];
}
