// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Blender;

public sealed class FertileUranium : RecipeBase
{
    public override int SortIndex => 283;
    public override string RecipeName => "Fertile Uranium";
    public override string Machine => "Blender";
    public override string BatchTime => "12";
    public override string Tier => "8-5";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Uranium", Amount = "-5" },
        new() { Part = "Uranium Waste", Amount = "-5" },
        new() { Part = "Nitric Acid", Amount = "-3" },
        new() { Part = "Sulfuric Acid", Amount = "-5" },
        new() { Part = "Non-Fissile Uranium", Amount = "20" },
        new() { Part = "Water", Amount = "8" },
    ];
}
