// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Blender;

public sealed class FusedModularFrame : RecipeBase
{
    public override int SortIndex => 260;
    public override string RecipeName => "Fused Modular Frame";
    public override string Machine => "Blender";
    public override string BatchTime => "40";
    public override string Tier => "8-3";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Heavy Modular Frame", Amount = "-1" },
        new() { Part = "Aluminum Casing", Amount = "-50" },
        new() { Part = "Nitrogen Gas", Amount = "-25" },
        new() { Part = "Fused Modular Frame", Amount = "1" },
    ];
}
