// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Blender;

public sealed class HeatFusedFrame : RecipeBase
{
    public override int SortIndex => 261;
    public override string RecipeName => "Heat-Fused Frame";
    public override string Machine => "Blender";
    public override string BatchTime => "20";
    public override string Tier => "8-5";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Heavy Modular Frame", Amount = "-1" },
        new() { Part = "Aluminum Ingot", Amount = "-50" },
        new() { Part = "Nitric Acid", Amount = "-8" },
        new() { Part = "Fuel", Amount = "-10" },
        new() { Part = "Fused Modular Frame", Amount = "1" },
    ];
}
