// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Blender;

public sealed class NitricAcid : RecipeBase
{
    public override int SortIndex => 280;
    public override string RecipeName => "Nitric Acid";
    public override string Machine => "Blender";
    public override string BatchTime => "6";
    public override string Tier => "8-5";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Nitrogen Gas", Amount = "-12" },
        new() { Part = "Water", Amount = "-3" },
        new() { Part = "Iron Plate", Amount = "-1" },
        new() { Part = "Nitric Acid", Amount = "3" },
    ];
}
