// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Blender;

public sealed class NonFissileUranium : RecipeBase
{
    public override int SortIndex => 282;
    public override string RecipeName => "Non-Fissile Uranium";
    public override string Machine => "Blender";
    public override string BatchTime => "24";
    public override string Tier => "8-5";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Uranium Waste", Amount = "-15" },
        new() { Part = "Silica", Amount = "-10" },
        new() { Part = "Nitric Acid", Amount = "-6" },
        new() { Part = "Sulfuric Acid", Amount = "-6" },
        new() { Part = "Non-Fissile Uranium", Amount = "20" },
        new() { Part = "Water", Amount = "6" },
    ];
}
