// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Blender;

public sealed class RocketFuel : RecipeBase
{
    public override int SortIndex => 182;
    public override string RecipeName => "Rocket Fuel";
    public override string Machine => "Blender";
    public override string BatchTime => "6";
    public override string Tier => "8-5";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Turbofuel", Amount = "-6" },
        new() { Part = "Nitric Acid", Amount = "-1" },
        new() { Part = "Rocket Fuel", Amount = "10" },
        new() { Part = "Compacted Coal", Amount = "1" },
    ];
}
