// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Blender;

public sealed class TurboBlendFuel : RecipeBase
{
    public override int SortIndex => 188;
    public override string RecipeName => "Turbo Blend Fuel";
    public override string Machine => "Blender";
    public override string BatchTime => "8";
    public override string Tier => "7-5";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Fuel", Amount = "-2" },
        new() { Part = "Heavy Oil Residue", Amount = "-4" },
        new() { Part = "Sulfur", Amount = "-3" },
        new() { Part = "Petroleum Coke", Amount = "-3" },
        new() { Part = "Turbofuel", Amount = "6" },
    ];
}
