// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.NuclearPowerPlant;

public sealed class UraniumNuclearPowerPlant : RecipeBase
{
    public override int SortIndex => 254;
    public override string RecipeName => "Uranium Nuclear Power Plant";
    public override string Machine => "Nuclear Power Plant";
    public override string BatchTime => "300";
    public override string Tier => "8-2";
    public override bool IgnoreInputMultiplier => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Uranium Fuel Rod", Amount = "-1" },
        new() { Part = "Water", Amount = "-1200" },
        new() { Part = "Uranium Waste", Amount = "50" },
    ];
}
