// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines.Extractors;

public sealed class Miner : ExtractorBase
{
    public override int SortIndex => 4;
    public override string MachineName => "Miner";
    public override string Tier => "0-5";
    public override int FamilySortIndex => 0;
    public override bool ShowPpm => true;
    public override bool AutoRound => false;
    public override string DefaultMax => "60";

    public override IReadOnlyList<MultiMachineVariant> FamilyMachines =>
    [
        new() { Name = "Miner Mk.1", PartsRatio = "60", Default = true },
        new() { Name = "Miner Mk.2", PartsRatio = "120" },
        new() { Name = "Miner Mk.3", PartsRatio = "240" },
    ];

    public override IReadOnlyList<MultiMachineCapacity> FamilyCapacities =>
    [
        new() { Name = "Impure", PartsRatio = "1/2", Color = 13775920 },
        new() { Name = "Normal", Default = true },
        new() { Name = "Pure", PartsRatio = "2", Color = 8433977 },
    ];

    public override IEnumerable<(int SortIndex, MachineDefinition Definition)> ToIndexedMachineDefinitions() =>
    [
        (4, new() { Name = "Miner Mk.1", Tier = "0-5", AveragePower = "-5", OverclockPowerExponent = "1321929/1000000", Cost = [new() { Part = "Portable Miner", Amount = "1" }, new() { Part = "Iron Plate", Amount = "10" }, new() { Part = "Concrete", Amount = "10" }] }),
        (14, new() { Name = "Miner Mk.2", Tier = "4-3", AveragePower = "-15", OverclockPowerExponent = "1321929/1000000", Cost = [new() { Part = "Portable Miner", Amount = "2" }, new() { Part = "Encased Industrial Beam", Amount = "10" }, new() { Part = "Steel Pipe", Amount = "20" }, new() { Part = "Modular Frame", Amount = "10" }] }),
        (26, new() { Name = "Miner Mk.3", Tier = "8-4", AveragePower = "-45", OverclockPowerExponent = "1321929/1000000", Cost = [new() { Part = "Portable Miner", Amount = "3" }, new() { Part = "Steel Pipe", Amount = "50" }, new() { Part = "Supercomputer", Amount = "5" }, new() { Part = "Fused Modular Frame", Amount = "10" }, new() { Part = "Turbo Motor", Amount = "3" }] }),
    ];

    public override MultiMachineDefinition ToFamilyDefinition() => new()
    {
        Name = "Miner",
        ShowPpm = true,
        AutoRound = false,
        DefaultMax = "60",
        Machines =
        [
            new() { Name = "Miner Mk.1", PartsRatio = "60", Default = true },
            new() { Name = "Miner Mk.2", PartsRatio = "120" },
            new() { Name = "Miner Mk.3", PartsRatio = "240" },
        ],
        Capacities =
        [
            new() { Name = "Impure", PartsRatio = "1/2", Color = 13775920 },
            new() { Name = "Normal", Default = true },
            new() { Name = "Pure", PartsRatio = "2", Color = 8433977 },
        ],
    };
}
