// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines.Extractors;

public sealed class OilExtractor : ExtractorBase
{
    public override int SortIndex => 16;
    public override string MachineName => "Oil Extractor";
    public override string Tier => "5-2";
    public override int FamilySortIndex => 1;
    public override bool ShowPpm => true;
    public override bool AutoRound => false;
    public override string DefaultMax => "120";
    public override string? AveragePower => "-40";
    public override string? OverclockPowerExponent => "1321929/1000000";

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Motor", Amount = "15" },
        new() { Part = "Encased Industrial Beam", Amount = "20" },
        new() { Part = "Cable", Amount = "60" },
    ];

    public override IReadOnlyList<MultiMachineCapacity> FamilyCapacities =>
    [
        new() { Name = "Impure", PartsRatio = "1/2", Color = 13775920 },
        new() { Name = "Normal", Default = true },
        new() { Name = "Pure", PartsRatio = "2", Color = 8433977 },
    ];

    public override MultiMachineDefinition ToFamilyDefinition() => new()
    {
        Name = "Oil Extractor",
        ShowPpm = true,
        AutoRound = false,
        DefaultMax = "120",
        Capacities =
        [
            new() { Name = "Impure", PartsRatio = "1/2", Color = 13775920 },
            new() { Name = "Normal", Default = true },
            new() { Name = "Pure", PartsRatio = "2", Color = 8433977 },
        ],
    };
}
