// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines.Extractors;

public sealed class ResourceWellPressurizer : ExtractorBase
{
    public override int SortIndex => 25;
    public override string MachineName => "Resource Well Pressurizer";
    public override string Tier => "8-3";
    public override string? AveragePower => "-150";
    public override string? OverclockPowerExponent => "1321929/1000000";

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Radio Control Unit", Amount = "10" },
        new() { Part = "Heavy Modular Frame", Amount = "25" },
        new() { Part = "Motor", Amount = "50" },
        new() { Part = "Alclad Aluminum Sheet", Amount = "50" },
        new() { Part = "Rubber", Amount = "100" },
    ];
}
