// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines.Extractors;

public sealed class ResourceWellExtractor : ExtractorBase
{
    public override int SortIndex => 24;
    public override string MachineName => "Resource Well Extractor";
    public override string Tier => "8-3";
    public override int FamilySortIndex => 2;
    public override bool ShowPpm => true;
    public override string DefaultMax => "60";

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Steel Beam", Amount = "10" },
        new() { Part = "Aluminum Casing", Amount = "10" },
    ];

    public override IReadOnlyList<MultiMachineCapacity> FamilyCapacities =>
    [
        new() { Name = "Impure", PartsRatio = "1/2", Color = 13775920 },
        new() { Name = "Normal", Default = true },
        new() { Name = "Pure", PartsRatio = "2", Color = 8433977 },
    ];

    public override MultiMachineDefinition ToFamilyDefinition() => new()
    {
        Name = "Resource Well Extractor",
        ShowPpm = true,
        DefaultMax = "60",
        Capacities =
        [
            new() { Name = "Impure", PartsRatio = "1/2", Color = 13775920 },
            new() { Name = "Normal", Default = true },
            new() { Name = "Pure", PartsRatio = "2", Color = 8433977 },
        ],
    };
}
