// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines.Extractors;

public sealed class WaterExtractor : ExtractorBase
{
    public override int SortIndex => 10;
    public override string MachineName => "Water Extractor";
    public override string Tier => "3-1";
    public override string? AveragePower => "-20";
    public override string? OverclockPowerExponent => "1321929/1000000";

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Copper Sheet", Amount = "20" },
        new() { Part = "Reinforced Iron Plate", Amount = "10" },
        new() { Part = "Rotor", Amount = "10" },
    ];
}
