// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.MultiMachines;

public sealed class AWESOMESinkFamily : MultiMachineBase
{
    public override int SortIndex => 4;
    public override string FamilyName => "AWESOME Sink";
    public override bool ShowPpm => true;

    public override IReadOnlyList<MultiMachineCapacity> Capacities =>
    [
        new() { Name = "Mk.1 Belt", PartsRatio = "60", Default = true },
        new() { Name = "Mk.2 Belt", PartsRatio = "120", Color = 13775920 },
        new() { Name = "Mk.3 Belt", PartsRatio = "270", Color = 16311334 },
        new() { Name = "Mk.4 Belt", PartsRatio = "480", Color = 8433977 },
        new() { Name = "Mk.5 Belt", PartsRatio = "780", Color = 2504952 },
        new() { Name = "Mk.6 Belt", PartsRatio = "1200", Color = 12330744 },
    ];
}
