// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.MultiMachines;

public sealed class DimensionalDepotUploaderFamily : MultiMachineBase
{
    public override int SortIndex => 3;
    public override string FamilyName => "Dimensional Depot Uploader";
    public override bool ShowPpm => true;

    public override IReadOnlyList<MultiMachineCapacity> Capacities =>
    [
        new() { Name = "15/min", PartsRatio = "15", Default = true },
        new() { Name = "30/min", PartsRatio = "30", Color = 13775920 },
        new() { Name = "60/min", PartsRatio = "60", Color = 16311334 },
        new() { Name = "120/min", PartsRatio = "120", Color = 8433977 },
        new() { Name = "240/min", PartsRatio = "240", Color = 12330744 },
    ];
}
