// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.MultiMachines;

public sealed class GeothermalGeneratorFamily : MultiMachineBase
{
    public override int SortIndex => 5;
    public override string FamilyName => "Geothermal Generator";
    public override string DefaultMax => "1";

    public override IReadOnlyList<MultiMachineCapacity> Capacities =>
    [
        new() { Name = "Impure", PowerRatio = "1/2", Color = 13775920 },
        new() { Name = "Normal", Default = true },
        new() { Name = "Pure", PowerRatio = "2", Color = 8433977 },
    ];
}
