// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.MultiMachines;

public sealed class MinerFamily : MultiMachineBase
{
    public override int SortIndex => 0;
    public override string FamilyName => "Miner";
    public override bool ShowPpm => true;
    public override bool AutoRound => false;
    public override string DefaultMax => "60";

    public override IReadOnlyList<MultiMachineVariant> Machines =>
    [
        new() { Name = "Miner Mk.1", PartsRatio = "60", Default = true },
        new() { Name = "Miner Mk.2", PartsRatio = "120" },
        new() { Name = "Miner Mk.3", PartsRatio = "240" },
    ];

    public override IReadOnlyList<MultiMachineCapacity> Capacities =>
    [
        new() { Name = "Impure", PartsRatio = "1/2", Color = 13775920 },
        new() { Name = "Normal", Default = true },
        new() { Name = "Pure", PartsRatio = "2", Color = 8433977 },
    ];
}
