// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.MultiMachines;

public sealed class OilExtractorFamily : MultiMachineBase
{
    public override int SortIndex => 1;
    public override string FamilyName => "Oil Extractor";
    public override bool ShowPpm => true;
    public override bool AutoRound => false;
    public override string DefaultMax => "120";

    public override IReadOnlyList<MultiMachineCapacity> Capacities =>
    [
        new() { Name = "Impure", PartsRatio = "1/2", Color = 13775920 },
        new() { Name = "Normal", Default = true },
        new() { Name = "Pure", PartsRatio = "2", Color = 8433977 },
    ];
}
