// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.MultiMachines;

public sealed class SpaceElevatorFamily : MultiMachineBase
{
    public override int SortIndex => 6;
    public override string FamilyName => "Space Elevator";
    public override string DefaultMax => "1";
}
