// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines;

public sealed class AlienPowerAugmenter : MachineBase
{
    public override int SortIndex => 28;
    public override string MachineName => "Alien Power Augmenter";
    public override string Tier => "9-1";
    public override string? BasePower => "500";
    public override string? BasePowerBoost => "1/10";
    public override string? FueledBasePowerBoost => "3/10";

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Somersloop", Amount = "10" },
        new() { Part = "SAM Fluctuator", Amount = "50" },
        new() { Part = "Cable", Amount = "100" },
        new() { Part = "Encased Industrial Beam", Amount = "50" },
        new() { Part = "Motor", Amount = "25" },
        new() { Part = "Computer", Amount = "10" },
    ];
}
