// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines;

public sealed class Assembler : MachineBase
{
    public override int SortIndex => 7;
    public override string MachineName => "Assembler";
    public override string Tier => "2-1";
    public override string? AveragePower => "-15";
    public override string? OverclockPowerExponent => "1321929/1000000";
    public override string? ProductionShardMultiplier => "1/2";
    public override string? ProductionShardPowerExponent => "2";
    public override int MaxProductionShards => 2;

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Reinforced Iron Plate", Amount = "8" },
        new() { Part = "Rotor", Amount = "4" },
        new() { Part = "Cable", Amount = "10" },
    ];
}
