// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines;

public sealed class AWESOMESink : MachineBase
{
    public override int SortIndex => 8;
    public override string MachineName => "AWESOME Sink";
    public override string Tier => "2-4";
    public override string? AveragePower => "-30";

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Reinforced Iron Plate", Amount = "15" },
        new() { Part = "Cable", Amount = "30" },
        new() { Part = "Concrete", Amount = "45" },
    ];
}
