// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines;

public sealed class BiomassBurner : MachineBase
{
    public override int SortIndex => 6;
    public override string MachineName => "Biomass Burner";
    public override string Tier => "0-6";
    public override string? AveragePower => "30";
    public override string? OverclockPowerExponent => "1";

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Iron Plate", Amount = "15" },
        new() { Part = "Iron Rod", Amount = "15" },
        new() { Part = "Wire", Amount = "25" },
    ];
}
