// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines;

public sealed class DimensionalDepotUploader : MachineBase
{
    public override int SortIndex => 30;
    public override string MachineName => "Dimensional Depot Uploader";
    public override string Tier => "9-1";

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Mercer Sphere", Amount = "1" },
        new() { Part = "SAM Fluctuator", Amount = "10" },
        new() { Part = "Modular Frame", Amount = "10" },
        new() { Part = "Wire", Amount = "100" },
    ];
}
