// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines;

public sealed class FICSMASGiftTree : MachineBase
{
    public override int SortIndex => 1;
    public override string MachineName => "FICSMAS Gift Tree";
    public override string Tier => "0-3";

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "FICSMAS Gift", Amount = "50" },
        new() { Part = "FICSMAS Tree Branch", Amount = "100" },
        new() { Part = "Red FICSMAS Ornament", Amount = "30" },
        new() { Part = "Blue FICSMAS Ornament", Amount = "30" },
    ];
}
