// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines;

public sealed class FluidBuffer : MachineBase
{
    public override int SortIndex => 9;
    public override string MachineName => "Fluid Buffer";
    public override string Tier => "3-1";

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Copper Sheet", Amount = "10" },
        new() { Part = "Modular Frame", Amount = "5" },
    ];
}
