// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines;

public sealed class Foundry : MachineBase
{
    public override int SortIndex => 12;
    public override string MachineName => "Foundry";
    public override string Tier => "3-3";
    public override string? AveragePower => "-16";
    public override string? OverclockPowerExponent => "1321929/1000000";
    public override string? ProductionShardMultiplier => "1/2";
    public override string? ProductionShardPowerExponent => "2";
    public override int MaxProductionShards => 2;

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Modular Frame", Amount = "10" },
        new() { Part = "Rotor", Amount = "10" },
        new() { Part = "Concrete", Amount = "20" },
    ];
}
