// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines;

public sealed class FuelPoweredGenerator : MachineBase
{
    public override int SortIndex => 19;
    public override string MachineName => "Fuel-Powered Generator";
    public override string Tier => "5-5";
    public override string? AveragePower => "250";
    public override string? OverclockPowerExponent => "1";

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Motor", Amount = "15" },
        new() { Part = "Encased Industrial Beam", Amount = "15" },
        new() { Part = "Copper Sheet", Amount = "30" },
        new() { Part = "Rubber", Amount = "50" },
        new() { Part = "Quickwire", Amount = "50" },
    ];
}
