// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines;

public sealed class GeothermalGenerator : MachineBase
{
    public override int SortIndex => 21;
    public override string MachineName => "Geothermal Generator";
    public override string Tier => "6-1";
    public override string? AveragePower => "200";
    public override string? MinPower => "100";

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Motor", Amount = "10" },
        new() { Part = "High-Speed Connector", Amount = "25" },
        new() { Part = "Modular Frame", Amount = "25" },
        new() { Part = "Copper Sheet", Amount = "50" },
        new() { Part = "Wire", Amount = "250" },
    ];
}
