// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines;

public sealed class IndustrialStorageContainer : MachineBase
{
    public override int SortIndex => 13;
    public override string MachineName => "Industrial Storage Container";
    public override string Tier => "4-2";

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Steel Beam", Amount = "20" },
        new() { Part = "Steel Pipe", Amount = "20" },
    ];
}
