// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines;

public sealed class IndustrialFluidBuffer : MachineBase
{
    public override int SortIndex => 18;
    public override string MachineName => "Industrial Fluid Buffer";
    public override string Tier => "5-5";

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Encased Industrial Beam", Amount = "5" },
        new() { Part = "Copper Sheet", Amount = "10" },
        new() { Part = "Plastic", Amount = "25" },
    ];
}
