// <auto-generated>
// Generated by Ficsit.Schematics.CatalogGenerator from Docs/en-US.json — do not edit.
// Regenerate with: dotnet run --project Ficsit.Schematics.CatalogGenerator -- --write
// </auto-generated>
using Ficsit.Schematics.Core.Numerics;

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines;

/// <summary>
/// Export-derived stats for every machine, keyed by machine name. The hand-authored
/// machine groups (families, marks, capacities) pull their numbers from here.
/// </summary>
internal static class MachineStats
{
    public static MachineStat For(string machine) => ByName[machine];

    public static readonly IReadOnlyDictionary<string, MachineStat> ByName = new Dictionary<string, MachineStat>(StringComparer.Ordinal)
    {
        ["AWESOME Sink"] = new("2-4", Power: -30, Cost: [C("Reinforced Iron Plate", 15), C("Cable", 30), C("Concrete", 45)]),
        ["Alien Power Augmenter"] = new("9-1", BasePower: 500, BasePowerBoost: R("1/10"), FueledBasePowerBoost: R("3/10"), Cost: [C("Somersloop", 10), C("SAM Fluctuator", 50), C("Cable", 100), C("Encased Industrial Beam", 50), C("Motor", 25), C("Computer", 10)]),
        ["Assembler"] = new("2-1", Power: -15, OverclockExp: R("1321929/1000000"), Sloops: 2, SloopMultiplier: R("1/2"), SloopPowerExp: 2, Cost: [C("Reinforced Iron Plate", 8), C("Rotor", 4), C("Cable", 10)]),
        ["Biomass Burner"] = new("0-6", Power: 30, OverclockExp: 1, Cost: [C("Iron Plate", 15), C("Iron Rod", 15), C("Wire", 25)]),
        ["Blender"] = new("7-5", Power: -75, OverclockExp: R("1321929/1000000"), Sloops: 4, SloopMultiplier: R("1/4"), SloopPowerExp: 2, Cost: [C("Computer", 10), C("Heavy Modular Frame", 10), C("Motor", 20), C("Aluminum Casing", 50)]),
        ["Coal-Powered Generator"] = new("3-1", Power: 75, OverclockExp: 1, Cost: [C("Reinforced Iron Plate", 20), C("Rotor", 10), C("Cable", 30)]),
        ["Constructor"] = new("0-3", Power: -4, OverclockExp: R("1321929/1000000"), Sloops: 1, SloopMultiplier: 1, SloopPowerExp: 2, Cost: [C("Reinforced Iron Plate", 2), C("Cable", 8)]),
        ["Converter"] = new("9-1", OverclockExp: R("1321929/1000000"), Sloops: 2, SloopMultiplier: R("1/2"), SloopPowerExp: 2, Cost: [C("Fused Modular Frame", 10), C("Cooling System", 25), C("Radio Control Unit", 50), C("SAM Fluctuator", 100)]),
        ["Dimensional Depot Uploader"] = new("9-1", Cost: [C("Mercer Sphere", 1), C("SAM Fluctuator", 10), C("Modular Frame", 10), C("Wire", 100)]),
        ["FICSMAS Gift Tree"] = new("0-3", Cost: [C("FICSMAS Gift", 50), C("FICSMAS Tree Branch", 100), C("Red FICSMAS Ornament", 30), C("Blue FICSMAS Ornament", 30)]),
        ["Fluid Buffer"] = new("3-1", Cost: [C("Copper Sheet", 10), C("Modular Frame", 5)]),
        ["Foundry"] = new("3-3", Power: -16, OverclockExp: R("1321929/1000000"), Sloops: 2, SloopMultiplier: R("1/2"), SloopPowerExp: 2, Cost: [C("Modular Frame", 10), C("Rotor", 10), C("Concrete", 20)]),
        ["Fuel-Powered Generator"] = new("5-5", Power: 250, OverclockExp: 1, Cost: [C("Motor", 15), C("Encased Industrial Beam", 15), C("Copper Sheet", 30), C("Rubber", 50), C("Quickwire", 50)]),
        ["Geothermal Generator"] = new("6-1", Power: 200, MinPower: 100, Cost: [C("Motor", 10), C("High-Speed Connector", 25), C("Modular Frame", 25), C("Copper Sheet", 50), C("Wire", 250)]),
        ["Industrial Fluid Buffer"] = new("5-5", Cost: [C("Encased Industrial Beam", 5), C("Copper Sheet", 10), C("Plastic", 25)]),
        ["Industrial Storage Container"] = new("4-2", Cost: [C("Steel Beam", 20), C("Steel Pipe", 20)]),
        ["Manufacturer"] = new("6-1", Power: -55, OverclockExp: R("1321929/1000000"), Sloops: 4, SloopMultiplier: R("1/4"), SloopPowerExp: 2, Cost: [C("Motor", 10), C("Modular Frame", 20), C("Plastic", 50), C("Cable", 50)]),
        ["Miner Mk.1"] = new("0-5", Power: -5, OverclockExp: R("1321929/1000000"), Cost: [C("Portable Miner", 1), C("Iron Plate", 10), C("Concrete", 10)], Throughput: 60),
        ["Miner Mk.2"] = new("4-3", Power: -15, OverclockExp: R("1321929/1000000"), Cost: [C("Portable Miner", 2), C("Encased Industrial Beam", 10), C("Steel Pipe", 20), C("Modular Frame", 10)], Throughput: 120),
        ["Miner Mk.3"] = new("8-4", Power: -45, OverclockExp: R("1321929/1000000"), Cost: [C("Portable Miner", 3), C("Steel Pipe", 50), C("Supercomputer", 5), C("Fused Modular Frame", 10), C("Turbo Motor", 3)], Throughput: 240),
        ["Nuclear Power Plant"] = new("8-2", Power: 2500, OverclockExp: 1, Cost: [C("Supercomputer", 10), C("Heavy Modular Frame", 25), C("Alclad Aluminum Sheet", 100), C("Cable", 200), C("Concrete", 250)]),
        ["Oil Extractor"] = new("5-2", Power: -40, OverclockExp: R("1321929/1000000"), Cost: [C("Motor", 15), C("Encased Industrial Beam", 20), C("Cable", 60)]),
        ["Packager"] = new("5-4", Power: -10, OverclockExp: R("1321929/1000000"), Cost: [C("Steel Beam", 20), C("Rubber", 10), C("Plastic", 10)]),
        ["Particle Accelerator"] = new("8-5", OverclockExp: R("1321929/1000000"), Sloops: 4, SloopMultiplier: R("1/4"), SloopPowerExp: 2, Cost: [C("Turbo Motor", 10), C("Supercomputer", 10), C("Fused Modular Frame", 25), C("Cooling System", 50), C("Quickwire", 500)]),
        ["Quantum Encoder"] = new("9-2", OverclockExp: R("1321929/1000000"), Sloops: 4, SloopMultiplier: R("1/4"), SloopPowerExp: 2, Cost: [C("Turbo Motor", 20), C("Supercomputer", 20), C("Cooling System", 50), C("Time Crystal", 50), C("Ficsite Trigon", 100)]),
        ["Refinery"] = new("5-2", Power: -30, OverclockExp: R("1321929/1000000"), Sloops: 2, SloopMultiplier: R("1/2"), SloopPowerExp: 2, Cost: [C("Motor", 10), C("Encased Industrial Beam", 10), C("Steel Pipe", 30), C("Copper Sheet", 20)]),
        ["Resource Well Extractor"] = new("8-3", Cost: [C("Steel Beam", 10), C("Aluminum Casing", 10)]),
        ["Resource Well Pressurizer"] = new("8-3", Power: -150, OverclockExp: R("1321929/1000000"), Cost: [C("Radio Control Unit", 10), C("Heavy Modular Frame", 25), C("Motor", 50), C("Alclad Aluminum Sheet", 50), C("Rubber", 100)]),
        ["Smelter"] = new("0-2", Power: -4, OverclockExp: R("1321929/1000000"), Sloops: 1, SloopMultiplier: 1, SloopPowerExp: 2, Cost: [C("Iron Rod", 5), C("Wire", 8)]),
        ["Space Elevator"] = new("0-6", Cost: [C("Concrete", 500), C("Iron Plate", 250), C("Iron Rod", 400), C("Wire", 1500)]),
        ["Storage Container"] = new("0-5", Cost: [C("Iron Plate", 10), C("Iron Rod", 10)]),
        ["Water Extractor"] = new("3-1", Power: -20, OverclockExp: R("1321929/1000000"), Cost: [C("Copper Sheet", 20), C("Reinforced Iron Plate", 10), C("Rotor", 10)]),
    };

    private static Rational R(string text) => Rational.Parse(text);

    private static CostEntry C(string part, int amount) => new() { Part = part, Amount = amount };
}
