// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines;

public sealed class Manufacturer : MachineBase
{
    public override int SortIndex => 20;
    public override string MachineName => "Manufacturer";
    public override string Tier => "6-1";
    public override string? AveragePower => "-55";
    public override string? OverclockPowerExponent => "1321929/1000000";
    public override string? ProductionShardMultiplier => "1/4";
    public override string? ProductionShardPowerExponent => "2";
    public override int MaxProductionShards => 4;

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Motor", Amount = "10" },
        new() { Part = "Modular Frame", Amount = "20" },
        new() { Part = "Plastic", Amount = "50" },
        new() { Part = "Cable", Amount = "50" },
    ];
}
