// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines;

public sealed class MinerMk2 : MachineBase
{
    public override int SortIndex => 14;
    public override string MachineName => "Miner Mk.2";
    public override string Tier => "4-3";
    public override string? AveragePower => "-15";
    public override string? OverclockPowerExponent => "1321929/1000000";

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Portable Miner", Amount = "2" },
        new() { Part = "Encased Industrial Beam", Amount = "10" },
        new() { Part = "Steel Pipe", Amount = "20" },
        new() { Part = "Modular Frame", Amount = "10" },
    ];
}
