// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines;

public sealed class MinerMk3 : MachineBase
{
    public override int SortIndex => 26;
    public override string MachineName => "Miner Mk.3";
    public override string Tier => "8-4";
    public override string? AveragePower => "-45";
    public override string? OverclockPowerExponent => "1321929/1000000";

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Portable Miner", Amount = "3" },
        new() { Part = "Steel Pipe", Amount = "50" },
        new() { Part = "Supercomputer", Amount = "5" },
        new() { Part = "Fused Modular Frame", Amount = "10" },
        new() { Part = "Turbo Motor", Amount = "3" },
    ];
}
