// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines;

public sealed class MinerMk1 : MachineBase
{
    public override int SortIndex => 4;
    public override string MachineName => "Miner Mk.1";
    public override string Tier => "0-5";
    public override string? AveragePower => "-5";
    public override string? OverclockPowerExponent => "1321929/1000000";

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Portable Miner", Amount = "1" },
        new() { Part = "Iron Plate", Amount = "10" },
        new() { Part = "Concrete", Amount = "10" },
    ];
}
