// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines;

public sealed class OilExtractor : MachineBase
{
    public override int SortIndex => 16;
    public override string MachineName => "Oil Extractor";
    public override string Tier => "5-2";
    public override string? AveragePower => "-40";
    public override string? OverclockPowerExponent => "1321929/1000000";

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Motor", Amount = "15" },
        new() { Part = "Encased Industrial Beam", Amount = "20" },
        new() { Part = "Cable", Amount = "60" },
    ];
}
