// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines;

public sealed class QuantumEncoder : MachineBase
{
    public override int SortIndex => 31;
    public override string MachineName => "Quantum Encoder";
    public override string Tier => "9-2";
    public override string? OverclockPowerExponent => "1321929/1000000";
    public override string? ProductionShardMultiplier => "1/4";
    public override string? ProductionShardPowerExponent => "2";
    public override int MaxProductionShards => 4;

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Turbo Motor", Amount = "20" },
        new() { Part = "Supercomputer", Amount = "20" },
        new() { Part = "Cooling System", Amount = "50" },
        new() { Part = "Time Crystal", Amount = "50" },
        new() { Part = "Ficsite Trigon", Amount = "100" },
    ];
}
