// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines;

public sealed class Refinery : MachineBase
{
    public override int SortIndex => 15;
    public override string MachineName => "Refinery";
    public override string Tier => "5-2";
    public override string? AveragePower => "-30";
    public override string? OverclockPowerExponent => "1321929/1000000";
    public override string? ProductionShardMultiplier => "1/2";
    public override string? ProductionShardPowerExponent => "2";
    public override int MaxProductionShards => 2;

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Motor", Amount = "10" },
        new() { Part = "Encased Industrial Beam", Amount = "10" },
        new() { Part = "Steel Pipe", Amount = "30" },
        new() { Part = "Copper Sheet", Amount = "20" },
    ];
}
