// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines;

public sealed class ResourceWellExtractor : MachineBase
{
    public override int SortIndex => 24;
    public override string MachineName => "Resource Well Extractor";
    public override string Tier => "8-3";

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Steel Beam", Amount = "10" },
        new() { Part = "Aluminum Casing", Amount = "10" },
    ];
}
