// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines;

public sealed class SpaceElevator : MachineBase
{
    public override int SortIndex => 5;
    public override string MachineName => "Space Elevator";
    public override string Tier => "0-6";

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Concrete", Amount = "500" },
        new() { Part = "Iron Plate", Amount = "250" },
        new() { Part = "Iron Rod", Amount = "400" },
        new() { Part = "Wire", Amount = "1500" },
    ];
}
