// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines;

public sealed class StorageContainer : MachineBase
{
    public override int SortIndex => 3;
    public override string MachineName => "Storage Container";
    public override string Tier => "0-5";

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Iron Plate", Amount = "10" },
        new() { Part = "Iron Rod", Amount = "10" },
    ];
}
