// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class AdheredIronPlate : RecipeBase
{
    public override int SortIndex => 59;
    public override string RecipeName => "Adhered Iron Plate";
    public override string Machine => "Assembler";
    public override string BatchTime => "16";
    public override string Tier => "5-2";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Iron Plate", Amount = "-3" },
        new() { Part = "Rubber", Amount = "-1" },
        new() { Part = "Reinforced Iron Plate", Amount = "1" },
    ];
}
