// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class AutomatedMiner : RecipeBase
{
    public override int SortIndex => 114;
    public override string RecipeName => "Automated Miner";
    public override string Machine => "Assembler";
    public override string BatchTime => "60";
    public override string Tier => "3-3";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Steel Pipe", Amount = "-4" },
        new() { Part = "Iron Plate", Amount = "-4" },
        new() { Part = "Portable Miner", Amount = "1" },
    ];
}
