// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class AutomatedWiring : RecipeBase
{
    public override int SortIndex => 126;
    public override string RecipeName => "Automated Wiring";
    public override string Machine => "Assembler";
    public override string BatchTime => "24";
    public override string Tier => "4-3";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Stator", Amount = "-1" },
        new() { Part = "Cable", Amount = "-20" },
        new() { Part = "Automated Wiring", Amount = "1" },
    ];
}
