// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class BoltedIronPlate : RecipeBase
{
    public override int SortIndex => 57;
    public override string RecipeName => "Bolted Iron Plate";
    public override string Machine => "Assembler";
    public override string BatchTime => "12";
    public override string Tier => "2-1";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Iron Plate", Amount = "-18" },
        new() { Part = "Screw", Amount = "-50" },
        new() { Part = "Reinforced Iron Plate", Amount = "3" },
    ];
}
