// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class CheapSilica : RecipeBase
{
    public override int SortIndex => 79;
    public override string RecipeName => "Cheap Silica";
    public override string Machine => "Assembler";
    public override string BatchTime => "8";
    public override string Tier => "2-1";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Raw Quartz", Amount = "-3" },
        new() { Part = "Limestone", Amount = "-5" },
        new() { Part = "Silica", Amount = "7" },
    ];
}
