// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class ElectrodeCircuitBoard : RecipeBase
{
    public override int SortIndex => 141;
    public override string RecipeName => "Electrode Circuit Board";
    public override string Machine => "Assembler";
    public override string BatchTime => "12";
    public override string Tier => "5-2";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Rubber", Amount = "-4" },
        new() { Part = "Petroleum Coke", Amount = "-8" },
        new() { Part = "Circuit Board", Amount = "1" },
    ];
}
