// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class ElectricMotor : RecipeBase
{
    public override int SortIndex => 131;
    public override string RecipeName => "Electric Motor";
    public override string Machine => "Assembler";
    public override string BatchTime => "16";
    public override string Tier => "8-2";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Electromagnetic Control Rod", Amount = "-1" },
        new() { Part = "Rotor", Amount = "-2" },
        new() { Part = "Motor", Amount = "2" },
    ];
}
