// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class EncasedIndustrialPipe : RecipeBase
{
    public override int SortIndex => 125;
    public override string RecipeName => "Encased Industrial Pipe";
    public override string Machine => "Assembler";
    public override string BatchTime => "15";
    public override string Tier => "4-3";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Steel Pipe", Amount = "-6" },
        new() { Part = "Concrete", Amount = "-5" },
        new() { Part = "Encased Industrial Beam", Amount = "1" },
    ];
}
