// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class EncasedIndustrialBeam : RecipeBase
{
    public override int SortIndex => 124;
    public override string RecipeName => "Encased Industrial Beam";
    public override string Machine => "Assembler";
    public override string BatchTime => "10";
    public override string Tier => "4-3";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Steel Beam", Amount = "-3" },
        new() { Part = "Concrete", Amount = "-6" },
        new() { Part = "Encased Industrial Beam", Amount = "1" },
    ];
}
