// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class EncasedPlutoniumCell : RecipeBase
{
    public override int SortIndex => 278;
    public override string RecipeName => "Encased Plutonium Cell";
    public override string Machine => "Assembler";
    public override string BatchTime => "12";
    public override string Tier => "8-5";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Plutonium Pellet", Amount = "-2" },
        new() { Part = "Concrete", Amount = "-4" },
        new() { Part = "Encased Plutonium Cell", Amount = "1" },
    ];
}
