// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class FancyFireworks : RecipeBase
{
    public override int SortIndex => 325;
    public override string RecipeName => "Fancy Fireworks";
    public override string Machine => "Assembler";
    public override string BatchTime => "24";
    public override string Tier => "2-1";
    public override bool Ficsmas => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "FICSMAS Tree Branch", Amount = "-4" },
        new() { Part = "FICSMAS Bow", Amount = "-3" },
        new() { Part = "Fancy Fireworks", Amount = "1" },
    ];
}
