// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class FICSMASOrnamentBundle : RecipeBase
{
    public override int SortIndex => 329;
    public override string RecipeName => "FICSMAS Ornament Bundle";
    public override string Machine => "Assembler";
    public override string BatchTime => "12";
    public override string Tier => "3-3";
    public override bool Ficsmas => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Copper FICSMAS Ornament", Amount = "-1" },
        new() { Part = "Iron FICSMAS Ornament", Amount = "-1" },
        new() { Part = "FICSMAS Ornament Bundle", Amount = "1" },
    ];
}
