// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class FICSMASWreath : RecipeBase
{
    public override int SortIndex => 330;
    public override string RecipeName => "FICSMAS Wreath";
    public override string Machine => "Assembler";
    public override string BatchTime => "60";
    public override string Tier => "3-3";
    public override bool Ficsmas => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "FICSMAS Tree Branch", Amount = "-15" },
        new() { Part = "FICSMAS Ornament Bundle", Amount = "-6" },
        new() { Part = "FICSMAS Wreath", Amount = "2" },
    ];
}
