// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class FusedWire : RecipeBase
{
    public override int SortIndex => 38;
    public override string RecipeName => "Fused Wire";
    public override string Machine => "Assembler";
    public override string BatchTime => "20";
    public override string Tier => "5-5";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Copper Ingot", Amount = "-4" },
        new() { Part = "Caterium Ingot", Amount = "-1" },
        new() { Part = "Wire", Amount = "30" },
    ];
}
