// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class GasNobelisk : RecipeBase
{
    public override int SortIndex => 119;
    public override string RecipeName => "Gas Nobelisk";
    public override string Machine => "Assembler";
    public override string BatchTime => "12";
    public override string Tier => "3-3";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Nobelisk", Amount = "-1" },
        new() { Part = "Biomass", Amount = "-10" },
        new() { Part = "Gas Nobelisk", Amount = "1" },
    ];
}
