// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class HeatExchanger : RecipeBase
{
    public override int SortIndex => 257;
    public override string RecipeName => "Heat Exchanger";
    public override string Machine => "Assembler";
    public override string BatchTime => "6";
    public override string Tier => "8-3";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Aluminum Casing", Amount = "-3" },
        new() { Part = "Rubber", Amount = "-3" },
        new() { Part = "Heat Sink", Amount = "1" },
    ];
}
