// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class HomingRifleAmmo : RecipeBase
{
    public override int SortIndex => 200;
    public override string RecipeName => "Homing Rifle Ammo";
    public override string Machine => "Assembler";
    public override string BatchTime => "24";
    public override string Tier => "6-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Rifle Ammo", Amount = "-20" },
        new() { Part = "High-Speed Connector", Amount = "-1" },
        new() { Part = "Homing Rifle Ammo", Amount = "10" },
    ];
}
