// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class MagneticFieldGenerator : RecipeBase
{
    public override int SortIndex => 250;
    public override string RecipeName => "Magnetic Field Generator";
    public override string Machine => "Assembler";
    public override string BatchTime => "120";
    public override string Tier => "8-2";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Versatile Framework", Amount = "-5" },
        new() { Part = "Electromagnetic Control Rod", Amount = "-2" },
        new() { Part = "Magnetic Field Generator", Amount = "2" },
    ];
}
