// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class ModularFrame : RecipeBase
{
    public override int SortIndex => 91;
    public override string RecipeName => "Modular Frame";
    public override string Machine => "Assembler";
    public override string BatchTime => "60";
    public override string Tier => "2-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Reinforced Iron Plate", Amount = "-3" },
        new() { Part = "Iron Rod", Amount = "-12" },
        new() { Part = "Modular Frame", Amount = "2" },
    ];
}
