// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class Motor : RecipeBase
{
    public override int SortIndex => 129;
    public override string RecipeName => "Motor";
    public override string Machine => "Assembler";
    public override string BatchTime => "12";
    public override string Tier => "4-3";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Rotor", Amount = "-2" },
        new() { Part = "Stator", Amount = "-2" },
        new() { Part = "Motor", Amount = "1" },
    ];
}
