// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class Nobelisk : RecipeBase
{
    public override int SortIndex => 118;
    public override string RecipeName => "Nobelisk";
    public override string Machine => "Assembler";
    public override string BatchTime => "6";
    public override string Tier => "3-3";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Black Powder", Amount = "-2" },
        new() { Part = "Steel Pipe", Amount = "-2" },
        new() { Part = "Nobelisk", Amount = "1" },
    ];
}
