// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class PlasticAILimiter : RecipeBase
{
    public override int SortIndex => 197;
    public override string RecipeName => "Plastic AI Limiter";
    public override string Machine => "Assembler";
    public override string BatchTime => "15";
    public override string Tier => "5-5";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Quickwire", Amount = "-30" },
        new() { Part = "Plastic", Amount = "-7" },
        new() { Part = "AI Limiter", Amount = "2" },
    ];
}
