// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class PlutoniumFuelUnit : RecipeBase
{
    public override int SortIndex => 273;
    public override string RecipeName => "Plutonium Fuel Unit";
    public override string Machine => "Assembler";
    public override string BatchTime => "120";
    public override string Tier => "8-5";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Encased Plutonium Cell", Amount = "-20" },
        new() { Part = "Pressure Conversion Cube", Amount = "-1" },
        new() { Part = "Plutonium Fuel Rod", Amount = "1" },
    ];
}
