// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class PulseNobelisk : RecipeBase
{
    public override int SortIndex => 201;
    public override string RecipeName => "Pulse Nobelisk";
    public override string Machine => "Assembler";
    public override string BatchTime => "60";
    public override string Tier => "6-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Nobelisk", Amount = "-5" },
        new() { Part = "Crystal Oscillator", Amount = "-1" },
        new() { Part = "Pulse Nobelisk", Amount = "5" },
    ];
}
