// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class QuickwireStator : RecipeBase
{
    public override int SortIndex => 123;
    public override string RecipeName => "Quickwire Stator";
    public override string Machine => "Assembler";
    public override string BatchTime => "15";
    public override string Tier => "5-5";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Steel Pipe", Amount = "-4" },
        new() { Part = "Quickwire", Amount = "-15" },
        new() { Part = "Stator", Amount = "2" },
    ];
}
