// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class Rotor : RecipeBase
{
    public override int SortIndex => 87;
    public override string RecipeName => "Rotor";
    public override string Machine => "Assembler";
    public override string BatchTime => "15";
    public override string Tier => "2-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Iron Rod", Amount = "-5" },
        new() { Part = "Screw", Amount = "-25" },
        new() { Part = "Rotor", Amount = "1" },
    ];
}
