// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class RubberConcrete : RecipeBase
{
    public override int SortIndex => 54;
    public override string RecipeName => "Rubber Concrete";
    public override string Machine => "Assembler";
    public override string BatchTime => "6";
    public override string Tier => "5-2";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Limestone", Amount = "-10" },
        new() { Part = "Rubber", Amount = "-2" },
        new() { Part = "Concrete", Amount = "9" },
    ];
}
