// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Assembler;

public sealed class VersatileFramework : RecipeBase
{
    public override int SortIndex => 120;
    public override string RecipeName => "Versatile Framework";
    public override string Machine => "Assembler";
    public override string BatchTime => "24";
    public override string Tier => "3-3";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Modular Frame", Amount = "-1" },
        new() { Part = "Steel Beam", Amount = "-12" },
        new() { Part = "Versatile Framework", Amount = "2" },
    ];
}
