// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.CoalPoweredGenerator;

public sealed class CompactedCoalGenerator : RecipeBase
{
    public override int SortIndex => 153;
    public override string RecipeName => "Compacted Coal Generator";
    public override string Machine => "Coal-Powered Generator";
    public override string BatchTime => "42/5";
    public override string Tier => "5-4";
    public override bool IgnoreInputMultiplier => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Compacted Coal", Amount = "-1" },
        new() { Part = "Water", Amount = "-63/10" },
    ];
}
