// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.CoalPoweredGenerator;

public sealed class PetroleumCokeGenerator : RecipeBase
{
    public override int SortIndex => 133;
    public override string RecipeName => "Petroleum Coke Generator";
    public override string Machine => "Coal-Powered Generator";
    public override string BatchTime => "12/5";
    public override string Tier => "5-2";
    public override bool IgnoreInputMultiplier => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Petroleum Coke", Amount = "-1" },
        new() { Part = "Water", Amount = "-9/5" },
    ];
}
