// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines.Special;

public sealed class AWESOMESink : SpecialBase
{
    public override int SortIndex => 8;
    public override string MachineName => "AWESOME Sink";
    public override string Tier => "2-4";
    public override int FamilySortIndex => 4;
    public override bool ShowPpm => true;
    public override string? AveragePower => "-30";

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Reinforced Iron Plate", Amount = "15" },
        new() { Part = "Cable", Amount = "30" },
        new() { Part = "Concrete", Amount = "45" },
    ];

    public override IReadOnlyList<MultiMachineCapacity> FamilyCapacities =>
    [
        new() { Name = "Mk.1 Belt", PartsRatio = "60", Default = true },
        new() { Name = "Mk.2 Belt", PartsRatio = "120", Color = 13775920 },
        new() { Name = "Mk.3 Belt", PartsRatio = "270", Color = 16311334 },
        new() { Name = "Mk.4 Belt", PartsRatio = "480", Color = 8433977 },
        new() { Name = "Mk.5 Belt", PartsRatio = "780", Color = 2504952 },
        new() { Name = "Mk.6 Belt", PartsRatio = "1200", Color = 12330744 },
    ];

    public override MultiMachineDefinition ToFamilyDefinition() => new()
    {
        Name = "AWESOME Sink",
        ShowPpm = true,
        Capacities =
        [
            new() { Name = "Mk.1 Belt", PartsRatio = "60", Default = true },
            new() { Name = "Mk.2 Belt", PartsRatio = "120", Color = 13775920 },
            new() { Name = "Mk.3 Belt", PartsRatio = "270", Color = 16311334 },
            new() { Name = "Mk.4 Belt", PartsRatio = "480", Color = 8433977 },
            new() { Name = "Mk.5 Belt", PartsRatio = "780", Color = 2504952 },
            new() { Name = "Mk.6 Belt", PartsRatio = "1200", Color = 12330744 },
        ],
    };
}
