// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines.Special;

public sealed class DimensionalDepotUploader : SpecialBase
{
    public override int SortIndex => 30;
    public override string MachineName => "Dimensional Depot Uploader";
    public override string Tier => "9-1";
    public override int FamilySortIndex => 3;
    public override bool ShowPpm => true;

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Mercer Sphere", Amount = "1" },
        new() { Part = "SAM Fluctuator", Amount = "10" },
        new() { Part = "Modular Frame", Amount = "10" },
        new() { Part = "Wire", Amount = "100" },
    ];

    public override IReadOnlyList<MultiMachineCapacity> FamilyCapacities =>
    [
        new() { Name = "15/min", PartsRatio = "15", Default = true },
        new() { Name = "30/min", PartsRatio = "30", Color = 13775920 },
        new() { Name = "60/min", PartsRatio = "60", Color = 16311334 },
        new() { Name = "120/min", PartsRatio = "120", Color = 8433977 },
        new() { Name = "240/min", PartsRatio = "240", Color = 12330744 },
    ];

    public override MultiMachineDefinition ToFamilyDefinition() => new()
    {
        Name = "Dimensional Depot Uploader",
        ShowPpm = true,
        Capacities =
        [
            new() { Name = "15/min", PartsRatio = "15", Default = true },
            new() { Name = "30/min", PartsRatio = "30", Color = 13775920 },
            new() { Name = "60/min", PartsRatio = "60", Color = 16311334 },
            new() { Name = "120/min", PartsRatio = "120", Color = 8433977 },
            new() { Name = "240/min", PartsRatio = "240", Color = 12330744 },
        ],
    };
}
