// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.ParticleAccelerator;

public sealed class DarkMatterTrap : RecipeBase
{
    public override int SortIndex => 303;
    public override string RecipeName => "Dark Matter Trap";
    public override string Machine => "Particle Accelerator";
    public override string BatchTime => "2";
    public override string Tier => "9-2";
    public override bool Alternate => true;
    public override string? AveragePower => "-1000";
    public override string? MinPower => "-1500";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Time Crystal", Amount = "-1" },
        new() { Part = "Dark Matter Residue", Amount = "-5" },
        new() { Part = "Dark Matter Crystal", Amount = "2" },
    ];
}
