// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.ParticleAccelerator;

public sealed class Diamonds : RecipeBase
{
    public override int SortIndex => 287;
    public override string RecipeName => "Diamonds";
    public override string Machine => "Particle Accelerator";
    public override string BatchTime => "2";
    public override string Tier => "9-1";
    public override string? AveragePower => "-500";
    public override string? MinPower => "-750";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Coal", Amount = "-20" },
        new() { Part = "Diamonds", Amount = "1" },
    ];
}
