// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.ResourceWellExtractor;

public sealed class OilWell : RecipeBase
{
    public override int SortIndex => 11;
    public override string RecipeName => "Oil Well";
    public override string Machine => "Resource Well Extractor";
    public override string BatchTime => "1";
    public override string Tier => "8-3";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Crude Oil", Amount = "1" },
    ];
}
