// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.ResourceWellExtractor;

public sealed class WellWater : RecipeBase
{
    public override int SortIndex => 9;
    public override string RecipeName => "Well Water";
    public override string Machine => "Resource Well Extractor";
    public override string BatchTime => "1";
    public override string Tier => "8-3";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Water", Amount = "1" },
    ];
}
