// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines.Production;

public sealed class Blender : ProductionBase
{
    public override int SortIndex => 22;
    public override string MachineName => "Blender";
    public override string Tier => "7-5";
    public override string? AveragePower => "-75";
    public override string? OverclockPowerExponent => "1321929/1000000";
    public override string? ProductionShardMultiplier => "1/4";
    public override string? ProductionShardPowerExponent => "2";
    public override int MaxProductionShards => 4;

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Computer", Amount = "10" },
        new() { Part = "Heavy Modular Frame", Amount = "10" },
        new() { Part = "Motor", Amount = "20" },
        new() { Part = "Aluminum Casing", Amount = "50" },
    ];
}
