// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines.Production;

public sealed class Constructor : ProductionBase
{
    public override int SortIndex => 2;
    public override string MachineName => "Constructor";
    public override string Tier => "0-3";
    public override string? AveragePower => "-4";
    public override string? OverclockPowerExponent => "1321929/1000000";
    public override string? ProductionShardMultiplier => "1";
    public override string? ProductionShardPowerExponent => "2";
    public override int MaxProductionShards => 1;

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Reinforced Iron Plate", Amount = "2" },
        new() { Part = "Cable", Amount = "8" },
    ];
}
