// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines.Production;

public sealed class Converter : ProductionBase
{
    public override int SortIndex => 29;
    public override string MachineName => "Converter";
    public override string Tier => "9-1";
    public override string? OverclockPowerExponent => "1321929/1000000";
    public override string? ProductionShardMultiplier => "1/2";
    public override string? ProductionShardPowerExponent => "2";
    public override int MaxProductionShards => 2;

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Fused Modular Frame", Amount = "10" },
        new() { Part = "Cooling System", Amount = "25" },
        new() { Part = "Radio Control Unit", Amount = "50" },
        new() { Part = "SAM Fluctuator", Amount = "100" },
    ];
}
