// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Machines.Production;

public sealed class Packager : ProductionBase
{
    public override int SortIndex => 17;
    public override string MachineName => "Packager";
    public override string Tier => "5-4";
    public override string? AveragePower => "-10";
    public override string? OverclockPowerExponent => "1321929/1000000";

    public override IReadOnlyList<CostEntry> Cost =>
    [
        new() { Part = "Steel Beam", Amount = "20" },
        new() { Part = "Rubber", Amount = "10" },
        new() { Part = "Plastic", Amount = "10" },
    ];
}
