// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Miner;

public sealed class CateriumOre : RecipeBase
{
    public override int SortIndex => 3;
    public override string RecipeName => "Caterium Ore";
    public override string Machine => "Miner";
    public override string BatchTime => "60";
    public override string Tier => "0-5";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Caterium Ore", Amount = "1" },
    ];
}
