// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.OilExtractor;

public sealed class CrudeOil : RecipeBase
{
    public override int SortIndex => 10;
    public override string RecipeName => "Crude Oil";
    public override string Machine => "Oil Extractor";
    public override string BatchTime => "1";
    public override string Tier => "5-2";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Crude Oil", Amount = "2" },
    ];
}
