// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.SpaceElevator;

public sealed class SpaceElevatorPhase3 : RecipeBase
{
    public override int SortIndex => 214;
    public override string RecipeName => "Space Elevator Phase 3";
    public override string Machine => "Space Elevator";
    public override string BatchTime => "60";
    public override string Tier => "6-1";
    public override string? SpaceElevatorMultiplier => "True";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Versatile Framework", Amount = "-2500" },
        new() { Part = "Modular Engine", Amount = "-500" },
        new() { Part = "Adaptive Control Unit", Amount = "-100" },
    ];
}
