// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Refinery;

public sealed class CoatedCable : RecipeBase
{
    public override int SortIndex => 40;
    public override string RecipeName => "Coated Cable";
    public override string Machine => "Refinery";
    public override string BatchTime => "8";
    public override string Tier => "5-2";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Wire", Amount = "-5" },
        new() { Part = "Heavy Oil Residue", Amount = "-2" },
        new() { Part = "Cable", Amount = "9" },
    ];
}
