// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Refinery;

public sealed class DilutedPackagedFuel : RecipeBase
{
    public override int SortIndex => 167;
    public override string RecipeName => "Diluted Packaged Fuel";
    public override string Machine => "Refinery";
    public override string BatchTime => "2";
    public override string Tier => "5-4";
    public override bool Alternate => true;
    public override bool IgnoreInputMultiplier => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Heavy Oil Residue", Amount = "-1" },
        new() { Part = "Packaged Water", Amount = "-2" },
        new() { Part = "Packaged Fuel", Amount = "2" },
    ];
}
