// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Refinery;

public sealed class ElectrodeAluminumScrap : RecipeBase
{
    public override int SortIndex => 219;
    public override string RecipeName => "Electrode Aluminum Scrap";
    public override string Machine => "Refinery";
    public override string BatchTime => "4";
    public override string Tier => "7-1";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Alumina Solution", Amount = "-12" },
        new() { Part = "Petroleum Coke", Amount = "-4" },
        new() { Part = "Aluminum Scrap", Amount = "20" },
        new() { Part = "Water", Amount = "7" },
    ];
}
