// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Refinery;

public sealed class Fuel : RecipeBase
{
    public override int SortIndex => 145;
    public override string RecipeName => "Fuel";
    public override string Machine => "Refinery";
    public override string BatchTime => "6";
    public override string Tier => "5-2";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Crude Oil", Amount = "-6" },
        new() { Part = "Fuel", Amount = "4" },
        new() { Part = "Polymer Resin", Amount = "3" },
    ];
}
