// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Refinery;

public sealed class IonizedFuel : RecipeBase
{
    public override int SortIndex => 173;
    public override string RecipeName => "Ionized Fuel";
    public override string Machine => "Refinery";
    public override string BatchTime => "24";
    public override string Tier => "5-4";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Rocket Fuel", Amount = "-16" },
        new() { Part = "Power Shard", Amount = "-1" },
        new() { Part = "Ionized Fuel", Amount = "16" },
        new() { Part = "Compacted Coal", Amount = "2" },
    ];
}
