// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Refinery;

public sealed class Plastic : RecipeBase
{
    public override int SortIndex => 149;
    public override string RecipeName => "Plastic";
    public override string Machine => "Refinery";
    public override string BatchTime => "6";
    public override string Tier => "5-2";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Crude Oil", Amount = "-3" },
        new() { Part = "Plastic", Amount = "2" },
        new() { Part = "Heavy Oil Residue", Amount = "1" },
    ];
}
