// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Refinery;

public sealed class PolyesterFabric : RecipeBase
{
    public override int SortIndex => 86;
    public override string RecipeName => "Polyester Fabric";
    public override string Machine => "Refinery";
    public override string BatchTime => "2";
    public override string Tier => "5-2";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Polymer Resin", Amount = "-1" },
        new() { Part = "Water", Amount = "-1" },
        new() { Part = "Fabric", Amount = "1" },
    ];
}
