// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Refinery;

public sealed class PureCateriumIngot : RecipeBase
{
    public override int SortIndex => 192;
    public override string RecipeName => "Pure Caterium Ingot";
    public override string Machine => "Refinery";
    public override string BatchTime => "5";
    public override string Tier => "5-5";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Caterium Ore", Amount = "-2" },
        new() { Part = "Water", Amount = "-2" },
        new() { Part = "Caterium Ingot", Amount = "1" },
    ];
}
