// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Refinery;

public sealed class QuartzPurification : RecipeBase
{
    public override int SortIndex => 277;
    public override string RecipeName => "Quartz Purification";
    public override string Machine => "Refinery";
    public override string BatchTime => "12";
    public override string Tier => "8-5";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Raw Quartz", Amount = "-24" },
        new() { Part = "Nitric Acid", Amount = "-2" },
        new() { Part = "Quartz Crystal", Amount = "15" },
        new() { Part = "Dissolved Silica", Amount = "12" },
    ];
}
