// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Refinery;

public sealed class RecycledRubber : RecipeBase
{
    public override int SortIndex => 137;
    public override string RecipeName => "Recycled Rubber";
    public override string Machine => "Refinery";
    public override string BatchTime => "12";
    public override string Tier => "5-2";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Plastic", Amount = "-6" },
        new() { Part = "Fuel", Amount = "-6" },
        new() { Part = "Rubber", Amount = "12" },
    ];
}
