// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Refinery;

public sealed class SloppyAlumina : RecipeBase
{
    public override int SortIndex => 231;
    public override string RecipeName => "Sloppy Alumina";
    public override string Machine => "Refinery";
    public override string BatchTime => "3";
    public override string Tier => "7-1";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Bauxite", Amount = "-10" },
        new() { Part = "Water", Amount = "-10" },
        new() { Part = "Alumina Solution", Amount = "12" },
    ];
}
