// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Refinery;

public sealed class SmokelessPowder : RecipeBase
{
    public override int SortIndex => 135;
    public override string RecipeName => "Smokeless Powder";
    public override string Machine => "Refinery";
    public override string BatchTime => "6";
    public override string Tier => "5-2";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Black Powder", Amount = "-2" },
        new() { Part = "Heavy Oil Residue", Amount = "-1" },
        new() { Part = "Smokeless Powder", Amount = "2" },
    ];
}
