// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Refinery;

public sealed class SulfuricAcid : RecipeBase
{
    public override int SortIndex => 243;
    public override string RecipeName => "Sulfuric Acid";
    public override string Machine => "Refinery";
    public override string BatchTime => "6";
    public override string Tier => "7-5";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Sulfur", Amount = "-5" },
        new() { Part = "Water", Amount = "-5" },
        new() { Part = "Sulfuric Acid", Amount = "5" },
    ];
}
