// <auto-generated>
// Generated by Ficsit.Schematics.CatalogGenerator from Docs/en-US.json — do not edit.
// Regenerate with: dotnet run --project Ficsit.Schematics.CatalogGenerator -- --write
// </auto-generated>
namespace Ficsit.Schematics.Core.Serialization;

/// <summary>
/// Legacy part/recipe/machine names → the game's current official names. Documents
/// written before a rename keep loading: the .sfmd reader resolves every stored
/// name through this table.
/// </summary>
public static class NameAliases
{
    /// <summary>The official name for a possibly-legacy one (unknown names pass through).</summary>
    public static string Resolve(string name)
        => ByLegacyName.TryGetValue(name, out var official) ? official : name;

    public static readonly IReadOnlyDictionary<string, string> ByLegacyName = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["Cast Screw"] = "Cast Screws",
        ["Leached Iron ingot"] = "Leached Iron Ingot",
        ["Screw"] = "Screws",
        ["Steel Screw"] = "Steel Screws",
    };
}
