// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Constructor;

public sealed class AluminumBeam : RecipeBase
{
    public override int SortIndex => 117;
    public override string RecipeName => "Aluminum Beam";
    public override string Machine => "Constructor";
    public override string BatchTime => "8";
    public override string Tier => "7-1";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Aluminum Ingot", Amount = "-3" },
        new() { Part = "Steel Beam", Amount = "3" },
    ];
}
