// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Constructor;

public sealed class BiomassLeaves : RecipeBase
{
    public override int SortIndex => 49;
    public override string RecipeName => "Biomass (Leaves)";
    public override string Machine => "Constructor";
    public override string BatchTime => "5";
    public override string Tier => "0-6";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Leaves", Amount = "-10" },
        new() { Part = "Biomass", Amount = "5" },
    ];
}
