// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Constructor;

public sealed class Cable : RecipeBase
{
    public override int SortIndex => 39;
    public override string RecipeName => "Cable";
    public override string Machine => "Constructor";
    public override string BatchTime => "2";
    public override string Tier => "0-2";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Wire", Amount = "-2" },
        new() { Part = "Cable", Amount = "1" },
    ];
}
