// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Constructor;

public sealed class Charcoal : RecipeBase
{
    public override int SortIndex => 102;
    public override string RecipeName => "Charcoal";
    public override string Machine => "Constructor";
    public override string BatchTime => "4";
    public override string Tier => "3-1";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Wood", Amount = "-1" },
        new() { Part = "Coal", Amount = "10" },
    ];
}
