// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Constructor;

public sealed class CopperPowder : RecipeBase
{
    public override int SortIndex => 270;
    public override string RecipeName => "Copper Powder";
    public override string Machine => "Constructor";
    public override string BatchTime => "6";
    public override string Tier => "8-5";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Copper Ingot", Amount = "-30" },
        new() { Part = "Copper Powder", Amount = "5" },
    ];
}
