// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Constructor;

public sealed class EmptyCanister : RecipeBase
{
    public override int SortIndex => 155;
    public override string RecipeName => "Empty Canister";
    public override string Machine => "Constructor";
    public override string BatchTime => "4";
    public override string Tier => "5-4";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Plastic", Amount = "-2" },
        new() { Part = "Empty Canister", Amount = "4" },
    ];
}
