// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Constructor;

public sealed class FICSMASTreeBranch : RecipeBase
{
    public override int SortIndex => 318;
    public override string RecipeName => "FICSMAS Tree Branch";
    public override string Machine => "Constructor";
    public override string BatchTime => "6";
    public override string Tier => "0-3";
    public override bool Ficsmas => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "FICSMAS Gift", Amount = "-1" },
        new() { Part = "FICSMAS Tree Branch", Amount = "1" },
    ];
}
