// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Constructor;

public sealed class FICSMASBow : RecipeBase
{
    public override int SortIndex => 320;
    public override string RecipeName => "FICSMAS Bow";
    public override string Machine => "Constructor";
    public override string BatchTime => "12";
    public override string Tier => "0-3";
    public override bool Ficsmas => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "FICSMAS Gift", Amount = "-2" },
        new() { Part = "FICSMAS Bow", Amount = "1" },
    ];
}
