// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Constructor;

public sealed class FICSMASActualSnow : RecipeBase
{
    public override int SortIndex => 321;
    public override string RecipeName => "FICSMAS Actual Snow";
    public override string Machine => "Constructor";
    public override string BatchTime => "12";
    public override string Tier => "0-3";
    public override bool Ficsmas => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "FICSMAS Gift", Amount = "-5" },
        new() { Part = "FICSMAS Actual Snow", Amount = "2" },
    ];
}
