// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Constructor;

public sealed class HogProtein : RecipeBase
{
    public override int SortIndex => 62;
    public override string RecipeName => "Hog Protein";
    public override string Machine => "Constructor";
    public override string BatchTime => "3";
    public override string Tier => "0-3";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Hog Remains", Amount = "-1" },
        new() { Part = "Alien Protein", Amount = "1" },
    ];
}
