// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Constructor;

public sealed class IronPipe : RecipeBase
{
    public override int SortIndex => 112;
    public override string RecipeName => "Iron Pipe";
    public override string Machine => "Constructor";
    public override string BatchTime => "12";
    public override string Tier => "3-3";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Iron Ingot", Amount = "-20" },
        new() { Part = "Steel Pipe", Amount = "5" },
    ];
}
