// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Constructor;

public sealed class IronRebar : RecipeBase
{
    public override int SortIndex => 46;
    public override string RecipeName => "Iron Rebar";
    public override string Machine => "Constructor";
    public override string BatchTime => "4";
    public override string Tier => "0-3";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Iron Rod", Amount = "-1" },
        new() { Part = "Iron Rebar", Amount = "1" },
    ];
}
