// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Constructor;

public sealed class PowerShard1 : RecipeBase
{
    public override int SortIndex => 65;
    public override string RecipeName => "Power Shard (1)";
    public override string Machine => "Constructor";
    public override string BatchTime => "8";
    public override string Tier => "0-3";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Blue Power Slug", Amount = "-1" },
        new() { Part = "Power Shard", Amount = "1" },
    ];
}
