// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Constructor;

public sealed class Silica : RecipeBase
{
    public override int SortIndex => 78;
    public override string RecipeName => "Silica";
    public override string Machine => "Constructor";
    public override string BatchTime => "8";
    public override string Tier => "0-5";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Raw Quartz", Amount = "-3" },
        new() { Part = "Silica", Amount = "5" },
    ];
}
