// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Constructor;

public sealed class SolidBiofuel : RecipeBase
{
    public override int SortIndex => 97;
    public override string RecipeName => "Solid Biofuel";
    public override string Machine => "Constructor";
    public override string BatchTime => "4";
    public override string Tier => "2-2";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Biomass", Amount = "-8" },
        new() { Part = "Solid Biofuel", Amount = "4" },
    ];
}
