// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Constructor;

public sealed class SteelScrew : RecipeBase
{
    public override int SortIndex => 45;
    public override string RecipeName => "Steel Screw";
    public override string Machine => "Constructor";
    public override string BatchTime => "12";
    public override string Tier => "3-3";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Steel Beam", Amount = "-1" },
        new() { Part = "Screw", Amount = "52" },
    ];
}
