// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Constructor;

public sealed class SteelPipe : RecipeBase
{
    public override int SortIndex => 111;
    public override string RecipeName => "Steel Pipe";
    public override string Machine => "Constructor";
    public override string BatchTime => "6";
    public override string Tier => "3-3";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Steel Ingot", Amount = "-3" },
        new() { Part = "Steel Pipe", Amount = "2" },
    ];
}
