// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Constructor;

public sealed class Wire : RecipeBase
{
    public override int SortIndex => 35;
    public override string RecipeName => "Wire";
    public override string Machine => "Constructor";
    public override string BatchTime => "4";
    public override string Tier => "0-2";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Copper Ingot", Amount = "-1" },
        new() { Part = "Wire", Amount = "2" },
    ];
}
