using System.Text;
using Ficsit.Schematics.Core.Numerics;

namespace Ficsit.Schematics.CatalogGenerator.Emit;

/// <summary>
/// Renders the generated catalog files byte-deterministically in the repo's grouped
/// one-line-per-row style (LF endings, aligned recipe columns). Rendering is pure —
/// tests byte-compare the rendered text against the files on disk — and
/// <see cref="Write"/> puts it on disk for the --write mode.
/// </summary>
public static class CatalogWriter
{
    public const string Header =
        """
        // <auto-generated>
        // Generated by Ficsit.Schematics.CatalogGenerator from Docs/en-US.json — do not edit.
        // Regenerate with: dotnet run --project Ficsit.Schematics.CatalogGenerator -- --write
        // </auto-generated>

        """;

    /// <summary>All generated files, keyed by repo-relative path (forward slashes).</summary>
    public static IReadOnlyDictionary<string, string> Render(CatalogModel model)
    {
        var files = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Ficsit.Schematics.Core/GameData/Catalog/PartsCatalog.cs"] = RenderParts(model),
            ["Ficsit.Schematics.Core/GameData/Catalog/Machines/MachineStats.g.cs"] = RenderMachineStats(model),
            ["Ficsit.Schematics.Core/Serialization/NameAliases.g.cs"] = RenderNameAliases(),
        };

        var sortIndex = GlobalRecipeOrder(model);
        foreach (var (machine, rows) in model.RecipesByModule.OrderBy(kv => kv.Key, StringComparer.Ordinal))
        {
            var module = ModuleName(machine);
            files[$"Ficsit.Schematics.Core/GameData/Catalog/Recipes/{module}Recipes.cs"]
                = RenderRecipeModule(machine, module, rows, sortIndex);
        }
        return files;
    }

    public static void Write(IReadOnlyDictionary<string, string> files, string repoRoot)
    {
        foreach (var (relative, content) in files)
        {
            var path = Path.Combine(repoRoot, relative.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, content, new UTF8Encoding(false));
        }
    }

    /// <summary>"Coal-Powered Generator" → "CoalPoweredGenerator" (module/file name).</summary>
    public static string ModuleName(string machine)
        => new(machine.Where(char.IsLetterOrDigit).ToArray());

    /// <summary>
    /// Canonical global order: progression tier, then standard before alternate, then name.
    /// The sort keys stored on the rows restore this order across all modules.
    /// </summary>
    private static Dictionary<RecipeRow, int> GlobalRecipeOrder(CatalogModel model)
    {
        var ordered = model.RecipesByModule.Values.SelectMany(r => r)
            .OrderBy(r => r.Tier)
            .ThenBy(r => r.Alternate)
            .ThenBy(r => r.Name, StringComparer.Ordinal)
            .ThenBy(r => r.Machine, StringComparer.Ordinal)
            .ToList();
        var index = new Dictionary<RecipeRow, int>(ReferenceEqualityComparer.Instance);
        for (var i = 0; i < ordered.Count; i++) index[ordered[i]] = i;
        return index;
    }

    // ------------------------------------------------------------------ parts

    private static string RenderParts(CatalogModel model)
    {
        var sb = new StringBuilder();
        sb.Append(Header);
        sb.Append(
            """
            namespace Ficsit.Schematics.Core.GameData.Catalog;

            /// <summary>Every part in the game, in canonical order.</summary>
            public sealed class PartsCatalog : PartModule
            {
                protected override IReadOnlyList<Part> Parts =>
                [

            """);

        for (var i = 0; i < model.Parts.Count; i++)
        {
            var part = model.Parts[i];
            sb.Append($"        new({i}, \"{part.Name}\", \"{part.Tier}\"");
            if (part.SinkPoints > 0) sb.Append($", SinkPoints: {part.SinkPoints}");
            if (part.Fluid) sb.Append(", Fluid: true");
            if (part.ManuallyGathered) sb.Append(", ManuallyGathered: true");
            sb.Append("),\n");
        }

        sb.Append("    ];\n}\n");
        return sb.ToString();
    }

    // ------------------------------------------------------------------ name aliases

    private static string RenderNameAliases()
    {
        var sb = new StringBuilder();
        sb.Append(Header);
        sb.Append(
            """
            namespace Ficsit.Schematics.Core.Serialization;

            /// <summary>
            /// Legacy part/recipe/machine names → the game's current official names. Documents
            /// written before a rename keep loading: the .sfmd reader resolves every stored
            /// name through this table.
            /// </summary>
            public static class NameAliases
            {
                /// <summary>The official name for a possibly-legacy one (unknown names pass through).</summary>
                public static string Resolve(string name)
                    => ByLegacyName.TryGetValue(name, out var official) ? official : name;

                public static readonly IReadOnlyDictionary<string, string> ByLegacyName = new Dictionary<string, string>(StringComparer.Ordinal)
                {

            """);

        foreach (var (legacy, official) in Overrides.LegacyNames.OrderBy(kv => kv.Key, StringComparer.Ordinal))
            sb.Append($"        [\"{legacy}\"] = \"{official}\",\n");

        sb.Append("    };\n}\n");
        return sb.ToString();
    }

    // ------------------------------------------------------------------ machine stats

    private static string RenderMachineStats(CatalogModel model)
    {
        var sb = new StringBuilder();
        sb.Append(Header);
        sb.Append(
            """
            using Ficsit.Schematics.Core.Numerics;

            namespace Ficsit.Schematics.Core.GameData.Catalog.Machines;

            /// <summary>
            /// Export-derived stats for every machine, keyed by machine name. The hand-authored
            /// machine groups (families, marks, capacities) pull their numbers from here.
            /// </summary>
            internal static class MachineStats
            {
                public static MachineStat For(string machine) => ByName[machine];

                public static readonly IReadOnlyDictionary<string, MachineStat> ByName = new Dictionary<string, MachineStat>(StringComparer.Ordinal)
                {

            """);

        foreach (var stat in model.MachineStats)
        {
            sb.Append($"        [\"{stat.Name}\"] = new(\"{stat.Tier}\"");
            if (stat.Power is { } power) sb.Append($", Power: {Literal(power)}");
            if (stat.MinPower is { } min) sb.Append($", MinPower: {Literal(min)}");
            if (stat.BasePower is { } basePower) sb.Append($", BasePower: {Literal(basePower)}");
            if (stat.BasePowerBoost is { } baseBoost) sb.Append($", BasePowerBoost: {Literal(baseBoost)}");
            if (stat.FueledBasePowerBoost is { } fueledBoost) sb.Append($", FueledBasePowerBoost: {Literal(fueledBoost)}");
            if (stat.OverclockExp is { } exp) sb.Append($", OverclockExp: {Literal(exp)}");
            if (stat.Sloops > 0) sb.Append($", Sloops: {stat.Sloops}");
            if (stat.SloopMultiplier is { } sloopMultiplier) sb.Append($", SloopMultiplier: {Literal(sloopMultiplier)}");
            if (stat.SloopPowerExp is { } sloopExp) sb.Append($", SloopPowerExp: {Literal(sloopExp)}");
            if (stat.Cost is { Count: > 0 } cost)
                sb.Append($", Cost: [{string.Join(", ", cost.Select(c => $"C(\"{c.Part}\", {c.Amount})"))}]");
            if (stat.Throughput is { } throughput) sb.Append($", Throughput: {Literal(throughput)}");
            sb.Append("),\n");
        }

        sb.Append(
            """
                };

                private static Rational R(string text) => Rational.Parse(text);

                private static CostEntry C(string part, int amount) => new() { Part = part, Amount = amount };
            }

            """);
        return sb.ToString();
    }

    // ------------------------------------------------------------------ recipes

    private static string RenderRecipeModule(
        string machine, string module, IReadOnlyList<RecipeRow> rows, Dictionary<RecipeRow, int> sortIndex)
    {
        var sorted = rows.OrderBy(r => sortIndex[r]).ToList();
        var sortWidth = sorted.Max(r => sortIndex[r].ToString().Length);
        var nameWidth = sorted.Max(r => r.Name.Length);
        var batchWidth = sorted.Max(r => BatchText(r).Length);

        var sb = new StringBuilder();
        sb.Append(Header);
        sb.Append(
            $$"""
            namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

            /// <summary>Recipes that run on the {{machine}}.</summary>
            public sealed class {{module}}Recipes : RecipeModule
            {
                protected override string Machine => "{{machine}}";

                protected override IReadOnlyList<Recipe> Recipes =>
                [

            """);

        foreach (var row in sorted)
        {
            sb.Append($"        new({sortIndex[row].ToString().PadLeft(sortWidth)}, ");
            sb.Append($"\"{row.Name}\",".PadRight(nameWidth + 4));
            sb.Append(BatchText(row).PadRight(batchWidth + 1));
            sb.Append($"Tier: \"{row.Tier}\", ");
            sb.Append(PartsText(row));
            if (row.Alternate) sb.Append(", Alternate: true");
            if (row.Ficsmas) sb.Append(", Ficsmas: true");
            if (row.AveragePower is { } avg) sb.Append($", AveragePower: {Literal(avg)}");
            if (row.MinPower is { } min) sb.Append($", MinPower: {Literal(min)}");
            if (row.IgnoreInputMultiplier) sb.Append(", IgnoreInputMultiplier: true");
            if (row.SpaceElevatorMultiplier is { } elevator) sb.Append($", SpaceElevatorMultiplier: \"{elevator}\"");
            sb.Append("),\n");
        }

        sb.Append("    ];\n}\n");
        return sb.ToString();
    }

    private static string BatchText(RecipeRow row) => $"Batch: {Literal(row.Batch)},";

    private static string PartsText(RecipeRow row)
    {
        var parts = row.Parts.Select(p => p.Amount.IsNegative
            ? $"In(\"{p.Part}\", {Literal(-p.Amount)})"
            : $"Out(\"{p.Part}\", {Literal(p.Amount)})");
        return $"[{string.Join(", ", parts)}]";
    }

    /// <summary>An exact literal in catalog style: int for whole numbers, R("a/b") for fractions.</summary>
    public static string Literal(Rational value)
        => value.IsInteger
            ? value.Numerator.ToString()
            : $"R(\"{value.Numerator}/{value.Denominator}\")";
}
