// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Packager;

public sealed class PackagedSulfuricAcid : RecipeBase
{
    public override int SortIndex => 233;
    public override string RecipeName => "Packaged Sulfuric Acid";
    public override string Machine => "Packager";
    public override string BatchTime => "3";
    public override string Tier => "7-5";
    public override bool IgnoreInputMultiplier => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Sulfuric Acid", Amount = "-2" },
        new() { Part = "Empty Canister", Amount = "-2" },
        new() { Part = "Packaged Sulfuric Acid", Amount = "2" },
    ];
}
