// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Packager;

public sealed class PackagedNitrogenGas : RecipeBase
{
    public override int SortIndex => 255;
    public override string RecipeName => "Packaged Nitrogen Gas";
    public override string Machine => "Packager";
    public override string BatchTime => "1";
    public override string Tier => "8-3";
    public override bool IgnoreInputMultiplier => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Nitrogen Gas", Amount = "-4" },
        new() { Part = "Empty Fluid Tank", Amount = "-1" },
        new() { Part = "Packaged Nitrogen Gas", Amount = "1" },
    ];
}
