// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Packager;

public sealed class PackagedTurbofuel : RecipeBase
{
    public override int SortIndex => 170;
    public override string RecipeName => "Packaged Turbofuel";
    public override string Machine => "Packager";
    public override string BatchTime => "6";
    public override string Tier => "5-4";
    public override bool IgnoreInputMultiplier => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Turbofuel", Amount = "-2" },
        new() { Part = "Empty Canister", Amount = "-2" },
        new() { Part = "Packaged Turbofuel", Amount = "2" },
    ];
}
