// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Packager;

public sealed class UnpackageNitricAcid : RecipeBase
{
    public override int SortIndex => 281;
    public override string RecipeName => "Unpackage Nitric Acid";
    public override string Machine => "Packager";
    public override string BatchTime => "3";
    public override string Tier => "8-5";
    public override bool IgnoreInputMultiplier => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Packaged Nitric Acid", Amount = "-1" },
        new() { Part = "Nitric Acid", Amount = "1" },
        new() { Part = "Empty Fluid Tank", Amount = "1" },
    ];
}
