// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Manufacturer;

public sealed class AdaptiveControlUnit : RecipeBase
{
    public override int SortIndex => 213;
    public override string RecipeName => "Adaptive Control Unit";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "60";
    public override string Tier => "6-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Automated Wiring", Amount = "-5" },
        new() { Part = "Circuit Board", Amount = "-5" },
        new() { Part = "Heavy Modular Frame", Amount = "-1" },
        new() { Part = "Computer", Amount = "-2" },
        new() { Part = "Adaptive Control Unit", Amount = "1" },
    ];
}
