// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Manufacturer;

public sealed class BallisticWarpDrive : RecipeBase
{
    public override int SortIndex => 311;
    public override string RecipeName => "Ballistic Warp Drive";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "60";
    public override string Tier => "9-4";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Thermal Propulsion Rocket", Amount = "-1" },
        new() { Part = "Singularity Cell", Amount = "-5" },
        new() { Part = "Superposition Oscillator", Amount = "-2" },
        new() { Part = "Dark Matter Crystal", Amount = "-40" },
        new() { Part = "Ballistic Warp Drive", Amount = "1" },
    ];
}
