// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Manufacturer;

public sealed class CateriumComputer : RecipeBase
{
    public override int SortIndex => 207;
    public override string RecipeName => "Caterium Computer";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "16";
    public override string Tier => "6-1";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Circuit Board", Amount = "-4" },
        new() { Part = "Quickwire", Amount = "-14" },
        new() { Part = "Rubber", Amount = "-6" },
        new() { Part = "Computer", Amount = "1" },
    ];
}
