// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Manufacturer;

public sealed class ClassicBattery : RecipeBase
{
    public override int SortIndex => 235;
    public override string RecipeName => "Classic Battery";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "8";
    public override string Tier => "7-5";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Sulfur", Amount = "-6" },
        new() { Part = "Alclad Aluminum Sheet", Amount = "-7" },
        new() { Part = "Plastic", Amount = "-8" },
        new() { Part = "Wire", Amount = "-12" },
        new() { Part = "Battery", Amount = "4" },
    ];
}
