// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Manufacturer;

public sealed class CrystalOscillator : RecipeBase
{
    public override int SortIndex => 202;
    public override string RecipeName => "Crystal Oscillator";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "120";
    public override string Tier => "6-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Quartz Crystal", Amount = "-36" },
        new() { Part = "Cable", Amount = "-28" },
        new() { Part = "Reinforced Iron Plate", Amount = "-5" },
        new() { Part = "Crystal Oscillator", Amount = "2" },
    ];
}
