// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Manufacturer;

public sealed class ExplosiveRebar : RecipeBase
{
    public override int SortIndex => 198;
    public override string RecipeName => "Explosive Rebar";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "12";
    public override string Tier => "6-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Iron Rebar", Amount = "-2" },
        new() { Part = "Smokeless Powder", Amount = "-2" },
        new() { Part = "Steel Pipe", Amount = "-2" },
        new() { Part = "Explosive Rebar", Amount = "1" },
    ];
}
