// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Manufacturer;

public sealed class FlexibleFramework : RecipeBase
{
    public override int SortIndex => 121;
    public override string RecipeName => "Flexible Framework";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "16";
    public override string Tier => "6-1";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Modular Frame", Amount = "-1" },
        new() { Part = "Steel Beam", Amount = "-6" },
        new() { Part = "Rubber", Amount = "-8" },
        new() { Part = "Versatile Framework", Amount = "2" },
    ];
}
