// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Manufacturer;

public sealed class HeavyEncasedFrame : RecipeBase
{
    public override int SortIndex => 211;
    public override string RecipeName => "Heavy Encased Frame";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "64";
    public override string Tier => "6-1";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Modular Frame", Amount = "-8" },
        new() { Part = "Encased Industrial Beam", Amount = "-10" },
        new() { Part = "Steel Pipe", Amount = "-36" },
        new() { Part = "Concrete", Amount = "-22" },
        new() { Part = "Heavy Modular Frame", Amount = "3" },
    ];
}
