// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Manufacturer;

public sealed class HeavyFlexibleFrame : RecipeBase
{
    public override int SortIndex => 212;
    public override string RecipeName => "Heavy Flexible Frame";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "16";
    public override string Tier => "6-1";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Modular Frame", Amount = "-5" },
        new() { Part = "Encased Industrial Beam", Amount = "-3" },
        new() { Part = "Rubber", Amount = "-20" },
        new() { Part = "Screw", Amount = "-104" },
        new() { Part = "Heavy Modular Frame", Amount = "1" },
    ];
}
