// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Manufacturer;

public sealed class NukeNobelisk : RecipeBase
{
    public override int SortIndex => 251;
    public override string RecipeName => "Nuke Nobelisk";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "120";
    public override string Tier => "8-2";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Nobelisk", Amount = "-5" },
        new() { Part = "Encased Uranium Cell", Amount = "-20" },
        new() { Part = "Smokeless Powder", Amount = "-10" },
        new() { Part = "AI Limiter", Amount = "-6" },
        new() { Part = "Nuke Nobelisk", Amount = "1" },
    ];
}
