// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Manufacturer;

public sealed class PackagedTurboRifleAmmo : RecipeBase
{
    public override int SortIndex => 221;
    public override string RecipeName => "Packaged Turbo Rifle Ammo";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "12";
    public override string Tier => "7-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Rifle Ammo", Amount = "-25" },
        new() { Part = "Aluminum Casing", Amount = "-3" },
        new() { Part = "Packaged Turbofuel", Amount = "-3" },
        new() { Part = "Turbo Rifle Ammo", Amount = "50" },
    ];
}
