// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Manufacturer;

public sealed class PlutoniumFuelRod : RecipeBase
{
    public override int SortIndex => 272;
    public override string RecipeName => "Plutonium Fuel Rod";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "240";
    public override string Tier => "8-5";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Encased Plutonium Cell", Amount = "-30" },
        new() { Part = "Steel Beam", Amount = "-18" },
        new() { Part = "Electromagnetic Control Rod", Amount = "-6" },
        new() { Part = "Heat Sink", Amount = "-10" },
        new() { Part = "Plutonium Fuel Rod", Amount = "1" },
    ];
}
