// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Manufacturer;

public sealed class RadioControlUnit : RecipeBase
{
    public override int SortIndex => 236;
    public override string RecipeName => "Radio Control Unit";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "48";
    public override string Tier => "7-5";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Aluminum Casing", Amount = "-32" },
        new() { Part = "Crystal Oscillator", Amount = "-1" },
        new() { Part = "Computer", Amount = "-2" },
        new() { Part = "Radio Control Unit", Amount = "2" },
    ];
}
