// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Manufacturer;

public sealed class RadioConnectionUnit : RecipeBase
{
    public override int SortIndex => 238;
    public override string RecipeName => "Radio Connection Unit";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "16";
    public override string Tier => "8-3";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Heat Sink", Amount = "-4" },
        new() { Part = "High-Speed Connector", Amount = "-2" },
        new() { Part = "Quartz Crystal", Amount = "-12" },
        new() { Part = "Radio Control Unit", Amount = "1" },
    ];
}
