// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Manufacturer;

public sealed class RadioControlSystem : RecipeBase
{
    public override int SortIndex => 237;
    public override string RecipeName => "Radio Control System";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "40";
    public override string Tier => "7-5";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Crystal Oscillator", Amount = "-1" },
        new() { Part = "Circuit Board", Amount = "-10" },
        new() { Part = "Aluminum Casing", Amount = "-60" },
        new() { Part = "Rubber", Amount = "-30" },
        new() { Part = "Radio Control Unit", Amount = "3" },
    ];
}
