// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Manufacturer;

public sealed class SAMFluctuator : RecipeBase
{
    public override int SortIndex => 298;
    public override string RecipeName => "SAM Fluctuator";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "6";
    public override string Tier => "9-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Reanimated SAM", Amount = "-6" },
        new() { Part = "Wire", Amount = "-5" },
        new() { Part = "Steel Pipe", Amount = "-3" },
        new() { Part = "SAM Fluctuator", Amount = "1" },
    ];
}
