// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Manufacturer;

public sealed class SuperStateComputer : RecipeBase
{
    public override int SortIndex => 240;
    public override string RecipeName => "Super-State Computer";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "25";
    public override string Tier => "8-2";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Computer", Amount = "-3" },
        new() { Part = "Electromagnetic Control Rod", Amount = "-1" },
        new() { Part = "Battery", Amount = "-10" },
        new() { Part = "Wire", Amount = "-25" },
        new() { Part = "Supercomputer", Amount = "1" },
    ];
}
