// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Manufacturer;

public sealed class Supercomputer : RecipeBase
{
    public override int SortIndex => 239;
    public override string RecipeName => "Supercomputer";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "32";
    public override string Tier => "7-5";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Computer", Amount = "-4" },
        new() { Part = "AI Limiter", Amount = "-2" },
        new() { Part = "High-Speed Connector", Amount = "-3" },
        new() { Part = "Plastic", Amount = "-28" },
        new() { Part = "Supercomputer", Amount = "1" },
    ];
}
