// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Manufacturer;

public sealed class UraniumFuelRod : RecipeBase
{
    public override int SortIndex => 252;
    public override string RecipeName => "Uranium Fuel Rod";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "150";
    public override string Tier => "8-2";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Encased Uranium Cell", Amount = "-50" },
        new() { Part = "Encased Industrial Beam", Amount = "-3" },
        new() { Part = "Electromagnetic Control Rod", Amount = "-5" },
        new() { Part = "Uranium Fuel Rod", Amount = "1" },
    ];
}
