// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class AIExpansionServer : RecipeBase
{
    public override int SortIndex => 304;
    public override string RecipeName => "AI Expansion Server";
    public override string Machine => "Quantum Encoder";
    public override string BatchTime => "15";
    public override string Tier => "9-2";
    public override string? AveragePower => "-1000";
    public override string? MinPower => "-2000";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Magnetic Field Generator", Amount = "-1" },
        new() { Part = "Neural-Quantum Processor", Amount = "-1" },
        new() { Part = "Superposition Oscillator", Amount = "-1" },
        new() { Part = "Excited Photonic Matter", Amount = "-25" },
        new() { Part = "AI Expansion Server", Amount = "1" },
        new() { Part = "Dark Matter Residue", Amount = "25" },
    ];
}
