// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class AILimiter : RecipeBase
{
    public override int SortIndex => 196;
    public override string RecipeName => "AI Limiter";
    public override string Machine => "Assembler";
    public override string BatchTime => "12";
    public override string Tier => "5-5";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Copper Sheet", Amount = "-5" },
        new() { Part = "Quickwire", Amount = "-20" },
        new() { Part = "AI Limiter", Amount = "1" },
    ];
}
