// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class AlcladCasing : RecipeBase
{
    public override int SortIndex => 228;
    public override string RecipeName => "Alclad Casing";
    public override string Machine => "Assembler";
    public override string BatchTime => "8";
    public override string Tier => "7-1";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Aluminum Ingot", Amount = "-20" },
        new() { Part = "Copper Ingot", Amount = "-10" },
        new() { Part = "Aluminum Casing", Amount = "15" },
    ];
}
