// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class AlcladAluminumSheet : RecipeBase
{
    public override int SortIndex => 226;
    public override string RecipeName => "Alclad Aluminum Sheet";
    public override string Machine => "Assembler";
    public override string BatchTime => "6";
    public override string Tier => "7-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Aluminum Ingot", Amount = "-3" },
        new() { Part = "Copper Ingot", Amount = "-1" },
        new() { Part = "Alclad Aluminum Sheet", Amount = "3" },
    ];
}
