// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class AlienDNACapsule : RecipeBase
{
    public override int SortIndex => 60;
    public override string RecipeName => "Alien DNA Capsule";
    public override string Machine => "Constructor";
    public override string BatchTime => "6";
    public override string Tier => "0-3";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Alien Protein", Amount = "-1" },
        new() { Part = "Alien DNA Capsule", Amount = "1" },
    ];
}
