// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class AlienPowerAugmenter : RecipeBase
{
    public override int SortIndex => 300;
    public override string RecipeName => "Alien Power Augmenter";
    public override string Machine => "Alien Power Augmenter";
    public override string BatchTime => "12";
    public override string Tier => "9-2";
    public override bool IgnoreInputMultiplier => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Alien Power Matrix", Amount = "-1" },
    ];
}
