// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class AluminumIngot : RecipeBase
{
    public override int SortIndex => 223;
    public override string RecipeName => "Aluminum Ingot";
    public override string Machine => "Foundry";
    public override string BatchTime => "4";
    public override string Tier => "7-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Aluminum Scrap", Amount = "-6" },
        new() { Part = "Silica", Amount = "-5" },
        new() { Part = "Aluminum Ingot", Amount = "4" },
    ];
}
