// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class AluminumScrap : RecipeBase
{
    public override int SortIndex => 218;
    public override string RecipeName => "Aluminum Scrap";
    public override string Machine => "Refinery";
    public override string BatchTime => "1";
    public override string Tier => "7-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Alumina Solution", Amount = "-4" },
        new() { Part = "Coal", Amount = "-2" },
        new() { Part = "Aluminum Scrap", Amount = "6" },
        new() { Part = "Water", Amount = "2" },
    ];
}
