namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

/// <summary>Recipes that run on the Assembler.</summary>
public sealed class AssemblerRecipes : RecipeModule
{
    protected override string Machine => "Assembler";

    protected override IReadOnlyList<Recipe> Recipes =>
    [
        new(27, "Coated Iron Plate", "8", "5-2", [In("Iron Ingot", 5), In("Plastic", 1), Out("Iron Plate", 10)], Alternate: true),
        new(38, "Fused Wire", "20", "5-5", [In("Copper Ingot", 4), In("Caterium Ingot", 1), Out("Wire", 30)], Alternate: true),
        new(41, "Insulated Cable", "12", "5-2", [In("Wire", 9), In("Rubber", 6), Out("Cable", 20)], Alternate: true),
        new(42, "Quickwire Cable", "24", "5-5", [In("Quickwire", 3), In("Rubber", 2), Out("Cable", 11)], Alternate: true),
        new(53, "Fine Concrete", "12", "2-1", [In("Silica", 3), In("Limestone", 12), Out("Concrete", 10)], Alternate: true),
        new(54, "Rubber Concrete", "6", "5-2", [In("Limestone", 10), In("Rubber", 2), Out("Concrete", 9)], Alternate: true),
        new(56, "Reinforced Iron Plate", "12", "0-3", [In("Iron Plate", 6), In("Screw", 12), Out("Reinforced Iron Plate", 1)]),
        new(57, "Bolted Iron Plate", "12", "2-1", [In("Iron Plate", 18), In("Screw", 50), Out("Reinforced Iron Plate", 3)], Alternate: true),
        new(58, "Stitched Iron Plate", "32", "2-1", [In("Iron Plate", 10), In("Wire", 20), Out("Reinforced Iron Plate", 3)], Alternate: true),
        new(59, "Adhered Iron Plate", "16", "5-2", [In("Iron Plate", 3), In("Rubber", 1), Out("Reinforced Iron Plate", 1)], Alternate: true),
        new(79, "Cheap Silica", "8", "2-1", [In("Raw Quartz", 3), In("Limestone", 5), Out("Silica", 7)], Alternate: true),
        new(85, "Fabric", "4", "2-1", [In("Mycelia", 1), In("Biomass", 5), Out("Fabric", 1)]),
        new(87, "Rotor", "15", "2-1", [In("Iron Rod", 5), In("Screw", 25), Out("Rotor", 1)]),
        new(88, "Copper Rotor", "16", "2-1", [In("Copper Sheet", 6), In("Screw", 52), Out("Rotor", 3)], Alternate: true),
        new(89, "Steel Rotor", "12", "3-3", [In("Steel Pipe", 2), In("Wire", 6), Out("Rotor", 1)], Alternate: true),
        new(90, "Shatter Rebar", "12", "2-1", [In("Iron Rebar", 2), In("Quartz Crystal", 3), Out("Shatter Rebar", 1)]),
        new(91, "Modular Frame", "60", "2-1", [In("Reinforced Iron Plate", 3), In("Iron Rod", 12), Out("Modular Frame", 2)]),
        new(92, "Bolted Frame", "24", "2-1", [In("Reinforced Iron Plate", 3), In("Screw", 56), Out("Modular Frame", 2)], Alternate: true),
        new(93, "Steeled Frame", "60", "3-3", [In("Reinforced Iron Plate", 2), In("Steel Pipe", 10), Out("Modular Frame", 3)], Alternate: true),
        new(94, "Smart Plating", "30", "2-1", [In("Reinforced Iron Plate", 1), In("Rotor", 1), Out("Smart Plating", 1)]),
        new(103, "Black Powder", "4", "3-1", [In("Coal", 1), In("Sulfur", 1), Out("Black Powder", 2)]),
        new(104, "Fine Black Powder", "8", "5-4", [In("Sulfur", 1), In("Compacted Coal", 2), Out("Black Powder", 6)], Alternate: true),
        new(114, "Automated Miner", "60", "3-3", [In("Steel Pipe", 4), In("Iron Plate", 4), Out("Portable Miner", 1)], Alternate: true),
        new(118, "Nobelisk", "6", "3-3", [In("Black Powder", 2), In("Steel Pipe", 2), Out("Nobelisk", 1)]),
        new(119, "Gas Nobelisk", "12", "3-3", [In("Nobelisk", 1), In("Biomass", 10), Out("Gas Nobelisk", 1)]),
        new(120, "Versatile Framework", "24", "3-3", [In("Modular Frame", 1), In("Steel Beam", 12), Out("Versatile Framework", 2)]),
        new(122, "Stator", "12", "4-3", [In("Steel Pipe", 3), In("Wire", 8), Out("Stator", 1)]),
        new(123, "Quickwire Stator", "15", "5-5", [In("Steel Pipe", 4), In("Quickwire", 15), Out("Stator", 2)], Alternate: true),
        new(124, "Encased Industrial Beam", "10", "4-3", [In("Steel Beam", 3), In("Concrete", 6), Out("Encased Industrial Beam", 1)]),
        new(125, "Encased Industrial Pipe", "15", "4-3", [In("Steel Pipe", 6), In("Concrete", 5), Out("Encased Industrial Beam", 1)], Alternate: true),
        new(126, "Automated Wiring", "24", "4-3", [In("Stator", 1), In("Cable", 20), Out("Automated Wiring", 1)]),
        new(129, "Motor", "12", "4-3", [In("Rotor", 2), In("Stator", 2), Out("Motor", 1)]),
        new(131, "Electric Motor", "16", "8-2", [In("Electromagnetic Control Rod", 1), In("Rotor", 2), Out("Motor", 2)], Alternate: true),
        new(134, "Rifle Ammo", "12", "5-2", [In("Copper Sheet", 3), In("Smokeless Powder", 2), Out("Rifle Ammo", 15)]),
        new(140, "Circuit Board", "8", "5-2", [In("Copper Sheet", 2), In("Plastic", 4), Out("Circuit Board", 1)]),
        new(141, "Electrode Circuit Board", "12", "5-2", [In("Rubber", 4), In("Petroleum Coke", 8), Out("Circuit Board", 1)], Alternate: true),
        new(142, "Silicon Circuit Board", "24", "5-2", [In("Copper Sheet", 11), In("Silica", 11), Out("Circuit Board", 5)], Alternate: true),
        new(143, "Caterium Circuit Board", "48", "5-5", [In("Plastic", 10), In("Quickwire", 30), Out("Circuit Board", 7)], Alternate: true),
        new(144, "Cluster Nobelisk", "24", "5-2", [In("Nobelisk", 3), In("Smokeless Powder", 4), Out("Cluster Nobelisk", 1)]),
        new(154, "Compacted Coal", "12", "5-4", [In("Coal", 5), In("Sulfur", 5), Out("Compacted Coal", 5)], Alternate: true),
        new(160, "Coated Iron Canister", "4", "5-4", [In("Iron Plate", 2), In("Copper Sheet", 1), Out("Empty Canister", 4)], Alternate: true),
        new(190, "Fused Quickwire", "8", "5-5", [In("Caterium Ingot", 1), In("Copper Ingot", 5), Out("Quickwire", 12)], Alternate: true),
        new(195, "Stun Rebar", "6", "5-5", [In("Iron Rebar", 1), In("Quickwire", 5), Out("Stun Rebar", 1)]),
        new(196, "AI Limiter", "12", "5-5", [In("Copper Sheet", 5), In("Quickwire", 20), Out("AI Limiter", 1)]),
        new(197, "Plastic AI Limiter", "15", "5-5", [In("Quickwire", 30), In("Plastic", 7), Out("AI Limiter", 2)], Alternate: true),
        new(200, "Homing Rifle Ammo", "24", "6-1", [In("Rifle Ammo", 20), In("High-Speed Connector", 1), Out("Homing Rifle Ammo", 10)]),
        new(201, "Pulse Nobelisk", "60", "6-1", [In("Nobelisk", 5), In("Crystal Oscillator", 1), Out("Pulse Nobelisk", 5)]),
        new(208, "Crystal Computer", "36", "6-1", [In("Circuit Board", 3), In("Crystal Oscillator", 1), Out("Computer", 2)], Alternate: true),
        new(226, "Alclad Aluminum Sheet", "6", "7-1", [In("Aluminum Ingot", 3), In("Copper Ingot", 1), Out("Alclad Aluminum Sheet", 3)]),
        new(228, "Alclad Casing", "8", "7-1", [In("Aluminum Ingot", 20), In("Copper Ingot", 10), Out("Aluminum Casing", 15)], Alternate: true),
        new(241, "OC Supercomputer", "20", "8-3", [In("Radio Control Unit", 2), In("Cooling System", 2), Out("Supercomputer", 1)], Alternate: true),
        new(242, "Assembly Director System", "80", "7-5", [In("Adaptive Control Unit", 2), In("Supercomputer", 1), Out("Assembly Director System", 1)]),
        new(248, "Electromagnetic Control Rod", "30", "8-2", [In("Stator", 3), In("AI Limiter", 2), Out("Electromagnetic Control Rod", 2)]),
        new(249, "Electromagnetic Connection Rod", "15", "8-2", [In("Stator", 2), In("High-Speed Connector", 1), Out("Electromagnetic Control Rod", 2)], Alternate: true),
        new(250, "Magnetic Field Generator", "120", "8-2", [In("Versatile Framework", 5), In("Electromagnetic Control Rod", 2), Out("Magnetic Field Generator", 2)]),
        new(256, "Heat Sink", "8", "8-3", [In("Alclad Aluminum Sheet", 5), In("Copper Sheet", 3), Out("Heat Sink", 1)]),
        new(257, "Heat Exchanger", "6", "8-3", [In("Aluminum Casing", 3), In("Rubber", 3), Out("Heat Sink", 1)], Alternate: true),
        new(273, "Plutonium Fuel Unit", "120", "8-5", [In("Encased Plutonium Cell", 20), In("Pressure Conversion Cube", 1), Out("Plutonium Fuel Rod", 1)], Alternate: true),
        new(274, "Pressure Conversion Cube", "60", "8-5", [In("Fused Modular Frame", 1), In("Radio Control Unit", 2), Out("Pressure Conversion Cube", 1)]),
        new(278, "Encased Plutonium Cell", "12", "8-5", [In("Plutonium Pellet", 2), In("Concrete", 4), Out("Encased Plutonium Cell", 1)]),
        new(324, "Sparkly Fireworks", "24", "2-1", [In("FICSMAS Tree Branch", 3), In("FICSMAS Actual Snow", 2), Out("Sparkly Fireworks", 1)], Ficsmas: true),
        new(325, "Fancy Fireworks", "24", "2-1", [In("FICSMAS Tree Branch", 4), In("FICSMAS Bow", 3), Out("Fancy Fireworks", 1)], Ficsmas: true),
        new(326, "Sweet Fireworks", "24", "2-1", [In("FICSMAS Tree Branch", 6), In("Candy Cane", 3), Out("Sweet Fireworks", 1)], Ficsmas: true),
        new(329, "FICSMAS Ornament Bundle", "12", "3-3", [In("Copper FICSMAS Ornament", 1), In("Iron FICSMAS Ornament", 1), Out("FICSMAS Ornament Bundle", 1)], Ficsmas: true),
        new(330, "FICSMAS Wreath", "60", "3-3", [In("FICSMAS Tree Branch", 15), In("FICSMAS Ornament Bundle", 6), Out("FICSMAS Wreath", 2)], Ficsmas: true),
        new(331, "FICSMAS Wonder Star", "60", "3-3", [In("FICSMAS Wreath", 5), In("Candy Cane", 20), Out("FICSMAS Wonder Star", 1)], Ficsmas: true),
    ];
}
