// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class AssemblyDirectorSystem : RecipeBase
{
    public override int SortIndex => 242;
    public override string RecipeName => "Assembly Director System";
    public override string Machine => "Assembler";
    public override string BatchTime => "80";
    public override string Tier => "7-5";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Adaptive Control Unit", Amount = "-2" },
        new() { Part = "Supercomputer", Amount = "-1" },
        new() { Part = "Assembly Director System", Amount = "1" },
    ];
}
