// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class AutomatedSpeedWiring : RecipeBase
{
    public override int SortIndex => 128;
    public override string RecipeName => "Automated Speed Wiring";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "32";
    public override string Tier => "6-1";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Stator", Amount = "-2" },
        new() { Part = "Wire", Amount = "-40" },
        new() { Part = "High-Speed Connector", Amount = "-1" },
        new() { Part = "Automated Wiring", Amount = "4" },
    ];
}
