// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class BasicIronIngot : RecipeBase
{
    public override int SortIndex => 17;
    public override string RecipeName => "Basic Iron Ingot";
    public override string Machine => "Foundry";
    public override string BatchTime => "12";
    public override string Tier => "3-3";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Iron Ore", Amount = "-5" },
        new() { Part = "Limestone", Amount = "-8" },
        new() { Part = "Iron Ingot", Amount = "10" },
    ];
}
