// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class Biocoal : RecipeBase
{
    public override int SortIndex => 101;
    public override string RecipeName => "Biocoal";
    public override string Machine => "Constructor";
    public override string BatchTime => "8";
    public override string Tier => "3-1";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Biomass", Amount = "-5" },
        new() { Part = "Coal", Amount = "6" },
    ];
}
