// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class BiomassWood : RecipeBase
{
    public override int SortIndex => 50;
    public override string RecipeName => "Biomass (Wood)";
    public override string Machine => "Constructor";
    public override string BatchTime => "4";
    public override string Tier => "0-6";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Wood", Amount = "-4" },
        new() { Part = "Biomass", Amount = "20" },
    ];
}
