// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class BiomassBurner : RecipeBase
{
    public override int SortIndex => 51;
    public override string RecipeName => "Biomass Burner";
    public override string Machine => "Biomass Burner";
    public override string BatchTime => "6";
    public override string Tier => "0-6";
    public override bool IgnoreInputMultiplier => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Biomass", Amount = "-1" },
    ];
}
