// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class BiomassMycelia : RecipeBase
{
    public override int SortIndex => 48;
    public override string RecipeName => "Biomass (Mycelia)";
    public override string Machine => "Constructor";
    public override string BatchTime => "4";
    public override string Tier => "0-3";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Mycelia", Amount = "-1" },
        new() { Part = "Biomass", Amount = "10" },
    ];
}
