// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class BlackPowder : RecipeBase
{
    public override int SortIndex => 103;
    public override string RecipeName => "Black Powder";
    public override string Machine => "Assembler";
    public override string BatchTime => "4";
    public override string Tier => "3-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Coal", Amount = "-1" },
        new() { Part = "Sulfur", Amount = "-1" },
        new() { Part = "Black Powder", Amount = "2" },
    ];
}
