// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class BoltedFrame : RecipeBase
{
    public override int SortIndex => 92;
    public override string RecipeName => "Bolted Frame";
    public override string Machine => "Assembler";
    public override string BatchTime => "24";
    public override string Tier => "2-1";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Reinforced Iron Plate", Amount = "-3" },
        new() { Part = "Screw", Amount = "-56" },
        new() { Part = "Modular Frame", Amount = "2" },
    ];
}
