// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class CandyCane : RecipeBase
{
    public override int SortIndex => 322;
    public override string RecipeName => "Candy Cane";
    public override string Machine => "Constructor";
    public override string BatchTime => "12";
    public override string Tier => "0-3";
    public override bool Ficsmas => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "FICSMAS Gift", Amount = "-3" },
        new() { Part = "Candy Cane", Amount = "1" },
    ];
}
