// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class CateriumCircuitBoard : RecipeBase
{
    public override int SortIndex => 143;
    public override string RecipeName => "Caterium Circuit Board";
    public override string Machine => "Assembler";
    public override string BatchTime => "48";
    public override string Tier => "5-5";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Plastic", Amount = "-10" },
        new() { Part = "Quickwire", Amount = "-30" },
        new() { Part = "Circuit Board", Amount = "7" },
    ];
}
