// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class CateriumWire : RecipeBase
{
    public override int SortIndex => 37;
    public override string RecipeName => "Caterium Wire";
    public override string Machine => "Constructor";
    public override string BatchTime => "4";
    public override string Tier => "5-5";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Caterium Ingot", Amount = "-1" },
        new() { Part = "Wire", Amount = "8" },
    ];
}
