// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class CateriumIngot : RecipeBase
{
    public override int SortIndex => 191;
    public override string RecipeName => "Caterium Ingot";
    public override string Machine => "Smelter";
    public override string BatchTime => "4";
    public override string Tier => "5-5";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Caterium Ore", Amount = "-3" },
        new() { Part = "Caterium Ingot", Amount = "1" },
    ];
}
