// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class CircuitBoard : RecipeBase
{
    public override int SortIndex => 140;
    public override string RecipeName => "Circuit Board";
    public override string Machine => "Assembler";
    public override string BatchTime => "8";
    public override string Tier => "5-2";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Copper Sheet", Amount = "-2" },
        new() { Part = "Plastic", Amount = "-4" },
        new() { Part = "Circuit Board", Amount = "1" },
    ];
}
