// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class ClusterNobelisk : RecipeBase
{
    public override int SortIndex => 144;
    public override string RecipeName => "Cluster Nobelisk";
    public override string Machine => "Assembler";
    public override string BatchTime => "24";
    public override string Tier => "5-2";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Nobelisk", Amount = "-3" },
        new() { Part = "Smokeless Powder", Amount = "-4" },
        new() { Part = "Cluster Nobelisk", Amount = "1" },
    ];
}
