// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class Coal : RecipeBase
{
    public override int SortIndex => 7;
    public override string RecipeName => "Coal";
    public override string Machine => "Miner";
    public override string BatchTime => "60";
    public override string Tier => "3-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Coal", Amount = "1" },
    ];
}
