// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class CoalGenerator : RecipeBase
{
    public override int SortIndex => 105;
    public override string RecipeName => "Coal Generator";
    public override string Machine => "Coal-Powered Generator";
    public override string BatchTime => "4";
    public override string Tier => "3-1";
    public override bool IgnoreInputMultiplier => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Coal", Amount = "-1" },
        new() { Part = "Water", Amount = "-3" },
    ];
}
