// <auto-generated>
// Generated by Ficsit.Schematics.CatalogGenerator from Docs/en-US.json — do not edit.
// Regenerate with: dotnet run --project Ficsit.Schematics.CatalogGenerator -- --write
// </auto-generated>
namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

/// <summary>Recipes that run on the Coal-Powered Generator.</summary>
public sealed class CoalPoweredGeneratorRecipes : RecipeModule
{
    protected override string Machine => "Coal-Powered Generator";

    protected override IReadOnlyList<Recipe> Recipes =>
    [
        new( 77, "Coal Generator",           Batch: 4,         Tier: "3-1", [In("Coal", 1), In("Water", 3)], IgnoreInputMultiplier: true),
        new( 78, "Compacted Coal Generator", Batch: R("42/5"), Tier: "3-1", [In("Compacted Coal", 1), In("Water", R("63/10"))], IgnoreInputMultiplier: true),
        new(121, "Petroleum Coke Generator", Batch: R("12/5"), Tier: "5-2", [In("Petroleum Coke", 1), In("Water", R("9/5"))], IgnoreInputMultiplier: true),
    ];
}
