// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class CoatedIronCanister : RecipeBase
{
    public override int SortIndex => 160;
    public override string RecipeName => "Coated Iron Canister";
    public override string Machine => "Assembler";
    public override string BatchTime => "4";
    public override string Tier => "5-4";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Iron Plate", Amount = "-2" },
        new() { Part = "Copper Sheet", Amount = "-1" },
        new() { Part = "Empty Canister", Amount = "4" },
    ];
}
