// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class CoatedIronPlate : RecipeBase
{
    public override int SortIndex => 27;
    public override string RecipeName => "Coated Iron Plate";
    public override string Machine => "Assembler";
    public override string BatchTime => "8";
    public override string Tier => "5-2";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Iron Ingot", Amount = "-5" },
        new() { Part = "Plastic", Amount = "-1" },
        new() { Part = "Iron Plate", Amount = "10" },
    ];
}
