// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class Computer : RecipeBase
{
    public override int SortIndex => 206;
    public override string RecipeName => "Computer";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "24";
    public override string Tier => "6-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Circuit Board", Amount = "-4" },
        new() { Part = "Cable", Amount = "-8" },
        new() { Part = "Plastic", Amount = "-16" },
        new() { Part = "Computer", Amount = "1" },
    ];
}
