// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class CompactedCoal : RecipeBase
{
    public override int SortIndex => 154;
    public override string RecipeName => "Compacted Coal";
    public override string Machine => "Assembler";
    public override string BatchTime => "12";
    public override string Tier => "5-4";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Coal", Amount = "-5" },
        new() { Part = "Sulfur", Amount = "-5" },
        new() { Part = "Compacted Coal", Amount = "5" },
    ];
}
