// <auto-generated>
// Generated by Ficsit.Schematics.CatalogGenerator from Docs/en-US.json — do not edit.
// Regenerate with: dotnet run --project Ficsit.Schematics.CatalogGenerator -- --write
// </auto-generated>
namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

/// <summary>Recipes that run on the Constructor.</summary>
public sealed class ConstructorRecipes : RecipeModule
{
    protected override string Machine => "Constructor";

    protected override IReadOnlyList<Recipe> Recipes =>
    [
        new(  1, "Iron Plate",              Batch: 6,  Tier: "0-0", [In("Iron Ingot", 3), Out("Iron Plate", 2)]),
        new(  2, "Iron Rod",                Batch: 4,  Tier: "0-0", [In("Iron Ingot", 1), Out("Iron Rod", 1)]),
        new(  3, "Cable",                   Batch: 2,  Tier: "0-2", [In("Wire", 2), Out("Cable", 1)]),
        new(  5, "Wire",                    Batch: 4,  Tier: "0-2", [In("Copper Ingot", 1), Out("Wire", 2)]),
        new(  6, "Alien DNA Capsule",       Batch: 6,  Tier: "0-3", [In("Alien Protein", 1), Out("Alien DNA Capsule", 1)]),
        new(  7, "Biomass (Alien Protein)", Batch: 4,  Tier: "0-3", [In("Alien Protein", 1), Out("Biomass", 100)]),
        new(  8, "Biomass (Mycelia)",       Batch: 4,  Tier: "0-3", [In("Mycelia", 1), Out("Biomass", 10)]),
        new( 10, "Candy Cane",              Batch: 12, Tier: "0-3", [In("FICSMAS Gift", 3), Out("Candy Cane", 1)], Ficsmas: true),
        new( 11, "Concrete",                Batch: 4,  Tier: "0-3", [In("Limestone", 3), Out("Concrete", 1)]),
        new( 12, "FICSMAS Actual Snow",     Batch: 12, Tier: "0-3", [In("FICSMAS Gift", 5), Out("FICSMAS Actual Snow", 2)], Ficsmas: true),
        new( 13, "FICSMAS Bow",             Batch: 12, Tier: "0-3", [In("FICSMAS Gift", 2), Out("FICSMAS Bow", 1)], Ficsmas: true),
        new( 15, "FICSMAS Tree Branch",     Batch: 6,  Tier: "0-3", [In("FICSMAS Gift", 1), Out("FICSMAS Tree Branch", 1)], Ficsmas: true),
        new( 16, "Hatcher Protein",         Batch: 3,  Tier: "0-3", [In("Hatcher Remains", 1), Out("Alien Protein", 1)]),
        new( 17, "Hog Protein",             Batch: 3,  Tier: "0-3", [In("Hog Remains", 1), Out("Alien Protein", 1)]),
        new( 18, "Iron Rebar",              Batch: 4,  Tier: "0-3", [In("Iron Rod", 1), Out("Iron Rebar", 1)]),
        new( 19, "Power Shard (1)",         Batch: 8,  Tier: "0-3", [In("Blue Power Slug", 1), Out("Power Shard", 1)]),
        new( 20, "Power Shard (2)",         Batch: 12, Tier: "0-3", [In("Yellow Power Slug", 1), Out("Power Shard", 2)]),
        new( 21, "Power Shard (5)",         Batch: 24, Tier: "0-3", [In("Purple Power Slug", 1), Out("Power Shard", 5)]),
        new( 24, "Screws",                  Batch: 6,  Tier: "0-3", [In("Iron Rod", 1), Out("Screws", 4)]),
        new( 25, "Snowball",                Batch: 12, Tier: "0-3", [In("FICSMAS Actual Snow", 3), Out("Snowball", 1)], Ficsmas: true),
        new( 26, "Spitter Protein",         Batch: 3,  Tier: "0-3", [In("Spitter Remains", 1), Out("Alien Protein", 1)]),
        new( 27, "Stinger Protein",         Batch: 3,  Tier: "0-3", [In("Stinger Remains", 1), Out("Alien Protein", 1)]),
        new( 28, "Biocoal",                 Batch: 8,  Tier: "0-3", [In("Biomass", 5), Out("Coal", 6)], Alternate: true),
        new( 29, "Cast Screws",             Batch: 24, Tier: "0-3", [In("Iron Ingot", 5), Out("Screws", 20)], Alternate: true),
        new( 30, "Charcoal",                Batch: 4,  Tier: "0-3", [In("Wood", 1), Out("Coal", 10)], Alternate: true),
        new( 31, "Iron Pipe",               Batch: 12, Tier: "0-3", [In("Iron Ingot", 20), Out("Steel Pipe", 5)], Alternate: true),
        new( 32, "Iron Wire",               Batch: 24, Tier: "0-3", [In("Iron Ingot", 5), Out("Wire", 9)], Alternate: true),
        new( 38, "Quartz Crystal",          Batch: 8,  Tier: "0-5", [In("Raw Quartz", 5), Out("Quartz Crystal", 3)]),
        new( 39, "Quickwire",               Batch: 5,  Tier: "0-5", [In("Caterium Ingot", 1), Out("Quickwire", 5)]),
        new( 42, "Silica",                  Batch: 8,  Tier: "0-5", [In("Raw Quartz", 3), Out("Silica", 5)]),
        new( 44, "Caterium Wire",           Batch: 4,  Tier: "0-5", [In("Caterium Ingot", 1), Out("Wire", 8)], Alternate: true),
        new( 45, "Biomass (Leaves)",        Batch: 5,  Tier: "0-6", [In("Leaves", 10), Out("Biomass", 5)]),
        new( 46, "Biomass (Wood)",          Batch: 4,  Tier: "0-6", [In("Wood", 4), Out("Biomass", 20)]),
        new( 52, "Copper Sheet",            Batch: 6,  Tier: "2-1", [In("Copper Ingot", 2), Out("Copper Sheet", 1)]),
        new( 73, "Solid Biofuel",           Batch: 4,  Tier: "2-2", [In("Biomass", 8), Out("Solid Biofuel", 4)]),
        new( 90, "Steel Beam",              Batch: 4,  Tier: "3-3", [In("Steel Ingot", 4), Out("Steel Beam", 1)]),
        new( 92, "Steel Pipe",              Batch: 6,  Tier: "3-3", [In("Steel Ingot", 3), Out("Steel Pipe", 2)]),
        new(105, "Steel Canister",          Batch: 6,  Tier: "3-3", [In("Steel Ingot", 4), Out("Empty Canister", 4)], Alternate: true),
        new(107, "Steel Rod",               Batch: 5,  Tier: "3-3", [In("Steel Ingot", 1), Out("Iron Rod", 4)], Alternate: true),
        new(109, "Steel Screws",            Batch: 12, Tier: "3-3", [In("Steel Beam", 1), Out("Screws", 52)], Alternate: true),
        new(154, "Empty Canister",          Batch: 4,  Tier: "5-4", [In("Plastic", 2), Out("Empty Canister", 4)]),
        new(197, "Aluminum Casing",         Batch: 2,  Tier: "7-1", [In("Aluminum Ingot", 3), Out("Aluminum Casing", 2)]),
        new(205, "Aluminum Beam",           Batch: 8,  Tier: "7-1", [In("Aluminum Ingot", 3), Out("Steel Beam", 3)], Alternate: true),
        new(206, "Aluminum Rod",            Batch: 8,  Tier: "7-1", [In("Aluminum Ingot", 1), Out("Iron Rod", 7)], Alternate: true),
        new(241, "Empty Fluid Tank",        Batch: 1,  Tier: "8-3", [In("Aluminum Ingot", 1), Out("Empty Fluid Tank", 1)]),
        new(256, "Copper Powder",           Batch: 6,  Tier: "8-5", [In("Copper Ingot", 30), Out("Copper Powder", 5)]),
        new(300, "Ficsite Trigon",          Batch: 6,  Tier: "9-1", [In("Ficsite Ingot", 1), Out("Ficsite Trigon", 3)]),
        new(307, "Reanimated SAM",          Batch: 2,  Tier: "9-1", [In("SAM", 4), Out("Reanimated SAM", 1)]),
    ];
}
