// <auto-generated>
// Generated by Ficsit.Schematics.CatalogGenerator from Docs/en-US.json — do not edit.
// Regenerate with: dotnet run --project Ficsit.Schematics.CatalogGenerator -- --write
// </auto-generated>
namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

/// <summary>Recipes that run on the Converter.</summary>
public sealed class ConverterRecipes : RecipeModule
{
    protected override string Machine => "Converter";

    protected override IReadOnlyList<Recipe> Recipes =>
    [
        new(287, "Bauxite (Caterium)",       Batch: 6,  Tier: "9-1", [In("Reanimated SAM", 1), In("Caterium Ore", 15), Out("Bauxite", 12)], AveragePower: -250, MinPower: -400),
        new(288, "Bauxite (Copper)",         Batch: 6,  Tier: "9-1", [In("Reanimated SAM", 1), In("Copper Ore", 18), Out("Bauxite", 12)], AveragePower: -250, MinPower: -400),
        new(290, "Caterium Ore (Copper)",    Batch: 6,  Tier: "9-1", [In("Reanimated SAM", 1), In("Copper Ore", 15), Out("Caterium Ore", 12)], AveragePower: -250, MinPower: -400),
        new(291, "Caterium Ore (Quartz)",    Batch: 6,  Tier: "9-1", [In("Reanimated SAM", 1), In("Raw Quartz", 12), Out("Caterium Ore", 12)], AveragePower: -250, MinPower: -400),
        new(292, "Coal (Iron)",              Batch: 6,  Tier: "9-1", [In("Reanimated SAM", 1), In("Iron Ore", 18), Out("Coal", 12)], AveragePower: -250, MinPower: -400),
        new(293, "Coal (Limestone)",         Batch: 6,  Tier: "9-1", [In("Reanimated SAM", 1), In("Limestone", 36), Out("Coal", 12)], AveragePower: -250, MinPower: -400),
        new(294, "Copper Ore (Quartz)",      Batch: 6,  Tier: "9-1", [In("Reanimated SAM", 1), In("Raw Quartz", 10), Out("Copper Ore", 12)], AveragePower: -250, MinPower: -400),
        new(295, "Copper Ore (Sulfur)",      Batch: 6,  Tier: "9-1", [In("Reanimated SAM", 1), In("Sulfur", 12), Out("Copper Ore", 12)], AveragePower: -250, MinPower: -400),
        new(297, "Ficsite Ingot (Aluminum)", Batch: 2,  Tier: "9-1", [In("Reanimated SAM", 2), In("Aluminum Ingot", 4), Out("Ficsite Ingot", 1)], AveragePower: -250, MinPower: -400),
        new(298, "Ficsite Ingot (Caterium)", Batch: 4,  Tier: "9-1", [In("Reanimated SAM", 3), In("Caterium Ingot", 4), Out("Ficsite Ingot", 1)], AveragePower: -250, MinPower: -400),
        new(299, "Ficsite Ingot (Iron)",     Batch: 6,  Tier: "9-1", [In("Reanimated SAM", 4), In("Iron Ingot", 24), Out("Ficsite Ingot", 1)], AveragePower: -250, MinPower: -400),
        new(301, "Iron Ore (Limestone)",     Batch: 6,  Tier: "9-1", [In("Reanimated SAM", 1), In("Limestone", 24), Out("Iron Ore", 12)], AveragePower: -250, MinPower: -400),
        new(302, "Limestone (Sulfur)",       Batch: 6,  Tier: "9-1", [In("Reanimated SAM", 1), In("Sulfur", 2), Out("Limestone", 12)], AveragePower: -250, MinPower: -400),
        new(303, "Nitrogen Gas (Bauxite)",   Batch: 6,  Tier: "9-1", [In("Reanimated SAM", 1), In("Bauxite", 10), Out("Nitrogen Gas", 12)], AveragePower: -250, MinPower: -400),
        new(304, "Nitrogen Gas (Caterium)",  Batch: 6,  Tier: "9-1", [In("Reanimated SAM", 1), In("Caterium Ore", 12), Out("Nitrogen Gas", 12)], AveragePower: -250, MinPower: -400),
        new(305, "Raw Quartz (Bauxite)",     Batch: 6,  Tier: "9-1", [In("Reanimated SAM", 1), In("Bauxite", 10), Out("Raw Quartz", 12)], AveragePower: -250, MinPower: -400),
        new(306, "Raw Quartz (Coal)",        Batch: 6,  Tier: "9-1", [In("Reanimated SAM", 1), In("Coal", 24), Out("Raw Quartz", 12)], AveragePower: -250, MinPower: -400),
        new(309, "Sulfur (Coal)",            Batch: 6,  Tier: "9-1", [In("Reanimated SAM", 1), In("Coal", 20), Out("Sulfur", 12)], AveragePower: -250, MinPower: -400),
        new(310, "Sulfur (Iron)",            Batch: 6,  Tier: "9-1", [In("Reanimated SAM", 1), In("Iron Ore", 30), Out("Sulfur", 12)], AveragePower: -250, MinPower: -400),
        new(311, "Time Crystal",             Batch: 10, Tier: "9-1", [In("Diamonds", 2), Out("Time Crystal", 1)], AveragePower: -250, MinPower: -400),
        new(312, "Uranium Ore (Bauxite)",    Batch: 6,  Tier: "9-1", [In("Reanimated SAM", 1), In("Bauxite", 48), Out("Uranium", 12)], AveragePower: -250, MinPower: -400),
        new(313, "Pink Diamonds",            Batch: 4,  Tier: "9-1", [In("Coal", 8), In("Quartz Crystal", 3), Out("Diamonds", 1)], Alternate: true, AveragePower: -250, MinPower: -400),
        new(318, "Dark Matter Residue",      Batch: 6,  Tier: "9-2", [In("Reanimated SAM", 5), Out("Dark Matter Residue", 10)], AveragePower: -250, MinPower: -400),
        new(319, "Excited Photonic Matter",  Batch: 3,  Tier: "9-2", [Out("Excited Photonic Matter", 10)], AveragePower: -250, MinPower: -400),
        new(325, "Dark-Ion Fuel",            Batch: 3,  Tier: "9-2", [In("Packaged Rocket Fuel", 12), In("Dark Matter Crystal", 4), Out("Ionized Fuel", 10), Out("Compacted Coal", 2)], Alternate: true, AveragePower: -250, MinPower: -400),
    ];
}
