// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class CoolingDevice : RecipeBase
{
    public override int SortIndex => 259;
    public override string RecipeName => "Cooling Device";
    public override string Machine => "Blender";
    public override string BatchTime => "24";
    public override string Tier => "8-3";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Heat Sink", Amount = "-4" },
        new() { Part = "Motor", Amount = "-1" },
        new() { Part = "Nitrogen Gas", Amount = "-24" },
        new() { Part = "Cooling System", Amount = "2" },
    ];
}
