// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class CopperSheet : RecipeBase
{
    public override int SortIndex => 83;
    public override string RecipeName => "Copper Sheet";
    public override string Machine => "Constructor";
    public override string BatchTime => "6";
    public override string Tier => "2-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Copper Ingot", Amount = "-2" },
        new() { Part = "Copper Sheet", Amount = "1" },
    ];
}
