// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class CopperIngot : RecipeBase
{
    public override int SortIndex => 30;
    public override string RecipeName => "Copper Ingot";
    public override string Machine => "Smelter";
    public override string BatchTime => "2";
    public override string Tier => "0-2";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Copper Ore", Amount = "-1" },
        new() { Part = "Copper Ingot", Amount = "1" },
    ];
}
