// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class CopperRotor : RecipeBase
{
    public override int SortIndex => 88;
    public override string RecipeName => "Copper Rotor";
    public override string Machine => "Assembler";
    public override string BatchTime => "16";
    public override string Tier => "2-1";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Copper Sheet", Amount = "-6" },
        new() { Part = "Screw", Amount = "-52" },
        new() { Part = "Rotor", Amount = "3" },
    ];
}
