// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class CopperAlloyIngot : RecipeBase
{
    public override int SortIndex => 31;
    public override string RecipeName => "Copper Alloy Ingot";
    public override string Machine => "Foundry";
    public override string BatchTime => "6";
    public override string Tier => "3-3";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Copper Ore", Amount = "-5" },
        new() { Part = "Iron Ore", Amount = "-5" },
        new() { Part = "Copper Ingot", Amount = "10" },
    ];
}
