// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class DarkIonFuel : RecipeBase
{
    public override int SortIndex => 176;
    public override string RecipeName => "Dark-Ion Fuel";
    public override string Machine => "Converter";
    public override string BatchTime => "3";
    public override string Tier => "9-2";
    public override bool Alternate => true;
    public override string? AveragePower => "-250";
    public override string? MinPower => "-400";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Packaged Rocket Fuel", Amount = "-12" },
        new() { Part = "Dark Matter Crystal", Amount = "-4" },
        new() { Part = "Ionized Fuel", Amount = "10" },
        new() { Part = "Compacted Coal", Amount = "2" },
    ];
}
