// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class DarkMatterCrystal : RecipeBase
{
    public override int SortIndex => 301;
    public override string RecipeName => "Dark Matter Crystal";
    public override string Machine => "Particle Accelerator";
    public override string BatchTime => "2";
    public override string Tier => "9-2";
    public override string? AveragePower => "-1000";
    public override string? MinPower => "-1500";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Diamonds", Amount = "-1" },
        new() { Part = "Dark Matter Residue", Amount = "-5" },
        new() { Part = "Dark Matter Crystal", Amount = "1" },
    ];
}
