// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class DarkMatterResidue : RecipeBase
{
    public override int SortIndex => 306;
    public override string RecipeName => "Dark Matter Residue";
    public override string Machine => "Converter";
    public override string BatchTime => "6";
    public override string Tier => "9-2";
    public override string? AveragePower => "-250";
    public override string? MinPower => "-400";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Reanimated SAM", Amount = "-5" },
        new() { Part = "Dark Matter Residue", Amount = "10" },
    ];
}
