// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class DistilledSilica : RecipeBase
{
    public override int SortIndex => 106;
    public override string RecipeName => "Distilled Silica";
    public override string Machine => "Blender";
    public override string BatchTime => "6";
    public override string Tier => "8-5";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Dissolved Silica", Amount = "-12" },
        new() { Part = "Limestone", Amount = "-5" },
        new() { Part = "Water", Amount = "-10" },
        new() { Part = "Silica", Amount = "27" },
        new() { Part = "Water", Amount = "8" },
    ];
}
