// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class ElectromagneticControlRod : RecipeBase
{
    public override int SortIndex => 248;
    public override string RecipeName => "Electromagnetic Control Rod";
    public override string Machine => "Assembler";
    public override string BatchTime => "30";
    public override string Tier => "8-2";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Stator", Amount = "-3" },
        new() { Part = "AI Limiter", Amount = "-2" },
        new() { Part = "Electromagnetic Control Rod", Amount = "2" },
    ];
}
