// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class ElectromagneticConnectionRod : RecipeBase
{
    public override int SortIndex => 249;
    public override string RecipeName => "Electromagnetic Connection Rod";
    public override string Machine => "Assembler";
    public override string BatchTime => "15";
    public override string Tier => "8-2";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Stator", Amount = "-2" },
        new() { Part = "High-Speed Connector", Amount = "-1" },
        new() { Part = "Electromagnetic Control Rod", Amount = "2" },
    ];
}
