// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class EmptyFluidTank : RecipeBase
{
    public override int SortIndex => 163;
    public override string RecipeName => "Empty Fluid Tank";
    public override string Machine => "Constructor";
    public override string BatchTime => "1";
    public override string Tier => "8-3";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Aluminum Ingot", Amount = "-1" },
        new() { Part = "Empty Fluid Tank", Amount = "1" },
    ];
}
