// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class Fabric : RecipeBase
{
    public override int SortIndex => 85;
    public override string RecipeName => "Fabric";
    public override string Machine => "Assembler";
    public override string BatchTime => "4";
    public override string Tier => "2-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Mycelia", Amount = "-1" },
        new() { Part = "Biomass", Amount = "-5" },
        new() { Part = "Fabric", Amount = "1" },
    ];
}
