// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class FicsiteTrigon : RecipeBase
{
    public override int SortIndex => 294;
    public override string RecipeName => "Ficsite Trigon";
    public override string Machine => "Constructor";
    public override string BatchTime => "6";
    public override string Tier => "9-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Ficsite Ingot", Amount = "-1" },
        new() { Part = "Ficsite Trigon", Amount = "3" },
    ];
}
