// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class Ficsonium : RecipeBase
{
    public override int SortIndex => 313;
    public override string RecipeName => "Ficsonium";
    public override string Machine => "Particle Accelerator";
    public override string BatchTime => "6";
    public override string Tier => "9-5";
    public override string? AveragePower => "-1000";
    public override string? MinPower => "-1500";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Plutonium Waste", Amount = "-1" },
        new() { Part = "Singularity Cell", Amount = "-1" },
        new() { Part = "Dark Matter Residue", Amount = "-20" },
        new() { Part = "Ficsonium", Amount = "1" },
    ];
}
