// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class FicsoniumNuclearPowerPlant : RecipeBase
{
    public override int SortIndex => 315;
    public override string RecipeName => "Ficsonium Nuclear Power Plant";
    public override string Machine => "Nuclear Power Plant";
    public override string BatchTime => "60";
    public override string Tier => "9-5";
    public override bool IgnoreInputMultiplier => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Ficsonium Fuel Rod", Amount = "-1" },
        new() { Part = "Water", Amount = "-240" },
    ];
}
