// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class FicsiteIngotCaterium : RecipeBase
{
    public override int SortIndex => 296;
    public override string RecipeName => "Ficsite Ingot (Caterium)";
    public override string Machine => "Converter";
    public override string BatchTime => "4";
    public override string Tier => "9-1";
    public override string? AveragePower => "-250";
    public override string? MinPower => "-400";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Reanimated SAM", Amount = "-3" },
        new() { Part = "Caterium Ingot", Amount = "-4" },
        new() { Part = "Ficsite Ingot", Amount = "1" },
    ];
}
