// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class FicsoniumFuelRod : RecipeBase
{
    public override int SortIndex => 314;
    public override string RecipeName => "Ficsonium Fuel Rod";
    public override string Machine => "Quantum Encoder";
    public override string BatchTime => "24";
    public override string Tier => "9-5";
    public override string? AveragePower => "-1000";
    public override string? MinPower => "-2000";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Ficsonium", Amount = "-2" },
        new() { Part = "Electromagnetic Control Rod", Amount = "-2" },
        new() { Part = "Ficsite Trigon", Amount = "-40" },
        new() { Part = "Excited Photonic Matter", Amount = "-20" },
        new() { Part = "Ficsonium Fuel Rod", Amount = "1" },
        new() { Part = "Dark Matter Residue", Amount = "20" },
    ];
}
