// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class FICSMASWonderStar : RecipeBase
{
    public override int SortIndex => 331;
    public override string RecipeName => "FICSMAS Wonder Star";
    public override string Machine => "Assembler";
    public override string BatchTime => "60";
    public override string Tier => "3-3";
    public override bool Ficsmas => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "FICSMAS Wreath", Amount = "-5" },
        new() { Part = "Candy Cane", Amount = "-20" },
        new() { Part = "FICSMAS Wonder Star", Amount = "1" },
    ];
}
