// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class FineConcrete : RecipeBase
{
    public override int SortIndex => 53;
    public override string RecipeName => "Fine Concrete";
    public override string Machine => "Assembler";
    public override string BatchTime => "12";
    public override string Tier => "2-1";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Silica", Amount = "-3" },
        new() { Part = "Limestone", Amount = "-12" },
        new() { Part = "Concrete", Amount = "10" },
    ];
}
