// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class FineBlackPowder : RecipeBase
{
    public override int SortIndex => 104;
    public override string RecipeName => "Fine Black Powder";
    public override string Machine => "Assembler";
    public override string BatchTime => "8";
    public override string Tier => "5-4";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Sulfur", Amount = "-1" },
        new() { Part = "Compacted Coal", Amount = "-2" },
        new() { Part = "Black Powder", Amount = "6" },
    ];
}
