// <auto-generated>
// Generated by Ficsit.Schematics.CatalogGenerator from Docs/en-US.json — do not edit.
// Regenerate with: dotnet run --project Ficsit.Schematics.CatalogGenerator -- --write
// </auto-generated>
namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

/// <summary>Recipes that run on the Foundry.</summary>
public sealed class FoundryRecipes : RecipeModule
{
    protected override string Machine => "Foundry";

    protected override IReadOnlyList<Recipe> Recipes =>
    [
        new( 83, "Copper FICSMAS Ornament", Batch: 12, Tier: "3-3", [In("Red FICSMAS Ornament", 2), In("Copper Ingot", 2), Out("Copper FICSMAS Ornament", 1)], Ficsmas: true),
        new( 88, "Iron FICSMAS Ornament",   Batch: 12, Tier: "3-3", [In("Blue FICSMAS Ornament", 3), In("Iron Ingot", 3), Out("Iron FICSMAS Ornament", 1)], Ficsmas: true),
        new( 91, "Steel Ingot",             Batch: 4,  Tier: "3-3", [In("Iron Ore", 3), In("Coal", 3), Out("Steel Ingot", 3)]),
        new( 95, "Basic Iron Ingot",        Batch: 12, Tier: "3-3", [In("Iron Ore", 5), In("Limestone", 8), Out("Iron Ingot", 10)], Alternate: true),
        new( 96, "Compacted Steel Ingot",   Batch: 24, Tier: "3-3", [In("Iron Ore", 2), In("Compacted Coal", 1), Out("Steel Ingot", 4)], Alternate: true),
        new( 97, "Copper Alloy Ingot",      Batch: 6,  Tier: "3-3", [In("Copper Ore", 5), In("Iron Ore", 5), Out("Copper Ingot", 10)], Alternate: true),
        new( 99, "Fused Quartz Crystal",    Batch: 20, Tier: "3-3", [In("Raw Quartz", 25), In("Coal", 12), Out("Quartz Crystal", 18)], Alternate: true),
        new(100, "Iron Alloy Ingot",        Batch: 12, Tier: "3-3", [In("Iron Ore", 8), In("Copper Ore", 2), Out("Iron Ingot", 15)], Alternate: true),
        new(101, "Molded Beam",             Batch: 12, Tier: "3-3", [In("Steel Ingot", 24), In("Concrete", 16), Out("Steel Beam", 9)], Alternate: true),
        new(102, "Molded Steel Pipe",       Batch: 6,  Tier: "3-3", [In("Steel Ingot", 5), In("Concrete", 3), Out("Steel Pipe", 5)], Alternate: true),
        new(104, "Solid Steel Ingot",       Batch: 3,  Tier: "3-3", [In("Iron Ingot", 2), In("Coal", 2), Out("Steel Ingot", 3)], Alternate: true),
        new(106, "Steel Cast Plate",        Batch: 4,  Tier: "3-3", [In("Iron Ingot", 1), In("Steel Ingot", 1), Out("Iron Plate", 3)], Alternate: true),
        new(133, "Coke Steel Ingot",        Batch: 12, Tier: "5-2", [In("Iron Ore", 15), In("Petroleum Coke", 15), Out("Steel Ingot", 20)], Alternate: true),
        new(149, "Tempered Caterium Ingot", Batch: 8,  Tier: "5-2", [In("Caterium Ore", 6), In("Petroleum Coke", 2), Out("Caterium Ingot", 3)], Alternate: true),
        new(150, "Tempered Copper Ingot",   Batch: 12, Tier: "5-2", [In("Copper Ore", 5), In("Petroleum Coke", 8), Out("Copper Ingot", 12)], Alternate: true),
        new(198, "Aluminum Ingot",          Batch: 4,  Tier: "7-1", [In("Aluminum Scrap", 6), In("Silica", 5), Out("Aluminum Ingot", 4)]),
    ];
}
