// <auto-generated>
// Generated by Ficsit.Schematics.CatalogGenerator from Docs/en-US.json — do not edit.
// Regenerate with: dotnet run --project Ficsit.Schematics.CatalogGenerator -- --write
// </auto-generated>
namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

/// <summary>Recipes that run on the Fuel-Powered Generator.</summary>
public sealed class FuelPoweredGeneratorRecipes : RecipeModule
{
    protected override string Machine => "Fuel-Powered Generator";

    protected override IReadOnlyList<Recipe> Recipes =>
    [
        new(170, "Fuel Generator",           Batch: 3,         Tier: "5-5", [In("Fuel", 1)], IgnoreInputMultiplier: true),
        new(171, "Liquid Biofuel Generator", Batch: 3,         Tier: "5-5", [In("Liquid Biofuel", 1)], IgnoreInputMultiplier: true),
        new(172, "Turbofuel Generator",      Batch: 8,         Tier: "5-5", [In("Turbofuel", 1)], IgnoreInputMultiplier: true),
        new(259, "Ionized Fuel Generator",   Batch: 20,        Tier: "8-5", [In("Ionized Fuel", 1)], IgnoreInputMultiplier: true),
        new(271, "Rocket Fuel Generator",    Batch: R("72/5"), Tier: "8-5", [In("Rocket Fuel", 1)], IgnoreInputMultiplier: true),
    ];
}
