// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class FusedQuickwire : RecipeBase
{
    public override int SortIndex => 190;
    public override string RecipeName => "Fused Quickwire";
    public override string Machine => "Assembler";
    public override string BatchTime => "8";
    public override string Tier => "5-5";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Caterium Ingot", Amount = "-1" },
        new() { Part = "Copper Ingot", Amount = "-5" },
        new() { Part = "Quickwire", Amount = "12" },
    ];
}
