// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class GasFilter : RecipeBase
{
    public override int SortIndex => 199;
    public override string RecipeName => "Gas Filter";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "8";
    public override string Tier => "6-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Fabric", Amount = "-2" },
        new() { Part = "Coal", Amount = "-4" },
        new() { Part = "Iron Plate", Amount = "-2" },
        new() { Part = "Gas Filter", Amount = "1" },
    ];
}
