// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class GeothermalGenerator : RecipeBase
{
    public override int SortIndex => 215;
    public override string RecipeName => "Geothermal Generator";
    public override string Machine => "Geothermal Generator";
    public override string BatchTime => "0";
    public override string Tier => "6-1";
    public override bool IgnoreInputMultiplier => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
    ];
}
