// <auto-generated>
// Generated by Ficsit.Schematics.CatalogGenerator from Docs/en-US.json — do not edit.
// Regenerate with: dotnet run --project Ficsit.Schematics.CatalogGenerator -- --write
// </auto-generated>
namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

/// <summary>Recipes that run on the Geothermal Generator.</summary>
public sealed class GeothermalGeneratorRecipes : RecipeModule
{
    protected override string Machine => "Geothermal Generator";

    protected override IReadOnlyList<Recipe> Recipes =>
    [
        new(79, "Geothermal Generator", Batch: 0, Tier: "3-1", [], IgnoreInputMultiplier: true),
    ];
}
