// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class HeatSink : RecipeBase
{
    public override int SortIndex => 256;
    public override string RecipeName => "Heat Sink";
    public override string Machine => "Assembler";
    public override string BatchTime => "8";
    public override string Tier => "8-3";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Alclad Aluminum Sheet", Amount = "-5" },
        new() { Part = "Copper Sheet", Amount = "-3" },
        new() { Part = "Heat Sink", Amount = "1" },
    ];
}
