// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class HeavyModularFrame : RecipeBase
{
    public override int SortIndex => 210;
    public override string RecipeName => "Heavy Modular Frame";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "30";
    public override string Tier => "6-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Modular Frame", Amount = "-5" },
        new() { Part = "Steel Pipe", Amount = "-20" },
        new() { Part = "Encased Industrial Beam", Amount = "-5" },
        new() { Part = "Screw", Amount = "-120" },
        new() { Part = "Heavy Modular Frame", Amount = "1" },
    ];
}
