// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class HighSpeedConnector : RecipeBase
{
    public override int SortIndex => 204;
    public override string RecipeName => "High-Speed Connector";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "16";
    public override string Tier => "6-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Quickwire", Amount = "-56" },
        new() { Part = "Cable", Amount = "-10" },
        new() { Part = "Circuit Board", Amount = "-1" },
        new() { Part = "High-Speed Connector", Amount = "1" },
    ];
}
