// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class InfusedUraniumCell : RecipeBase
{
    public override int SortIndex => 247;
    public override string RecipeName => "Infused Uranium Cell";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "12";
    public override string Tier => "8-2";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Uranium", Amount = "-5" },
        new() { Part = "Silica", Amount = "-3" },
        new() { Part = "Sulfur", Amount = "-5" },
        new() { Part = "Quickwire", Amount = "-15" },
        new() { Part = "Encased Uranium Cell", Amount = "4" },
    ];
}
