// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class InstantPlutoniumCell : RecipeBase
{
    public override int SortIndex => 279;
    public override string RecipeName => "Instant Plutonium Cell";
    public override string Machine => "Particle Accelerator";
    public override string BatchTime => "120";
    public override string Tier => "8-5";
    public override bool Alternate => true;
    public override string? AveragePower => "-500";
    public override string? MinPower => "-750";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Non-Fissile Uranium", Amount = "-150" },
        new() { Part = "Aluminum Casing", Amount = "-20" },
        new() { Part = "Encased Plutonium Cell", Amount = "20" },
    ];
}
