// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class InstantScrap : RecipeBase
{
    public override int SortIndex => 220;
    public override string RecipeName => "Instant Scrap";
    public override string Machine => "Blender";
    public override string BatchTime => "6";
    public override string Tier => "7-5";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Bauxite", Amount = "-15" },
        new() { Part = "Coal", Amount = "-10" },
        new() { Part = "Sulfuric Acid", Amount = "-5" },
        new() { Part = "Water", Amount = "-6" },
        new() { Part = "Aluminum Scrap", Amount = "30" },
        new() { Part = "Water", Amount = "5" },
    ];
}
