// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class InsulatedCable : RecipeBase
{
    public override int SortIndex => 41;
    public override string RecipeName => "Insulated Cable";
    public override string Machine => "Assembler";
    public override string BatchTime => "12";
    public override string Tier => "5-2";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Wire", Amount = "-9" },
        new() { Part = "Rubber", Amount = "-6" },
        new() { Part = "Cable", Amount = "20" },
    ];
}
