// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class InsulatedCrystalOscillator : RecipeBase
{
    public override int SortIndex => 203;
    public override string RecipeName => "Insulated Crystal Oscillator";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "32";
    public override string Tier => "6-1";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Quartz Crystal", Amount = "-10" },
        new() { Part = "Rubber", Amount = "-7" },
        new() { Part = "AI Limiter", Amount = "-1" },
        new() { Part = "Crystal Oscillator", Amount = "1" },
    ];
}
