// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class IodineInfusedFilter : RecipeBase
{
    public override int SortIndex => 232;
    public override string RecipeName => "Iodine-Infused Filter";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "16";
    public override string Tier => "7-4";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Gas Filter", Amount = "-1" },
        new() { Part = "Quickwire", Amount = "-8" },
        new() { Part = "Aluminum Casing", Amount = "-1" },
        new() { Part = "Iodine-Infused Filter", Amount = "1" },
    ];
}
