// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class IronPlate : RecipeBase
{
    public override int SortIndex => 25;
    public override string RecipeName => "Iron Plate";
    public override string Machine => "Constructor";
    public override string BatchTime => "6";
    public override string Tier => "0-0";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Iron Ingot", Amount = "-3" },
        new() { Part = "Iron Plate", Amount = "2" },
    ];
}
