// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class IronIngot : RecipeBase
{
    public override int SortIndex => 16;
    public override string RecipeName => "Iron Ingot";
    public override string Machine => "Smelter";
    public override string BatchTime => "2";
    public override string Tier => "0-0";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Iron Ore", Amount = "-1" },
        new() { Part = "Iron Ingot", Amount = "1" },
    ];
}
