// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class IronRod : RecipeBase
{
    public override int SortIndex => 22;
    public override string RecipeName => "Iron Rod";
    public override string Machine => "Constructor";
    public override string BatchTime => "4";
    public override string Tier => "0-0";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Iron Ingot", Amount = "-1" },
        new() { Part = "Iron Rod", Amount = "1" },
    ];
}
