// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class IronWire : RecipeBase
{
    public override int SortIndex => 36;
    public override string RecipeName => "Iron Wire";
    public override string Machine => "Constructor";
    public override string BatchTime => "24";
    public override string Tier => "0-3";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Iron Ingot", Amount = "-5" },
        new() { Part = "Wire", Amount = "9" },
    ];
}
