// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class LeachedCopperIngot : RecipeBase
{
    public override int SortIndex => 34;
    public override string RecipeName => "Leached Copper Ingot";
    public override string Machine => "Refinery";
    public override string BatchTime => "12";
    public override string Tier => "7-5";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Copper Ore", Amount = "-9" },
        new() { Part = "Sulfuric Acid", Amount = "-5" },
        new() { Part = "Copper Ingot", Amount = "22" },
    ];
}
