// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class LeachedIronIngot : RecipeBase
{
    public override int SortIndex => 20;
    public override string RecipeName => "Leached Iron ingot";
    public override string Machine => "Refinery";
    public override string BatchTime => "6";
    public override string Tier => "7-5";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Iron Ore", Amount = "-5" },
        new() { Part = "Sulfuric Acid", Amount = "-1" },
        new() { Part = "Iron Ingot", Amount = "10" },
    ];
}
