// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class LiquidBiofuelGenerator : RecipeBase
{
    public override int SortIndex => 179;
    public override string RecipeName => "Liquid Biofuel Generator";
    public override string Machine => "Fuel-Powered Generator";
    public override string BatchTime => "3";
    public override string Tier => "5-5";
    public override bool IgnoreInputMultiplier => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Liquid Biofuel", Amount = "-1" },
    ];
}
