// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class LiquidBiofuel : RecipeBase
{
    public override int SortIndex => 177;
    public override string RecipeName => "Liquid Biofuel";
    public override string Machine => "Refinery";
    public override string BatchTime => "4";
    public override string Tier => "5-4";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Solid Biofuel", Amount = "-6" },
        new() { Part = "Water", Amount = "-3" },
        new() { Part = "Liquid Biofuel", Amount = "4" },
    ];
}
