// <auto-generated>
// Generated by Ficsit.Schematics.CatalogGenerator from Docs/en-US.json — do not edit.
// Regenerate with: dotnet run --project Ficsit.Schematics.CatalogGenerator -- --write
// </auto-generated>
namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

/// <summary>Recipes that run on the Miner.</summary>
public sealed class MinerRecipes : RecipeModule
{
    protected override string Machine => "Miner";

    protected override IReadOnlyList<Recipe> Recipes =>
    [
        new( 34, "Caterium Ore", Batch: 60, Tier: "0-5", [Out("Caterium Ore", 1)]),
        new( 35, "Copper Ore",   Batch: 60, Tier: "0-5", [Out("Copper Ore", 1)]),
        new( 36, "Iron Ore",     Batch: 60, Tier: "0-5", [Out("Iron Ore", 1)]),
        new( 37, "Limestone",    Batch: 60, Tier: "0-5", [Out("Limestone", 1)]),
        new( 40, "Raw Quartz",   Batch: 60, Tier: "0-5", [Out("Raw Quartz", 1)]),
        new( 41, "SAM",          Batch: 60, Tier: "0-5", [Out("SAM", 1)]),
        new( 43, "Sulfur",       Batch: 60, Tier: "0-5", [Out("Sulfur", 1)]),
        new( 76, "Coal",         Batch: 60, Tier: "3-1", [Out("Coal", 1)]),
        new(200, "Bauxite",      Batch: 60, Tier: "7-1", [Out("Bauxite", 1)]),
        new(232, "Uranium",      Batch: 60, Tier: "8-2", [Out("Uranium", 1)]),
    ];
}
