// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class ModularEngine : RecipeBase
{
    public override int SortIndex => 209;
    public override string RecipeName => "Modular Engine";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "60";
    public override string Tier => "6-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Motor", Amount = "-2" },
        new() { Part = "Rubber", Amount = "-15" },
        new() { Part = "Smart Plating", Amount = "-2" },
        new() { Part = "Modular Engine", Amount = "1" },
    ];
}
