// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class MoldedBeam : RecipeBase
{
    public override int SortIndex => 116;
    public override string RecipeName => "Molded Beam";
    public override string Machine => "Foundry";
    public override string BatchTime => "12";
    public override string Tier => "3-3";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Steel Ingot", Amount = "-24" },
        new() { Part = "Concrete", Amount = "-16" },
        new() { Part = "Steel Beam", Amount = "9" },
    ];
}
