// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class NitroRocketFuel : RecipeBase
{
    public override int SortIndex => 183;
    public override string RecipeName => "Nitro Rocket Fuel";
    public override string Machine => "Blender";
    public override string BatchTime => "12/5";
    public override string Tier => "8-3";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Fuel", Amount = "-4" },
        new() { Part = "Nitrogen Gas", Amount = "-3" },
        new() { Part = "Sulfur", Amount = "-4" },
        new() { Part = "Coal", Amount = "-2" },
        new() { Part = "Rocket Fuel", Amount = "6" },
        new() { Part = "Compacted Coal", Amount = "1" },
    ];
}
