// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class NuclearPasta : RecipeBase
{
    public override int SortIndex => 275;
    public override string RecipeName => "Nuclear Pasta";
    public override string Machine => "Particle Accelerator";
    public override string BatchTime => "120";
    public override string Tier => "8-5";
    public override string? AveragePower => "-1000";
    public override string? MinPower => "-1500";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Copper Powder", Amount = "-200" },
        new() { Part = "Pressure Conversion Cube", Amount = "-1" },
        new() { Part = "Nuclear Pasta", Amount = "1" },
    ];
}
