// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class OCSupercomputer : RecipeBase
{
    public override int SortIndex => 241;
    public override string RecipeName => "OC Supercomputer";
    public override string Machine => "Assembler";
    public override string BatchTime => "20";
    public override string Tier => "8-3";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Radio Control Unit", Amount = "-2" },
        new() { Part = "Cooling System", Amount = "-2" },
        new() { Part = "Supercomputer", Amount = "1" },
    ];
}
