// <auto-generated>
// Generated by Ficsit.Schematics.CatalogGenerator from Docs/en-US.json — do not edit.
// Regenerate with: dotnet run --project Ficsit.Schematics.CatalogGenerator -- --write
// </auto-generated>
namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

/// <summary>Recipes that run on the Particle Accelerator.</summary>
public sealed class ParticleAcceleratorRecipes : RecipeModule
{
    protected override string Machine => "Particle Accelerator";

    protected override IReadOnlyList<Recipe> Recipes =>
    [
        new(262, "Nuclear Pasta",               Batch: 120, Tier: "8-5", [In("Copper Powder", 200), In("Pressure Conversion Cube", 1), Out("Nuclear Pasta", 1)], AveragePower: -1000, MinPower: -1500),
        new(268, "Plutonium Pellet",            Batch: 60,  Tier: "8-5", [In("Non-Fissile Uranium", 100), In("Uranium Waste", 25), Out("Plutonium Pellet", 30)], AveragePower: -500, MinPower: -750),
        new(276, "Cloudy Diamonds",             Batch: 3,   Tier: "8-5", [In("Coal", 12), In("Limestone", 24), Out("Diamonds", 1)], Alternate: true, AveragePower: -500, MinPower: -750),
        new(280, "Instant Plutonium Cell",      Batch: 120, Tier: "8-5", [In("Non-Fissile Uranium", 150), In("Aluminum Casing", 20), Out("Encased Plutonium Cell", 20)], Alternate: true, AveragePower: -500, MinPower: -750),
        new(281, "Oil-Based Diamonds",          Batch: 3,   Tier: "8-5", [In("Crude Oil", 10), Out("Diamonds", 2)], Alternate: true, AveragePower: -500, MinPower: -750),
        new(282, "Petroleum Diamonds",          Batch: 2,   Tier: "8-5", [In("Petroleum Coke", 24), Out("Diamonds", 1)], Alternate: true, AveragePower: -500, MinPower: -750),
        new(285, "Turbo Diamonds",              Batch: 3,   Tier: "8-5", [In("Coal", 30), In("Packaged Turbofuel", 2), Out("Diamonds", 3)], Alternate: true, AveragePower: -500, MinPower: -750),
        new(296, "Diamonds",                    Batch: 2,   Tier: "9-1", [In("Coal", 20), Out("Diamonds", 1)], AveragePower: -500, MinPower: -750),
        new(317, "Dark Matter Crystal",         Batch: 2,   Tier: "9-2", [In("Diamonds", 1), In("Dark Matter Residue", 5), Out("Dark Matter Crystal", 1)], AveragePower: -1000, MinPower: -1500),
        new(323, "Dark Matter Crystallization", Batch: 3,   Tier: "9-2", [In("Dark Matter Residue", 10), Out("Dark Matter Crystal", 1)], Alternate: true, AveragePower: -1000, MinPower: -1500),
        new(324, "Dark Matter Trap",            Batch: 2,   Tier: "9-2", [In("Time Crystal", 1), In("Dark Matter Residue", 5), Out("Dark Matter Crystal", 2)], Alternate: true, AveragePower: -1000, MinPower: -1500),
        new(329, "Ficsonium",                   Batch: 6,   Tier: "9-5", [In("Plutonium Waste", 1), In("Singularity Cell", 1), In("Dark Matter Residue", 20), Out("Ficsonium", 1)], AveragePower: -1000, MinPower: -1500),
    ];
}
