// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class PlutoniumNuclearPowerPlant : RecipeBase
{
    public override int SortIndex => 285;
    public override string RecipeName => "Plutonium Nuclear Power Plant";
    public override string Machine => "Nuclear Power Plant";
    public override string BatchTime => "600";
    public override string Tier => "8-5";
    public override bool IgnoreInputMultiplier => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Plutonium Fuel Rod", Amount = "-1" },
        new() { Part = "Water", Amount = "-2400" },
        new() { Part = "Plutonium Waste", Amount = "10" },
    ];
}
