// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class PlutoniumPellet : RecipeBase
{
    public override int SortIndex => 284;
    public override string RecipeName => "Plutonium Pellet";
    public override string Machine => "Particle Accelerator";
    public override string BatchTime => "60";
    public override string Tier => "8-5";
    public override string? AveragePower => "-500";
    public override string? MinPower => "-750";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Non-Fissile Uranium", Amount = "-100" },
        new() { Part = "Uranium Waste", Amount = "-25" },
        new() { Part = "Plutonium Pellet", Amount = "30" },
    ];
}
