// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class PressureConversionCube : RecipeBase
{
    public override int SortIndex => 274;
    public override string RecipeName => "Pressure Conversion Cube";
    public override string Machine => "Assembler";
    public override string BatchTime => "60";
    public override string Tier => "8-5";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Fused Modular Frame", Amount = "-1" },
        new() { Part = "Radio Control Unit", Amount = "-2" },
        new() { Part = "Pressure Conversion Cube", Amount = "1" },
    ];
}
