// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class PureQuartzCrystal : RecipeBase
{
    public override int SortIndex => 82;
    public override string RecipeName => "Pure Quartz Crystal";
    public override string Machine => "Refinery";
    public override string BatchTime => "8";
    public override string Tier => "5-2";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Raw Quartz", Amount = "-9" },
        new() { Part = "Water", Amount = "-5" },
        new() { Part = "Quartz Crystal", Amount = "7" },
    ];
}
