// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class PureIronIngot : RecipeBase
{
    public override int SortIndex => 19;
    public override string RecipeName => "Pure Iron Ingot";
    public override string Machine => "Refinery";
    public override string BatchTime => "12";
    public override string Tier => "5-2";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Iron Ore", Amount = "-7" },
        new() { Part = "Water", Amount = "-4" },
        new() { Part = "Iron Ingot", Amount = "13" },
    ];
}
