// <auto-generated>
// Generated by Ficsit.Schematics.CatalogGenerator from Docs/en-US.json — do not edit.
// Regenerate with: dotnet run --project Ficsit.Schematics.CatalogGenerator -- --write
// </auto-generated>
namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

/// <summary>Recipes that run on the Quantum Encoder.</summary>
public sealed class QuantumEncoderRecipes : RecipeModule
{
    protected override string Machine => "Quantum Encoder";

    protected override IReadOnlyList<Recipe> Recipes =>
    [
        new(314, "AI Expansion Server",      Batch: 15, Tier: "9-2", [In("Magnetic Field Generator", 1), In("Neural-Quantum Processor", 1), In("Superposition Oscillator", 1), In("Excited Photonic Matter", 25), Out("AI Expansion Server", 1), Out("Dark Matter Residue", 25)], AveragePower: -1000, MinPower: -2000),
        new(316, "Alien Power Matrix",       Batch: 24, Tier: "9-2", [In("SAM Fluctuator", 5), In("Power Shard", 3), In("Superposition Oscillator", 3), In("Excited Photonic Matter", 24), Out("Alien Power Matrix", 1), Out("Dark Matter Residue", 24)], AveragePower: -1000, MinPower: -2000),
        new(320, "Neural-Quantum Processor", Batch: 20, Tier: "9-2", [In("Time Crystal", 5), In("Supercomputer", 1), In("Ficsite Trigon", 15), In("Excited Photonic Matter", 25), Out("Neural-Quantum Processor", 1), Out("Dark Matter Residue", 25)], AveragePower: -1000, MinPower: -2000),
        new(321, "Superposition Oscillator", Batch: 12, Tier: "9-2", [In("Dark Matter Crystal", 6), In("Crystal Oscillator", 1), In("Alclad Aluminum Sheet", 9), In("Excited Photonic Matter", 25), Out("Superposition Oscillator", 1), Out("Dark Matter Residue", 25)], AveragePower: -1000, MinPower: -2000),
        new(322, "Synthetic Power Shard",    Batch: 12, Tier: "9-2", [In("Time Crystal", 2), In("Dark Matter Crystal", 2), In("Quartz Crystal", 12), In("Excited Photonic Matter", 12), Out("Power Shard", 1), Out("Dark Matter Residue", 12)], AveragePower: -1000, MinPower: -2000),
        new(330, "Ficsonium Fuel Rod",       Batch: 24, Tier: "9-5", [In("Ficsonium", 2), In("Electromagnetic Control Rod", 2), In("Ficsite Trigon", 40), In("Excited Photonic Matter", 20), Out("Ficsonium Fuel Rod", 1), Out("Dark Matter Residue", 20)], AveragePower: -1000, MinPower: -2000),
    ];
}
