// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class QuartzCrystal : RecipeBase
{
    public override int SortIndex => 80;
    public override string RecipeName => "Quartz Crystal";
    public override string Machine => "Constructor";
    public override string BatchTime => "8";
    public override string Tier => "0-5";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Raw Quartz", Amount = "-5" },
        new() { Part = "Quartz Crystal", Amount = "3" },
    ];
}
