// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class Quickwire : RecipeBase
{
    public override int SortIndex => 189;
    public override string RecipeName => "Quickwire";
    public override string Machine => "Constructor";
    public override string BatchTime => "5";
    public override string Tier => "5-5";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Caterium Ingot", Amount = "-1" },
        new() { Part = "Quickwire", Amount = "5" },
    ];
}
