// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class ReanimatedSAM : RecipeBase
{
    public override int SortIndex => 286;
    public override string RecipeName => "Reanimated SAM";
    public override string Machine => "Constructor";
    public override string BatchTime => "2";
    public override string Tier => "9-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "SAM", Amount = "-4" },
        new() { Part = "Reanimated SAM", Amount = "1" },
    ];
}
