// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class ReinforcedIronPlate : RecipeBase
{
    public override int SortIndex => 56;
    public override string RecipeName => "Reinforced Iron Plate";
    public override string Machine => "Assembler";
    public override string BatchTime => "12";
    public override string Tier => "0-3";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Iron Plate", Amount = "-6" },
        new() { Part = "Screw", Amount = "-12" },
        new() { Part = "Reinforced Iron Plate", Amount = "1" },
    ];
}
