// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class ResidualRubber : RecipeBase
{
    public override int SortIndex => 136;
    public override string RecipeName => "Residual Rubber";
    public override string Machine => "Refinery";
    public override string BatchTime => "6";
    public override string Tier => "5-2";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Polymer Resin", Amount = "-4" },
        new() { Part = "Water", Amount = "-4" },
        new() { Part = "Rubber", Amount = "2" },
    ];
}
