// <auto-generated>
// Generated by Ficsit.Schematics.CatalogGenerator from Docs/en-US.json — do not edit.
// Regenerate with: dotnet run --project Ficsit.Schematics.CatalogGenerator -- --write
// </auto-generated>
namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

/// <summary>Recipes that run on the Resource Well Extractor.</summary>
public sealed class ResourceWellExtractorRecipes : RecipeModule
{
    protected override string Machine => "Resource Well Extractor";

    protected override IReadOnlyList<Recipe> Recipes =>
    [
        new(244, "Nitrogen Gas", Batch: 60, Tier: "8-3", [Out("Nitrogen Gas", 60)]),
        new(245, "Oil Well",     Batch: 60, Tier: "8-3", [Out("Crude Oil", 60)]),
        new(249, "Well Water",   Batch: 60, Tier: "8-3", [Out("Water", 60)]),
    ];
}
