// <auto-generated>
// Generated by Ficsit.Schematics.CatalogGenerator from Docs/en-US.json — do not edit.
// Regenerate with: dotnet run --project Ficsit.Schematics.CatalogGenerator -- --write
// </auto-generated>
namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

/// <summary>Recipes that run on the Resource Well Pressurizer.</summary>
public sealed class ResourceWellPressurizerRecipes : RecipeModule
{
    protected override string Machine => "Resource Well Pressurizer";

    protected override IReadOnlyList<Recipe> Recipes =>
    [
        new(247, "Resource Well Pressurizer", Batch: 1, Tier: "8-3", []),
    ];
}
