// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class RifleAmmo : RecipeBase
{
    public override int SortIndex => 134;
    public override string RecipeName => "Rifle Ammo";
    public override string Machine => "Assembler";
    public override string BatchTime => "12";
    public override string Tier => "5-2";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Copper Sheet", Amount = "-3" },
        new() { Part = "Smokeless Powder", Amount = "-2" },
        new() { Part = "Rifle Ammo", Amount = "15" },
    ];
}
