// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class RigorMotor : RecipeBase
{
    public override int SortIndex => 130;
    public override string RecipeName => "Rigor Motor";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "48";
    public override string Tier => "6-1";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Rotor", Amount = "-3" },
        new() { Part = "Stator", Amount = "-3" },
        new() { Part = "Crystal Oscillator", Amount = "-1" },
        new() { Part = "Motor", Amount = "6" },
    ];
}
