// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class Screw : RecipeBase
{
    public override int SortIndex => 43;
    public override string RecipeName => "Screw";
    public override string Machine => "Constructor";
    public override string BatchTime => "6";
    public override string Tier => "0-3";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Iron Rod", Amount = "-1" },
        new() { Part = "Screw", Amount = "4" },
    ];
}
