// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class ShatterRebar : RecipeBase
{
    public override int SortIndex => 90;
    public override string RecipeName => "Shatter Rebar";
    public override string Machine => "Assembler";
    public override string BatchTime => "12";
    public override string Tier => "2-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Iron Rebar", Amount = "-2" },
        new() { Part = "Quartz Crystal", Amount = "-3" },
        new() { Part = "Shatter Rebar", Amount = "1" },
    ];
}
