// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class SiliconCircuitBoard : RecipeBase
{
    public override int SortIndex => 142;
    public override string RecipeName => "Silicon Circuit Board";
    public override string Machine => "Assembler";
    public override string BatchTime => "24";
    public override string Tier => "5-2";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Copper Sheet", Amount = "-11" },
        new() { Part = "Silica", Amount = "-11" },
        new() { Part = "Circuit Board", Amount = "5" },
    ];
}
