// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class SiliconHighSpeedConnector : RecipeBase
{
    public override int SortIndex => 205;
    public override string RecipeName => "Silicon High-Speed Connector";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "40";
    public override string Tier => "6-1";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Quickwire", Amount = "-60" },
        new() { Part = "Silica", Amount = "-25" },
        new() { Part = "Circuit Board", Amount = "-2" },
        new() { Part = "High-Speed Connector", Amount = "2" },
    ];
}
