// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class SmartPlating : RecipeBase
{
    public override int SortIndex => 94;
    public override string RecipeName => "Smart Plating";
    public override string Machine => "Assembler";
    public override string BatchTime => "30";
    public override string Tier => "2-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Reinforced Iron Plate", Amount = "-1" },
        new() { Part = "Rotor", Amount = "-1" },
        new() { Part = "Smart Plating", Amount = "1" },
    ];
}
