// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class SpaceElevatorPhase4 : RecipeBase
{
    public override int SortIndex => 276;
    public override string RecipeName => "Space Elevator Phase 4";
    public override string Machine => "Space Elevator";
    public override string BatchTime => "60";
    public override string Tier => "8-5";
    public override string? SpaceElevatorMultiplier => "True";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Assembly Director System", Amount = "-500" },
        new() { Part = "Magnetic Field Generator", Amount = "-500" },
        new() { Part = "Nuclear Pasta", Amount = "-100" },
        new() { Part = "Thermal Propulsion Rocket", Amount = "-250" },
    ];
}
