// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class SpaceElevatorPhase2 : RecipeBase
{
    public override int SortIndex => 127;
    public override string RecipeName => "Space Elevator Phase 2";
    public override string Machine => "Space Elevator";
    public override string BatchTime => "60";
    public override string Tier => "4-3";
    public override string? SpaceElevatorMultiplier => "True";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Smart Plating", Amount = "-1000" },
        new() { Part = "Versatile Framework", Amount = "-1000" },
        new() { Part = "Automated Wiring", Amount = "-100" },
    ];
}
