// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class SpaceElevatorPhase5 : RecipeBase
{
    public override int SortIndex => 312;
    public override string RecipeName => "Space Elevator Phase 5";
    public override string Machine => "Space Elevator";
    public override string BatchTime => "60";
    public override string Tier => "9-4";
    public override string? SpaceElevatorMultiplier => "True";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Nuclear Pasta", Amount = "-1000" },
        new() { Part = "Biochemical Sculptor", Amount = "-1000" },
        new() { Part = "AI Expansion Server", Amount = "-256" },
        new() { Part = "Ballistic Warp Drive", Amount = "-200" },
    ];
}
