// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class SpaceElevatorPhase1 : RecipeBase
{
    public override int SortIndex => 95;
    public override string RecipeName => "Space Elevator Phase 1";
    public override string Machine => "Space Elevator";
    public override string BatchTime => "60";
    public override string Tier => "2-1";
    public override string? SpaceElevatorMultiplier => "True";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Smart Plating", Amount = "-50" },
    ];
}
