// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class Stator : RecipeBase
{
    public override int SortIndex => 122;
    public override string RecipeName => "Stator";
    public override string Machine => "Assembler";
    public override string BatchTime => "12";
    public override string Tier => "4-3";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Steel Pipe", Amount = "-3" },
        new() { Part = "Wire", Amount = "-8" },
        new() { Part = "Stator", Amount = "1" },
    ];
}
