// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class SteelRotor : RecipeBase
{
    public override int SortIndex => 89;
    public override string RecipeName => "Steel Rotor";
    public override string Machine => "Assembler";
    public override string BatchTime => "12";
    public override string Tier => "3-3";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Steel Pipe", Amount = "-2" },
        new() { Part = "Wire", Amount = "-6" },
        new() { Part = "Rotor", Amount = "1" },
    ];
}
