// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class SteelCanister : RecipeBase
{
    public override int SortIndex => 161;
    public override string RecipeName => "Steel Canister";
    public override string Machine => "Constructor";
    public override string BatchTime => "6";
    public override string Tier => "5-4";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Steel Ingot", Amount = "-4" },
        new() { Part = "Empty Canister", Amount = "4" },
    ];
}
