// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class SteelBeam : RecipeBase
{
    public override int SortIndex => 115;
    public override string RecipeName => "Steel Beam";
    public override string Machine => "Constructor";
    public override string BatchTime => "4";
    public override string Tier => "3-3";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Steel Ingot", Amount = "-4" },
        new() { Part = "Steel Beam", Amount = "1" },
    ];
}
