// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class SteelRod : RecipeBase
{
    public override int SortIndex => 23;
    public override string RecipeName => "Steel Rod";
    public override string Machine => "Constructor";
    public override string BatchTime => "5";
    public override string Tier => "3-3";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Steel Ingot", Amount = "-1" },
        new() { Part = "Iron Rod", Amount = "4" },
    ];
}
