// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class SteeledFrame : RecipeBase
{
    public override int SortIndex => 93;
    public override string RecipeName => "Steeled Frame";
    public override string Machine => "Assembler";
    public override string BatchTime => "60";
    public override string Tier => "3-3";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Reinforced Iron Plate", Amount = "-2" },
        new() { Part = "Steel Pipe", Amount = "-10" },
        new() { Part = "Modular Frame", Amount = "3" },
    ];
}
