// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class StitchedIronPlate : RecipeBase
{
    public override int SortIndex => 58;
    public override string RecipeName => "Stitched Iron Plate";
    public override string Machine => "Assembler";
    public override string BatchTime => "32";
    public override string Tier => "2-1";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Iron Plate", Amount = "-10" },
        new() { Part = "Wire", Amount = "-20" },
        new() { Part = "Reinforced Iron Plate", Amount = "3" },
    ];
}
