// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class StunRebar : RecipeBase
{
    public override int SortIndex => 195;
    public override string RecipeName => "Stun Rebar";
    public override string Machine => "Assembler";
    public override string BatchTime => "6";
    public override string Tier => "5-5";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Iron Rebar", Amount = "-1" },
        new() { Part = "Quickwire", Amount = "-5" },
        new() { Part = "Stun Rebar", Amount = "1" },
    ];
}
