// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class SweetFireworks : RecipeBase
{
    public override int SortIndex => 326;
    public override string RecipeName => "Sweet Fireworks";
    public override string Machine => "Assembler";
    public override string BatchTime => "24";
    public override string Tier => "2-1";
    public override bool Ficsmas => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "FICSMAS Tree Branch", Amount = "-6" },
        new() { Part = "Candy Cane", Amount = "-3" },
        new() { Part = "Sweet Fireworks", Amount = "1" },
    ];
}
