// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class SyntheticPowerShard : RecipeBase
{
    public override int SortIndex => 309;
    public override string RecipeName => "Synthetic Power Shard";
    public override string Machine => "Quantum Encoder";
    public override string BatchTime => "12";
    public override string Tier => "9-2";
    public override string? AveragePower => "-1000";
    public override string? MinPower => "-2000";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Time Crystal", Amount = "-2" },
        new() { Part = "Dark Matter Crystal", Amount = "-2" },
        new() { Part = "Quartz Crystal", Amount = "-12" },
        new() { Part = "Excited Photonic Matter", Amount = "-12" },
        new() { Part = "Power Shard", Amount = "1" },
        new() { Part = "Dark Matter Residue", Amount = "12" },
    ];
}
