// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class TemperedCateriumIngot : RecipeBase
{
    public override int SortIndex => 193;
    public override string RecipeName => "Tempered Caterium Ingot";
    public override string Machine => "Foundry";
    public override string BatchTime => "8";
    public override string Tier => "5-5";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Caterium Ore", Amount = "-6" },
        new() { Part = "Petroleum Coke", Amount = "-2" },
        new() { Part = "Caterium Ingot", Amount = "3" },
    ];
}
