// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class TemperedCopperIngot : RecipeBase
{
    public override int SortIndex => 33;
    public override string RecipeName => "Tempered Copper Ingot";
    public override string Machine => "Foundry";
    public override string BatchTime => "12";
    public override string Tier => "5-2";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Copper Ore", Amount = "-5" },
        new() { Part = "Petroleum Coke", Amount = "-8" },
        new() { Part = "Copper Ingot", Amount = "12" },
    ];
}
