// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class ThermalPropulsionRocket : RecipeBase
{
    public override int SortIndex => 269;
    public override string RecipeName => "Thermal Propulsion Rocket";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "120";
    public override string Tier => "8-4";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Modular Engine", Amount = "-5" },
        new() { Part = "Turbo Motor", Amount = "-2" },
        new() { Part = "Cooling System", Amount = "-6" },
        new() { Part = "Fused Modular Frame", Amount = "-2" },
        new() { Part = "Thermal Propulsion Rocket", Amount = "2" },
    ];
}
