// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class TurboElectricMotor : RecipeBase
{
    public override int SortIndex => 267;
    public override string RecipeName => "Turbo Electric Motor";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "64";
    public override string Tier => "8-4";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Motor", Amount = "-7" },
        new() { Part = "Radio Control Unit", Amount = "-9" },
        new() { Part = "Electromagnetic Control Rod", Amount = "-5" },
        new() { Part = "Rotor", Amount = "-7" },
        new() { Part = "Turbo Motor", Amount = "3" },
    ];
}
