// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class TurboPressureMotor : RecipeBase
{
    public override int SortIndex => 268;
    public override string RecipeName => "Turbo Pressure Motor";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "32";
    public override string Tier => "8-5";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Motor", Amount = "-4" },
        new() { Part = "Pressure Conversion Cube", Amount = "-1" },
        new() { Part = "Packaged Nitrogen Gas", Amount = "-24" },
        new() { Part = "Stator", Amount = "-8" },
        new() { Part = "Turbo Motor", Amount = "2" },
    ];
}
