// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class TurboHeavyFuel : RecipeBase
{
    public override int SortIndex => 187;
    public override string RecipeName => "Turbo Heavy Fuel";
    public override string Machine => "Refinery";
    public override string BatchTime => "8";
    public override string Tier => "5-4";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Heavy Oil Residue", Amount = "-5" },
        new() { Part = "Compacted Coal", Amount = "-4" },
        new() { Part = "Turbofuel", Amount = "4" },
    ];
}
