// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class TurboMotor : RecipeBase
{
    public override int SortIndex => 266;
    public override string RecipeName => "Turbo Motor";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "32";
    public override string Tier => "8-4";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Cooling System", Amount = "-4" },
        new() { Part = "Radio Control Unit", Amount = "-2" },
        new() { Part = "Motor", Amount = "-4" },
        new() { Part = "Rubber", Amount = "-24" },
        new() { Part = "Turbo Motor", Amount = "1" },
    ];
}
