// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class Turbofuel : RecipeBase
{
    public override int SortIndex => 184;
    public override string RecipeName => "Turbofuel";
    public override string Machine => "Refinery";
    public override string BatchTime => "16";
    public override string Tier => "5-4";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Fuel", Amount = "-6" },
        new() { Part = "Compacted Coal", Amount = "-4" },
        new() { Part = "Turbofuel", Amount = "5" },
    ];
}
