// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class TurboRifleAmmo : RecipeBase
{
    public override int SortIndex => 222;
    public override string RecipeName => "Turbo Rifle Ammo";
    public override string Machine => "Blender";
    public override string BatchTime => "12";
    public override string Tier => "7-5";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Rifle Ammo", Amount = "-25" },
        new() { Part = "Aluminum Casing", Amount = "-3" },
        new() { Part = "Turbofuel", Amount = "-3" },
        new() { Part = "Turbo Rifle Ammo", Amount = "50" },
    ];
}
