// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class UnpackageIonizedFuel : RecipeBase
{
    public override int SortIndex => 174;
    public override string RecipeName => "Unpackage Ionized Fuel";
    public override string Machine => "Packager";
    public override string BatchTime => "3";
    public override string Tier => "5-4";
    public override bool IgnoreInputMultiplier => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Packaged Ionized Fuel", Amount = "-2" },
        new() { Part = "Ionized Fuel", Amount = "4" },
        new() { Part = "Empty Fluid Tank", Amount = "2" },
    ];
}
