// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class UnpackageHeavyOilResidue : RecipeBase
{
    public override int SortIndex => 157;
    public override string RecipeName => "Unpackage Heavy Oil Residue";
    public override string Machine => "Packager";
    public override string BatchTime => "6";
    public override string Tier => "5-4";
    public override bool IgnoreInputMultiplier => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Packaged Heavy Oil Residue", Amount = "-2" },
        new() { Part = "Heavy Oil Residue", Amount = "2" },
        new() { Part = "Empty Canister", Amount = "2" },
    ];
}
