// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class UnpackageFuel : RecipeBase
{
    public override int SortIndex => 156;
    public override string RecipeName => "Unpackage Fuel";
    public override string Machine => "Packager";
    public override string BatchTime => "2";
    public override string Tier => "5-4";
    public override bool IgnoreInputMultiplier => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Packaged Fuel", Amount = "-2" },
        new() { Part = "Fuel", Amount = "2" },
        new() { Part = "Empty Canister", Amount = "2" },
    ];
}
