// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class UnpackageSulfuricAcid : RecipeBase
{
    public override int SortIndex => 244;
    public override string RecipeName => "Unpackage Sulfuric Acid";
    public override string Machine => "Packager";
    public override string BatchTime => "1";
    public override string Tier => "7-5";
    public override bool IgnoreInputMultiplier => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Packaged Sulfuric Acid", Amount = "-1" },
        new() { Part = "Sulfuric Acid", Amount = "1" },
        new() { Part = "Empty Canister", Amount = "1" },
    ];
}
