// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class UnpackageRocketFuel : RecipeBase
{
    public override int SortIndex => 180;
    public override string RecipeName => "Unpackage Rocket Fuel";
    public override string Machine => "Packager";
    public override string BatchTime => "1";
    public override string Tier => "5-4";
    public override bool IgnoreInputMultiplier => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Packaged Rocket Fuel", Amount = "-1" },
        new() { Part = "Rocket Fuel", Amount = "2" },
        new() { Part = "Empty Fluid Tank", Amount = "1" },
    ];
}
