// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class UnpackageAluminaSolution : RecipeBase
{
    public override int SortIndex => 230;
    public override string RecipeName => "Unpackage Alumina Solution";
    public override string Machine => "Packager";
    public override string BatchTime => "1";
    public override string Tier => "7-1";
    public override bool IgnoreInputMultiplier => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Packaged Alumina Solution", Amount = "-2" },
        new() { Part = "Alumina Solution", Amount = "2" },
        new() { Part = "Empty Canister", Amount = "2" },
    ];
}
