// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class UraniumFuelUnit : RecipeBase
{
    public override int SortIndex => 253;
    public override string RecipeName => "Uranium Fuel Unit";
    public override string Machine => "Manufacturer";
    public override string BatchTime => "300";
    public override string Tier => "8-2";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Encased Uranium Cell", Amount = "-100" },
        new() { Part = "Electromagnetic Control Rod", Amount = "-10" },
        new() { Part = "Crystal Oscillator", Amount = "-3" },
        new() { Part = "Rotor", Amount = "-10" },
        new() { Part = "Uranium Fuel Rod", Amount = "3" },
    ];
}
