// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class Water : RecipeBase
{
    public override int SortIndex => 8;
    public override string RecipeName => "Water";
    public override string Machine => "Water Extractor";
    public override string BatchTime => "60";
    public override string Tier => "3-1";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Water", Amount = "120" },
    ];
}
