// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class WetConcrete : RecipeBase
{
    public override int SortIndex => 55;
    public override string RecipeName => "Wet Concrete";
    public override string Machine => "Refinery";
    public override string BatchTime => "3";
    public override string Tier => "5-2";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Limestone", Amount = "-6" },
        new() { Part = "Water", Amount = "-5" },
        new() { Part = "Concrete", Amount = "4" },
    ];
}
