// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;

public sealed class WoodBiomassBurner : RecipeBase
{
    public override int SortIndex => 29;
    public override string RecipeName => "Wood Biomass Burner";
    public override string Machine => "Biomass Burner";
    public override string BatchTime => "10/3";
    public override string Tier => "0-6";
    public override bool IgnoreInputMultiplier => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Wood", Amount = "-1" },
    ];
}
