# Regenerates the C# game-data catalog (one class per machine/part/recipe) from
# the canonical JSON in this folder. Run from the repo root or anywhere:
#   pwsh tools/generate-catalog.ps1
# The app never reads the JSON at runtime — it exists only as generator input.

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path $PSScriptRoot -Parent
$jsonPath = Join-Path $PSScriptRoot 'game_data.json'
$catalogRoot = Join-Path $repoRoot 'Ficsit.Schematics.Core\GameData\Catalog'

$data = Get-Content $jsonPath -Raw | ConvertFrom-Json

function Sanitize([string]$name) {
    $tokens = [regex]::Split($name, '[^A-Za-z0-9]+') | Where-Object { $_ }
    $result = ($tokens | ForEach-Object { $_.Substring(0, 1).ToUpper() + $_.Substring(1) }) -join ''
    if ($result -match '^\d') { $result = '_' + $result }
    return $result
}

function Esc([string]$value) {
    return $value.Replace('\', '\\').Replace('"', '\"')
}

function Prop($obj, [string]$name) {
    $p = $obj.PSObject.Properties[$name]
    if ($null -ne $p) { return $p.Value } else { return $null }
}

function New-CatalogDir([string]$sub) {
    $dir = Join-Path $catalogRoot $sub
    if (Test-Path $dir) { Remove-Item "$dir\*.cs" -Force }
    New-Item -ItemType Directory -Force $dir | Out-Null
    return $dir
}

function Save-Class([string]$dir, [string]$className, [string]$body) {
    $header = "// <auto-generated>`n" +
        "//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.`n" +
        "//     Do not edit by hand - rerun the script after changing the source data.`n" +
        "// </auto-generated>`n" +
        "#nullable enable`n`n"
    [System.IO.File]::WriteAllText((Join-Path $dir "$className.cs"), $header + $body,
        [System.Text.UTF8Encoding]::new($false))
}

function Unique([hashtable]$used, [string]$name) {
    $candidate = $name
    $n = 2
    while ($used.ContainsKey($candidate)) { $candidate = "$name$n"; $n++ }
    $used[$candidate] = $true
    return $candidate
}

# ------------------------------------------------------------------ machines
$dir = New-CatalogDir 'Machines'
$used = @{}
for ($i = 0; $i -lt $data.Machines.Count; $i++) {
    $m = $data.Machines[$i]
    $cls = Unique $used (Sanitize $m.Name)
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine('namespace Ficsit.Schematics.Core.GameData.Catalog.Machines;')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("public sealed class $cls : MachineBase")
    [void]$sb.AppendLine('{')
    [void]$sb.AppendLine("    public override int SortIndex => $i;")
    [void]$sb.AppendLine("    public override string MachineName => `"$(Esc $m.Name)`";")
    [void]$sb.AppendLine("    public override string Tier => `"$(Esc $m.Tier)`";")
    foreach ($field in 'AveragePower', 'MinPower', 'BasePower', 'BasePowerBoost', 'FueledBasePowerBoost', 'OverclockPowerExponent', 'ProductionShardMultiplier', 'ProductionShardPowerExponent') {
        $v = Prop $m $field
        if ($null -ne $v -and "$v" -ne '') {
            [void]$sb.AppendLine("    public override string? $field => `"$(Esc "$v")`";")
        }
    }
    $shards = Prop $m 'MaxProductionShards'
    if ($shards) { [void]$sb.AppendLine("    public override int MaxProductionShards => $shards;") }
    $cost = Prop $m 'Cost'
    if ($cost -and $cost.Count -gt 0) {
        [void]$sb.AppendLine('')
        [void]$sb.AppendLine('    public override IReadOnlyList<CostEntry> Cost =>')
        [void]$sb.AppendLine('    [')
        foreach ($c in $cost) {
            [void]$sb.AppendLine("        new() { Part = `"$(Esc $c.Part)`", Amount = `"$(Esc "$($c.Amount)")`" },")
        }
        [void]$sb.AppendLine('    ];')
    }
    [void]$sb.AppendLine('}')
    Save-Class $dir $cls $sb.ToString()
}
"machines: $($data.Machines.Count)"

# ------------------------------------------------------------- multimachines
$dir = New-CatalogDir 'MultiMachines'
$used = @{}
for ($i = 0; $i -lt $data.MultiMachines.Count; $i++) {
    $m = $data.MultiMachines[$i]
    $cls = Unique $used ((Sanitize $m.Name) + 'Family')
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine('namespace Ficsit.Schematics.Core.GameData.Catalog.MultiMachines;')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("public sealed class $cls : MultiMachineBase")
    [void]$sb.AppendLine('{')
    [void]$sb.AppendLine("    public override int SortIndex => $i;")
    [void]$sb.AppendLine("    public override string FamilyName => `"$(Esc $m.Name)`";")
    if ((Prop $m 'ShowPpm') -eq $true) { [void]$sb.AppendLine('    public override bool ShowPpm => true;') }
    if ((Prop $m 'AutoRound') -eq $false) { [void]$sb.AppendLine('    public override bool AutoRound => false;') }
    $defaultMax = Prop $m 'DefaultMax'
    if ($defaultMax) { [void]$sb.AppendLine("    public override string DefaultMax => `"$(Esc "$defaultMax")`";") }
    $variants = Prop $m 'Machines'
    if ($variants -and $variants.Count -gt 0) {
        [void]$sb.AppendLine('')
        [void]$sb.AppendLine('    public override IReadOnlyList<MultiMachineVariant> Machines =>')
        [void]$sb.AppendLine('    [')
        foreach ($v in $variants) {
            $parts = @("Name = `"$(Esc $v.Name)`"")
            $ratio = Prop $v 'PartsRatio'
            if ($null -ne $ratio) { $parts += "PartsRatio = `"$(Esc "$ratio")`"" }
            if ((Prop $v 'Default') -eq $true) { $parts += 'Default = true' }
            [void]$sb.AppendLine("        new() { $($parts -join ', ') },")
        }
        [void]$sb.AppendLine('    ];')
    }
    $capacities = Prop $m 'Capacities'
    if ($capacities -and $capacities.Count -gt 0) {
        [void]$sb.AppendLine('')
        [void]$sb.AppendLine('    public override IReadOnlyList<MultiMachineCapacity> Capacities =>')
        [void]$sb.AppendLine('    [')
        foreach ($c in $capacities) {
            $parts = @("Name = `"$(Esc $c.Name)`"")
            $ratio = Prop $c 'PartsRatio'
            if ($null -ne $ratio) { $parts += "PartsRatio = `"$(Esc "$ratio")`"" }
            $power = Prop $c 'PowerRatio'
            if ($null -ne $power) { $parts += "PowerRatio = `"$(Esc "$power")`"" }
            if ((Prop $c 'Default') -eq $true) { $parts += 'Default = true' }
            $color = Prop $c 'Color'
            if ($null -ne $color) { $parts += "Color = $color" }
            [void]$sb.AppendLine("        new() { $($parts -join ', ') },")
        }
        [void]$sb.AppendLine('    ];')
    }
    [void]$sb.AppendLine('}')
    Save-Class $dir $cls $sb.ToString()
}
"multimachines: $($data.MultiMachines.Count)"

# --------------------------------------------------------------------- parts
$dir = New-CatalogDir 'Parts'
$used = @{}
for ($i = 0; $i -lt $data.Parts.Count; $i++) {
    $p = $data.Parts[$i]
    $cls = Unique $used (Sanitize $p.Name)
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine('namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("public sealed class $cls : PartBase")
    [void]$sb.AppendLine('{')
    [void]$sb.AppendLine("    public override int SortIndex => $i;")
    [void]$sb.AppendLine("    public override string PartName => `"$(Esc $p.Name)`";")
    [void]$sb.AppendLine("    public override string Tier => `"$(Esc $p.Tier)`";")
    $sink = Prop $p 'SinkPoints'
    if ($sink) { [void]$sb.AppendLine("    public override int SinkPoints => $sink;") }
    if ((Prop $p 'Fluid') -eq $true) { [void]$sb.AppendLine('    public override bool Fluid => true;') }
    [void]$sb.AppendLine('}')
    Save-Class $dir $cls $sb.ToString()
}
"parts: $($data.Parts.Count)"

# ------------------------------------------------------------------- recipes
$dir = New-CatalogDir 'Recipes'
$used = @{}
for ($i = 0; $i -lt $data.Recipes.Count; $i++) {
    $r = $data.Recipes[$i]
    $cls = Unique $used (Sanitize $r.Name)
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine('namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes;')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("public sealed class $cls : RecipeBase")
    [void]$sb.AppendLine('{')
    [void]$sb.AppendLine("    public override int SortIndex => $i;")
    [void]$sb.AppendLine("    public override string RecipeName => `"$(Esc $r.Name)`";")
    [void]$sb.AppendLine("    public override string Machine => `"$(Esc $r.Machine)`";")
    [void]$sb.AppendLine("    public override string BatchTime => `"$(Esc "$($r.BatchTime)")`";")
    $tier = Prop $r 'Tier'
    if ($tier) { [void]$sb.AppendLine("    public override string Tier => `"$(Esc $tier)`";") }
    if ((Prop $r 'Alternate') -eq $true) { [void]$sb.AppendLine('    public override bool Alternate => true;') }
    if ((Prop $r 'Ficsmas') -eq $true) { [void]$sb.AppendLine('    public override bool Ficsmas => true;') }
    foreach ($field in 'AveragePower', 'MinPower', 'SpaceElevatorMultiplier') {
        $v = Prop $r $field
        if ($null -ne $v -and "$v" -ne '') {
            [void]$sb.AppendLine("    public override string? $field => `"$(Esc "$v")`";")
        }
    }
    if ((Prop $r 'IgnoreInputMultiplier') -eq $true) { [void]$sb.AppendLine('    public override bool IgnoreInputMultiplier => true;') }
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('    public override IReadOnlyList<RecipePart> Parts =>')
    if ($r.Parts -and $r.Parts.Count -gt 0) {
        [void]$sb.AppendLine('    [')
        foreach ($p in $r.Parts) {
            [void]$sb.AppendLine("        new() { Part = `"$(Esc $p.Part)`", Amount = `"$(Esc "$($p.Amount)")`" },")
        }
        [void]$sb.AppendLine('    ];')
    }
    else {
        [void]$sb.AppendLine('    [')
        [void]$sb.AppendLine('    ];')
    }
    [void]$sb.AppendLine('}')
    Save-Class $dir $cls $sb.ToString()
}
"recipes: $($data.Recipes.Count)"
