# Regenerates the C# game-data catalog (one class per machine/part/recipe) from
# the canonical JSON in this folder. Run from the repo root or anywhere:
#   pwsh tools/generate-catalog.ps1
# The app never reads the JSON at runtime — it exists only as generator input.

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path $PSScriptRoot -Parent
$jsonPath = Join-Path $PSScriptRoot 'game_data.json'
$catalogRoot = Join-Path $repoRoot 'Ficsit.Schematics.Core\GameData\Catalog'

$data = Get-Content $jsonPath -Raw | ConvertFrom-Json

function Sanitize([string]$name) {
    $tokens = [regex]::Split($name, '[^A-Za-z0-9]+') | Where-Object { $_ }
    $result = ($tokens | ForEach-Object { $_.Substring(0, 1).ToUpper() + $_.Substring(1) }) -join ''
    if ($result -match '^\d') { $result = '_' + $result }
    return $result
}

function Esc([string]$value) {
    return $value.Replace('\', '\\').Replace('"', '\"')
}

function Prop($obj, [string]$name) {
    $p = $obj.PSObject.Properties[$name]
    if ($null -ne $p) { return $p.Value } else { return $null }
}

function New-CatalogDir([string]$sub) {
    $dir = Join-Path $catalogRoot $sub
    if (Test-Path $dir) {
        # Remove all generated .cs files recursively
        Get-ChildItem $dir -Filter '*.cs' -Recurse | Remove-Item -Force
        # Remove empty subdirectories
        Get-ChildItem $dir -Directory -Recurse | Sort-Object -Property FullName -Descending |
            Where-Object { (Get-ChildItem $_.FullName).Count -eq 0 } | Remove-Item -Force
    }
    New-Item -ItemType Directory -Force $dir | Out-Null
    return $dir
}

function New-SubDir([string]$parent, [string]$sub) {
    $dir = Join-Path $parent $sub
    New-Item -ItemType Directory -Force $dir | Out-Null
    return $dir
}

function Save-Class([string]$dir, [string]$className, [string]$body) {
    $header = "// <auto-generated>`n" +
        "//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.`n" +
        "//     Do not edit by hand - rerun the script after changing the source data.`n" +
        "// </auto-generated>`n" +
        "#nullable enable`n`n"
    [System.IO.File]::WriteAllText((Join-Path $dir "$className.cs"), $header + $body,
        [System.Text.UTF8Encoding]::new($false))
}

function Unique([hashtable]$used, [string]$name) {
    $candidate = $name
    $n = 2
    while ($used.ContainsKey($candidate)) { $candidate = "$name$n"; $n++ }
    $used[$candidate] = $true
    return $candidate
}

# Map category name -> base class name
$categoryBase = @{
    'Extractors'  = 'ExtractorBase'
    'Generators'  = 'GeneratorBase'
    'Smelting'    = 'SmelterBase'
    'Production'  = 'ProductionBase'
    'Storage'     = 'StorageBase'
    'Special'     = 'SpecialBase'
}

# Map category name -> namespace subfolder name
$categoryFolder = @{
    'Extractors'  = 'Extractors'
    'Generators'  = 'Generators'
    'Smelting'    = 'Smelting'
    'Production'  = 'Production'
    'Storage'     = 'Storage'
    'Special'     = 'Special'
}

# Which base classes have family surface (FamilySortIndex, ShowPpm, etc.)
$familyBases = @('ExtractorBase', 'GeneratorBase', 'StorageBase', 'SpecialBase')

# ------------------------------------------------------------------ machines
# First, build lookup structures.

# Index machines by name
$machineByName = @{}
for ($i = 0; $i -lt $data.Machines.Count; $i++) {
    $m = $data.Machines[$i]
    $machineByName[$m.Name] = @{ Machine = $m; SortIndex = $i }
}

# Index multimachines by name; also build reverse map: variant machine name -> family name
$familyByName   = @{}   # MultiMachine.Name -> MultiMachine object
$familySortIdx  = @{}   # MultiMachine.Name -> its index in MultiMachines array
$variantOfFamily = @{}  # machine variant name -> family name (for Miner Mk.1/2/3 -> "Miner")

for ($i = 0; $i -lt $data.MultiMachines.Count; $i++) {
    $mm = $data.MultiMachines[$i]
    $familyByName[$mm.Name] = $mm
    $familySortIdx[$mm.Name] = $i
    $variants = Prop $mm 'Machines'
    if ($variants -and $variants.Count -gt 0) {
        foreach ($v in $variants) {
            $variantOfFamily[$v.Name] = $mm.Name
        }
    }
}

# Determine which machine names have already been emitted (to avoid duplicates
# for Miner Mk.1/2/3 which collapse into a single Miner class)
$emittedFamilies = @{}   # family name -> $true (prevents emitting Miner twice)
$skippedMachines = @{}   # variant machine names that are subsumed by their family

foreach ($variantName in $variantOfFamily.Keys) {
    $skippedMachines[$variantName] = $true
}

# ------------------------------------------------------------------ machines section
$machinesRoot = New-CatalogDir 'Machines'

# Also delete legacy MultiMachines folder if it exists
$multiMachinesDir = Join-Path $catalogRoot 'MultiMachines'
if (Test-Path $multiMachinesDir) {
    Remove-Item $multiMachinesDir -Recurse -Force
    "Deleted MultiMachines/ folder"
}

$used = @{}
$machineCount = 0

for ($i = 0; $i -lt $data.Machines.Count; $i++) {
    $m = $data.Machines[$i]
    $cat = Prop $m 'Category'
    if (-not $cat) { throw "Machine '$($m.Name)' has no Category in game_data.json." }
    if (-not $categoryBase.ContainsKey($cat)) { throw "Unknown category '$cat' on machine '$($m.Name)'." }

    $baseClass = $categoryBase[$cat]
    $folder = $categoryFolder[$cat]
    $catDir = New-SubDir $machinesRoot $folder
    $nsBase = "Ficsit.Schematics.Core.GameData.Catalog.Machines.$folder"

    if ($skippedMachines.ContainsKey($m.Name)) {
        # This machine is a variant inside a family (e.g. Miner Mk.2).
        # It will be emitted as part of the family class. Skip standalone.
        # Emit the family class when we encounter the FIRST variant.
        $familyName = $variantOfFamily[$m.Name]
        if ($emittedFamilies.ContainsKey($familyName)) { continue }
        $emittedFamilies[$familyName] = $true

        $mm = $familyByName[$familyName]
        $familyIdx = $familySortIdx[$familyName]
        $cls = Unique $used (Sanitize $familyName)

        # Collect per-variant machine data
        $variants = Prop $mm 'Machines'

        $sb = [System.Text.StringBuilder]::new()
        [void]$sb.AppendLine("namespace $nsBase;")
        [void]$sb.AppendLine('')
        [void]$sb.AppendLine("public sealed class $cls : $baseClass")
        [void]$sb.AppendLine('{')
        # SortIndex = first variant's SortIndex (for machine-list ordering)
        $firstVariantSortIdx = $machineByName[$variants[0].Name].SortIndex
        [void]$sb.AppendLine("    public override int SortIndex => $firstVariantSortIdx;")
        [void]$sb.AppendLine("    public override string MachineName => `"$(Esc $familyName)`";")
        # Tier from the first variant machine
        $firstMachine = $machineByName[$variants[0].Name].Machine
        [void]$sb.AppendLine("    public override string Tier => `"$(Esc $firstMachine.Tier)`";")

        # Family sort index
        if ($familyBases -contains $baseClass) {
            [void]$sb.AppendLine("    public override int FamilySortIndex => $familyIdx;")
        }

        # Family surface: ShowPpm, AutoRound, DefaultMax
        if ((Prop $mm 'ShowPpm') -eq $true)  { [void]$sb.AppendLine('    public override bool ShowPpm => true;') }
        if ((Prop $mm 'AutoRound') -eq $false) { [void]$sb.AppendLine('    public override bool AutoRound => false;') }
        $defaultMax = Prop $mm 'DefaultMax'
        if ($null -ne $defaultMax -and "$defaultMax" -ne '') {
            [void]$sb.AppendLine("    public override string DefaultMax => `"$(Esc "$defaultMax")`";")
        }

        # FamilyMachines (variant list)
        [void]$sb.AppendLine('')
        [void]$sb.AppendLine('    public override IReadOnlyList<MultiMachineVariant> FamilyMachines =>')
        [void]$sb.AppendLine('    [')
        foreach ($v in $variants) {
            $parts = @("Name = `"$(Esc $v.Name)`"")
            $ratio = Prop $v 'PartsRatio'
            if ($null -ne $ratio) { $parts += "PartsRatio = `"$(Esc "$ratio")`"" }
            if ((Prop $v 'Default') -eq $true) { $parts += 'Default = true' }
            [void]$sb.AppendLine("        new() { $($parts -join ', ') },")
        }
        [void]$sb.AppendLine('    ];')

        # FamilyCapacities
        $capacities = Prop $mm 'Capacities'
        if ($capacities -and $capacities.Count -gt 0) {
            [void]$sb.AppendLine('')
            [void]$sb.AppendLine('    public override IReadOnlyList<MultiMachineCapacity> FamilyCapacities =>')
            [void]$sb.AppendLine('    [')
            foreach ($c in $capacities) {
                $cparts = @("Name = `"$(Esc $c.Name)`"")
                $ratio = Prop $c 'PartsRatio'
                if ($null -ne $ratio) { $cparts += "PartsRatio = `"$(Esc "$ratio")`"" }
                $power = Prop $c 'PowerRatio'
                if ($null -ne $power) { $cparts += "PowerRatio = `"$(Esc "$power")`"" }
                if ((Prop $c 'Default') -eq $true) { $cparts += 'Default = true' }
                $color = Prop $c 'Color'
                if ($null -ne $color) { $cparts += "Color = $color" }
                [void]$sb.AppendLine("        new() { $($cparts -join ', ') },")
            }
            [void]$sb.AppendLine('    ];')
        }

        # ToIndexedMachineDefinitions: one per variant with its original SortIndex
        # so GameDataCatalog can restore the canonical interleaved ordering.
        [void]$sb.AppendLine('')
        [void]$sb.AppendLine('    public override IEnumerable<(int SortIndex, MachineDefinition Definition)> ToIndexedMachineDefinitions() =>')
        [void]$sb.AppendLine('    [')
        foreach ($v in $variants) {
            $vm = $machineByName[$v.Name]
            $vMachine = $vm.Machine
            $vIdx = $vm.SortIndex
            $vName = Esc $v.Name
            $vTier = Esc $vMachine.Tier

            # Build cost list
            $vCost = Prop $vMachine 'Cost'
            if ($vCost -and $vCost.Count -gt 0) {
                $costItems = ($vCost | ForEach-Object { "new() { Part = `"$(Esc $_.Part)`", Amount = `"$(Esc "$($_.Amount)")`" }" }) -join ', '
                $costExpr = "[$costItems]"
            } else {
                $costExpr = "[]"
            }

            # Power fields
            $powerParts = @()
            foreach ($field in 'AveragePower', 'MinPower', 'BasePower', 'BasePowerBoost', 'FueledBasePowerBoost', 'OverclockPowerExponent', 'ProductionShardMultiplier', 'ProductionShardPowerExponent') {
                $v2 = Prop $vMachine $field
                if ($null -ne $v2 -and "$v2" -ne '') {
                    $powerParts += "$field = `"$(Esc "$v2")`""
                }
            }
            $shards = Prop $vMachine 'MaxProductionShards'
            if ($shards) { $powerParts += "MaxProductionShards = $shards" }
            $powerParts += "Cost = $costExpr"

            [void]$sb.AppendLine("        ($vIdx, new() { Name = `"$vName`", Tier = `"$vTier`", $($powerParts -join ', ') }),")
        }
        [void]$sb.AppendLine('    ];')

        # ToFamilyDefinition
        [void]$sb.AppendLine('')
        [void]$sb.AppendLine("    public override MultiMachineDefinition ToFamilyDefinition() => new()")
        [void]$sb.AppendLine('    {')
        [void]$sb.AppendLine("        Name = `"$(Esc $familyName)`",")
        if ((Prop $mm 'ShowPpm') -eq $true)  { [void]$sb.AppendLine('        ShowPpm = true,') }
        if ((Prop $mm 'AutoRound') -eq $false) { [void]$sb.AppendLine('        AutoRound = false,') }
        if ($null -ne $defaultMax -and "$defaultMax" -ne '') {
            [void]$sb.AppendLine("        DefaultMax = `"$(Esc "$defaultMax")`",")
        }
        # Machines list for family def
        [void]$sb.AppendLine('        Machines =')
        [void]$sb.AppendLine('        [')
        foreach ($v in $variants) {
            $vparts = @("Name = `"$(Esc $v.Name)`"")
            $ratio = Prop $v 'PartsRatio'
            if ($null -ne $ratio) { $vparts += "PartsRatio = `"$(Esc "$ratio")`"" }
            if ((Prop $v 'Default') -eq $true) { $vparts += 'Default = true' }
            [void]$sb.AppendLine("            new() { $($vparts -join ', ') },")
        }
        [void]$sb.AppendLine('        ],')
        # Capacities list for family def
        if ($capacities -and $capacities.Count -gt 0) {
            [void]$sb.AppendLine('        Capacities =')
            [void]$sb.AppendLine('        [')
            foreach ($c in $capacities) {
                $cparts = @("Name = `"$(Esc $c.Name)`"")
                $ratio = Prop $c 'PartsRatio'
                if ($null -ne $ratio) { $cparts += "PartsRatio = `"$(Esc "$ratio")`"" }
                $power = Prop $c 'PowerRatio'
                if ($null -ne $power) { $cparts += "PowerRatio = `"$(Esc "$power")`"" }
                if ((Prop $c 'Default') -eq $true) { $cparts += 'Default = true' }
                $color = Prop $c 'Color'
                if ($null -ne $color) { $cparts += "Color = $color" }
                [void]$sb.AppendLine("            new() { $($cparts -join ', ') },")
            }
            [void]$sb.AppendLine('        ],')
        }
        [void]$sb.AppendLine('    };')

        [void]$sb.AppendLine('}')
        Save-Class $catDir $cls $sb.ToString()
        $machineCount++
        continue
    }

    # Check if this machine IS a family (self-referential: its name matches a MultiMachine name)
    $isSelfFamily = $familyByName.ContainsKey($m.Name)

    $cls = Unique $used (Sanitize $m.Name)
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine("namespace $nsBase;")
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("public sealed class $cls : $baseClass")
    [void]$sb.AppendLine('{')
    [void]$sb.AppendLine("    public override int SortIndex => $i;")
    [void]$sb.AppendLine("    public override string MachineName => `"$(Esc $m.Name)`";")
    [void]$sb.AppendLine("    public override string Tier => `"$(Esc $m.Tier)`";")

    if ($isSelfFamily) {
        $mm = $familyByName[$m.Name]
        $familyIdx = $familySortIdx[$m.Name]

        # Family sort index
        if ($familyBases -contains $baseClass) {
            [void]$sb.AppendLine("    public override int FamilySortIndex => $familyIdx;")
        }

        # Family surface
        if ((Prop $mm 'ShowPpm') -eq $true)  { [void]$sb.AppendLine('    public override bool ShowPpm => true;') }
        if ((Prop $mm 'AutoRound') -eq $false) { [void]$sb.AppendLine('    public override bool AutoRound => false;') }
        $defaultMax = Prop $mm 'DefaultMax'
        if ($null -ne $defaultMax -and "$defaultMax" -ne '') {
            [void]$sb.AppendLine("    public override string DefaultMax => `"$(Esc "$defaultMax")`";")
        }
    }

    # Standard machine fields
    foreach ($field in 'AveragePower', 'MinPower', 'BasePower', 'BasePowerBoost', 'FueledBasePowerBoost', 'OverclockPowerExponent', 'ProductionShardMultiplier', 'ProductionShardPowerExponent') {
        $v = Prop $m $field
        if ($null -ne $v -and "$v" -ne '') {
            [void]$sb.AppendLine("    public override string? $field => `"$(Esc "$v")`";")
        }
    }
    $shards = Prop $m 'MaxProductionShards'
    if ($shards) { [void]$sb.AppendLine("    public override int MaxProductionShards => $shards;") }
    $cost = Prop $m 'Cost'
    if ($cost -and $cost.Count -gt 0) {
        [void]$sb.AppendLine('')
        [void]$sb.AppendLine('    public override IReadOnlyList<CostEntry> Cost =>')
        [void]$sb.AppendLine('    [')
        foreach ($c in $cost) {
            [void]$sb.AppendLine("        new() { Part = `"$(Esc $c.Part)`", Amount = `"$(Esc "$($c.Amount)")`" },")
        }
        [void]$sb.AppendLine('    ];')
    }

    if ($isSelfFamily) {
        $mm = $familyByName[$m.Name]
        $capacities = Prop $mm 'Capacities'

        # FamilyCapacities override
        if ($capacities -and $capacities.Count -gt 0) {
            [void]$sb.AppendLine('')
            [void]$sb.AppendLine('    public override IReadOnlyList<MultiMachineCapacity> FamilyCapacities =>')
            [void]$sb.AppendLine('    [')
            foreach ($c in $capacities) {
                $cparts = @("Name = `"$(Esc $c.Name)`"")
                $ratio = Prop $c 'PartsRatio'
                if ($null -ne $ratio) { $cparts += "PartsRatio = `"$(Esc "$ratio")`"" }
                $power = Prop $c 'PowerRatio'
                if ($null -ne $power) { $cparts += "PowerRatio = `"$(Esc "$power")`"" }
                if ((Prop $c 'Default') -eq $true) { $cparts += 'Default = true' }
                $color = Prop $c 'Color'
                if ($null -ne $color) { $cparts += "Color = $color" }
                [void]$sb.AppendLine("        new() { $($cparts -join ', ') },")
            }
            [void]$sb.AppendLine('    ];')
        }

        # ToFamilyDefinition
        $familyName = $m.Name
        $defaultMax = Prop $mm 'DefaultMax'
        [void]$sb.AppendLine('')
        [void]$sb.AppendLine("    public override MultiMachineDefinition ToFamilyDefinition() => new()")
        [void]$sb.AppendLine('    {')
        [void]$sb.AppendLine("        Name = `"$(Esc $familyName)`",")
        if ((Prop $mm 'ShowPpm') -eq $true)  { [void]$sb.AppendLine('        ShowPpm = true,') }
        if ((Prop $mm 'AutoRound') -eq $false) { [void]$sb.AppendLine('        AutoRound = false,') }
        if ($null -ne $defaultMax -and "$defaultMax" -ne '') {
            [void]$sb.AppendLine("        DefaultMax = `"$(Esc "$defaultMax")`",")
        }
        if ($capacities -and $capacities.Count -gt 0) {
            [void]$sb.AppendLine('        Capacities =')
            [void]$sb.AppendLine('        [')
            foreach ($c in $capacities) {
                $cparts = @("Name = `"$(Esc $c.Name)`"")
                $ratio = Prop $c 'PartsRatio'
                if ($null -ne $ratio) { $cparts += "PartsRatio = `"$(Esc "$ratio")`"" }
                $power = Prop $c 'PowerRatio'
                if ($null -ne $power) { $cparts += "PowerRatio = `"$(Esc "$power")`"" }
                if ((Prop $c 'Default') -eq $true) { $cparts += 'Default = true' }
                $color = Prop $c 'Color'
                if ($null -ne $color) { $cparts += "Color = $color" }
                [void]$sb.AppendLine("            new() { $($cparts -join ', ') },")
            }
            [void]$sb.AppendLine('        ],')
        }
        [void]$sb.AppendLine('    };')
    }

    [void]$sb.AppendLine('}')
    Save-Class $catDir $cls $sb.ToString()
    $machineCount++
}
"machines emitted: $machineCount"

# --------------------------------------------------------------------- parts
$dir = New-CatalogDir 'Parts'
$used = @{}
for ($i = 0; $i -lt $data.Parts.Count; $i++) {
    $p = $data.Parts[$i]
    $cls = Unique $used (Sanitize $p.Name)
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine('namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("public sealed class $cls : PartBase")
    [void]$sb.AppendLine('{')
    [void]$sb.AppendLine("    public override int SortIndex => $i;")
    [void]$sb.AppendLine("    public override string PartName => `"$(Esc $p.Name)`";")
    [void]$sb.AppendLine("    public override string Tier => `"$(Esc $p.Tier)`";")
    $sink = Prop $p 'SinkPoints'
    if ($sink) { [void]$sb.AppendLine("    public override int SinkPoints => $sink;") }
    if ((Prop $p 'Fluid') -eq $true) { [void]$sb.AppendLine('    public override bool Fluid => true;') }
    if ((Prop $p 'IsManuallyGathered') -eq $true) { [void]$sb.AppendLine('    public override bool IsManuallyGathered => true;') }
    [void]$sb.AppendLine('}')
    Save-Class $dir $cls $sb.ToString()
}
"parts: $($data.Parts.Count)"

# ------------------------------------------------------------------- recipes
# Build machine folder map: machine name -> folder path
# Family variant names map to the family folder
$machineFolderMap = @{}

# Standalone machines and self-family machines
for ($i = 0; $i -lt $data.Machines.Count; $i++) {
    $m = $data.Machines[$i]
    $cat = Prop $m 'Category'
    if (-not $cat) { throw "Machine '$($m.Name)' has no Category in game_data.json." }
    $folder = Sanitize $m.Name
    $machineFolderMap[$m.Name] = $folder
}

# For variant machines (Miner Mk.1/2/3), override to family name
foreach ($variantName in $variantOfFamily.Keys) {
    $familyName = $variantOfFamily[$variantName]
    $machineFolderMap[$variantName] = Sanitize $familyName
}

# MultiMachine names that are self-referential also need to map to their sanitized name
# (already covered above since they have machine entries)

$recipesRoot = New-CatalogDir 'Recipes'
$used = @{}
for ($i = 0; $i -lt $data.Recipes.Count; $i++) {
    $r = $data.Recipes[$i]
    $machineName = $r.Machine

    # Resolve machine folder
    if (-not $machineFolderMap.ContainsKey($machineName)) {
        # Also check family names directly (e.g. "Miner" as machine name)
        if ($familyByName.ContainsKey($machineName)) {
            $folder = Sanitize $machineName
        } else {
            throw "Recipe '$($r.Name)' references machine '$machineName' which has no folder. Add the machine to game_data.json."
        }
    } else {
        $folder = $machineFolderMap[$machineName]
    }

    $machineDir = New-SubDir $recipesRoot $folder
    $ns = "Ficsit.Schematics.Core.GameData.Catalog.Recipes.$folder"

    $cls = Unique $used (Sanitize $r.Name)
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine("namespace $ns;")
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("public sealed class $cls : RecipeBase")
    [void]$sb.AppendLine('{')
    [void]$sb.AppendLine("    public override int SortIndex => $i;")
    [void]$sb.AppendLine("    public override string RecipeName => `"$(Esc $r.Name)`";")
    [void]$sb.AppendLine("    public override string Machine => `"$(Esc $r.Machine)`";")
    [void]$sb.AppendLine("    public override string BatchTime => `"$(Esc "$($r.BatchTime)")`";")
    $tier = Prop $r 'Tier'
    if ($tier) { [void]$sb.AppendLine("    public override string Tier => `"$(Esc $tier)`";") }
    if ((Prop $r 'Alternate') -eq $true) { [void]$sb.AppendLine('    public override bool Alternate => true;') }
    if ((Prop $r 'Ficsmas') -eq $true) { [void]$sb.AppendLine('    public override bool Ficsmas => true;') }
    foreach ($field in 'AveragePower', 'MinPower', 'SpaceElevatorMultiplier') {
        $v = Prop $r $field
        if ($null -ne $v -and "$v" -ne '') {
            [void]$sb.AppendLine("    public override string? $field => `"$(Esc "$v")`";")
        }
    }
    if ((Prop $r 'IgnoreInputMultiplier') -eq $true) { [void]$sb.AppendLine('    public override bool IgnoreInputMultiplier => true;') }
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('    public override IReadOnlyList<RecipePart> Parts =>')
    if ($r.Parts -and $r.Parts.Count -gt 0) {
        [void]$sb.AppendLine('    [')
        foreach ($p in $r.Parts) {
            [void]$sb.AppendLine("        new() { Part = `"$(Esc $p.Part)`", Amount = `"$(Esc "$($p.Amount)")`" },")
        }
        [void]$sb.AppendLine('    ];')
    }
    else {
        [void]$sb.AppendLine('    [')
        [void]$sb.AppendLine('    ];')
    }
    [void]$sb.AppendLine('}')
    Save-Class $machineDir $cls $sb.ToString()
}
"recipes: $($data.Recipes.Count)"
