// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class AILimiter : PartBase
{
    public override int SortIndex => 101;
    public override string PartName => "AI Limiter";
    public override string Tier => "5-5";
    public override int SinkPoints => 920;
}
