// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class AlcladAluminumSheet : PartBase
{
    public override int SortIndex => 117;
    public override string PartName => "Alclad Aluminum Sheet";
    public override string Tier => "7-1";
    public override int SinkPoints => 266;
}
