// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class AlienPowerMatrix : PartBase
{
    public override int SortIndex => 159;
    public override string PartName => "Alien Power Matrix";
    public override string Tier => "9-2";
    public override int SinkPoints => 210;
}
