// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class AluminaSolution : PartBase
{
    public override int SortIndex => 119;
    public override string PartName => "Alumina Solution";
    public override string Tier => "7-1";
    public override bool Fluid => true;
}
