// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class BluePowerSlug : PartBase
{
    public override int SortIndex => 6;
    public override string PartName => "Blue Power Slug";
    public override string Tier => "0-0";
}
