// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class FICSMASTreeBranch : PartBase
{
    public override int SortIndex => 20;
    public override string PartName => "FICSMAS Tree Branch";
    public override string Tier => "0-3";
    public override int SinkPoints => 2;
}
