// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class FICSMASOrnamentBundle : PartBase
{
    public override int SortIndex => 62;
    public override string PartName => "FICSMAS Ornament Bundle";
    public override string Tier => "3-3";
    public override int SinkPoints => 100;
    public override bool IsManuallyGathered => true;
}
