// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class FICSMASGift : PartBase
{
    public override int SortIndex => 19;
    public override string PartName => "FICSMAS Gift";
    public override string Tier => "0-3";
    public override int SinkPoints => 1;
    public override bool IsManuallyGathered => true;
}
