// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class FicsoniumFuelRod : PartBase
{
    public override int SortIndex => 169;
    public override string PartName => "Ficsonium Fuel Rod";
    public override string Tier => "9-5";
}
