// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class FicsiteTrigon : PartBase
{
    public override int SortIndex => 155;
    public override string PartName => "Ficsite Trigon";
    public override string Tier => "9-1";
    public override int SinkPoints => 1291;
}
