// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class Fuel : PartBase
{
    public override int SortIndex => 81;
    public override string PartName => "Fuel";
    public override string Tier => "5-2";
    public override bool Fluid => true;
}
