// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class IodineInfusedFilter : PartBase
{
    public override int SortIndex => 120;
    public override string PartName => "Iodine-Infused Filter";
    public override string Tier => "7-4";
    public override int SinkPoints => 2274;
}
