// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class IonizedFuel : PartBase
{
    public override int SortIndex => 94;
    public override string PartName => "Ionized Fuel";
    public override string Tier => "5-4";
    public override bool Fluid => true;
}
