// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class IronPlate : PartBase
{
    public override int SortIndex => 3;
    public override string PartName => "Iron Plate";
    public override string Tier => "0-0";
    public override int SinkPoints => 6;
}
