// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class IronRebar : PartBase
{
    public override int SortIndex => 26;
    public override string PartName => "Iron Rebar";
    public override string Tier => "0-3";
    public override int SinkPoints => 8;
}
