// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class Leaves : PartBase
{
    public override int SortIndex => 1;
    public override string PartName => "Leaves";
    public override string Tier => "0-0";
    public override int SinkPoints => 3;
}
