// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class LiquidBiofuel : PartBase
{
    public override int SortIndex => 95;
    public override string PartName => "Liquid Biofuel";
    public override string Tier => "5-4";
    public override bool Fluid => true;
}
