// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class NitrogenGas : PartBase
{
    public override int SortIndex => 138;
    public override string PartName => "Nitrogen Gas";
    public override string Tier => "8-3";
    public override bool Fluid => true;
}
