// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class NitricAcid : PartBase
{
    public override int SortIndex => 148;
    public override string PartName => "Nitric Acid";
    public override string Tier => "8-5";
    public override bool Fluid => true;
}
