// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class PackagedSulfuricAcid : PartBase
{
    public override int SortIndex => 121;
    public override string PartName => "Packaged Sulfuric Acid";
    public override string Tier => "7-5";
    public override int SinkPoints => 152;
}
