// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class PetroleumCoke : PartBase
{
    public override int SortIndex => 73;
    public override string PartName => "Petroleum Coke";
    public override string Tier => "5-2";
    public override int SinkPoints => 20;
}
