// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class PlutoniumWaste : PartBase
{
    public override int SortIndex => 151;
    public override string PartName => "Plutonium Waste";
    public override string Tier => "8-5";
}
