// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class SAMFluctuator : PartBase
{
    public override int SortIndex => 157;
    public override string PartName => "SAM Fluctuator";
    public override string Tier => "9-1";
    public override int SinkPoints => 1968;
}
