// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class ShatterRebar : PartBase
{
    public override int SortIndex => 49;
    public override string PartName => "Shatter Rebar";
    public override string Tier => "2-1";
    public override int SinkPoints => 332;
}
