// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class Silica : PartBase
{
    public override int SortIndex => 41;
    public override string PartName => "Silica";
    public override string Tier => "0-5";
    public override int SinkPoints => 20;
}
