// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class SingularityCell : PartBase
{
    public override int SortIndex => 166;
    public override string PartName => "Singularity Cell";
    public override string Tier => "9-4";
    public override int SinkPoints => 114675;
}
