// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class SpitterRemains : PartBase
{
    public override int SortIndex => 12;
    public override string PartName => "Spitter Remains";
    public override string Tier => "0-0";
    public override bool IsManuallyGathered => true;
}
