// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class SteelPipe : PartBase
{
    public override int SortIndex => 58;
    public override string PartName => "Steel Pipe";
    public override string Tier => "3-3";
    public override int SinkPoints => 24;
}
