// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class ThermalPropulsionRocket : PartBase
{
    public override int SortIndex => 140;
    public override string PartName => "Thermal Propulsion Rocket";
    public override string Tier => "8-4";
    public override int SinkPoints => 728508;
}
