// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Parts;

public sealed class TurboRifleAmmo : PartBase
{
    public override int SortIndex => 114;
    public override string PartName => "Turbo Rifle Ammo";
    public override string Tier => "7-1";
    public override int SinkPoints => 120;
}
