// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Foundry;

public sealed class CompactedSteelIngot : RecipeBase
{
    public override int SortIndex => 110;
    public override string RecipeName => "Compacted Steel Ingot";
    public override string Machine => "Foundry";
    public override string BatchTime => "24";
    public override string Tier => "5-4";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Iron Ore", Amount = "-2" },
        new() { Part = "Compacted Coal", Amount = "-1" },
        new() { Part = "Steel Ingot", Amount = "4" },
    ];
}
