// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Foundry;

public sealed class FusedQuartzCrystal : RecipeBase
{
    public override int SortIndex => 81;
    public override string RecipeName => "Fused Quartz Crystal";
    public override string Machine => "Foundry";
    public override string BatchTime => "20";
    public override string Tier => "3-3";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Raw Quartz", Amount = "-25" },
        new() { Part = "Coal", Amount = "-12" },
        new() { Part = "Quartz Crystal", Amount = "18" },
    ];
}
