// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Foundry;

public sealed class IronFICSMASOrnament : RecipeBase
{
    public override int SortIndex => 327;
    public override string RecipeName => "Iron FICSMAS Ornament";
    public override string Machine => "Foundry";
    public override string BatchTime => "12";
    public override string Tier => "3-3";
    public override bool Ficsmas => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Blue FICSMAS Ornament", Amount = "-3" },
        new() { Part = "Iron Ingot", Amount = "-3" },
        new() { Part = "Iron FICSMAS Ornament", Amount = "1" },
    ];
}
