// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Foundry;

public sealed class MoldedSteelPipe : RecipeBase
{
    public override int SortIndex => 113;
    public override string RecipeName => "Molded Steel Pipe";
    public override string Machine => "Foundry";
    public override string BatchTime => "6";
    public override string Tier => "3-3";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Steel Ingot", Amount = "-5" },
        new() { Part = "Concrete", Amount = "-3" },
        new() { Part = "Steel Pipe", Amount = "5" },
    ];
}
