// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Foundry;

public sealed class SolidSteelIngot : RecipeBase
{
    public override int SortIndex => 108;
    public override string RecipeName => "Solid Steel Ingot";
    public override string Machine => "Foundry";
    public override string BatchTime => "3";
    public override string Tier => "3-3";
    public override bool Alternate => true;

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Iron Ingot", Amount = "-2" },
        new() { Part = "Coal", Amount = "-2" },
        new() { Part = "Steel Ingot", Amount = "3" },
    ];
}
