// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.Foundry;

public sealed class SteelIngot : RecipeBase
{
    public override int SortIndex => 107;
    public override string RecipeName => "Steel Ingot";
    public override string Machine => "Foundry";
    public override string BatchTime => "4";
    public override string Tier => "3-3";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Iron Ore", Amount = "-3" },
        new() { Part = "Coal", Amount = "-3" },
        new() { Part = "Steel Ingot", Amount = "3" },
    ];
}
