// <auto-generated>
//     Generated by tools/generate-catalog.ps1 from tools/game_data.json.
//     Do not edit by hand - rerun the script after changing the source data.
// </auto-generated>
#nullable enable

namespace Ficsit.Schematics.Core.GameData.Catalog.Recipes.QuantumEncoder;

public sealed class NeuralQuantumProcessor : RecipeBase
{
    public override int SortIndex => 307;
    public override string RecipeName => "Neural-Quantum Processor";
    public override string Machine => "Quantum Encoder";
    public override string BatchTime => "20";
    public override string Tier => "9-2";
    public override string? AveragePower => "-1000";
    public override string? MinPower => "-2000";

    public override IReadOnlyList<RecipePart> Parts =>
    [
        new() { Part = "Time Crystal", Amount = "-5" },
        new() { Part = "Supercomputer", Amount = "-1" },
        new() { Part = "Ficsite Trigon", Amount = "-15" },
        new() { Part = "Excited Photonic Matter", Amount = "-25" },
        new() { Part = "Neural-Quantum Processor", Amount = "1" },
        new() { Part = "Dark Matter Residue", Amount = "25" },
    ];
}
