#Requires -Version 7
<#
.SYNOPSIS
	Builds the Ficsit.Schematics Windows installer (per-user MSI).

.DESCRIPTION
	Publishes the app self-contained for win-x64 (via Properties/PublishProfiles/win-x64.pubxml)
	with the given version injected, then wraps the publish output in an MSI with WiX
	(restored from .config/dotnet-tools.json). This script is the single build path for
	installers - the release workflow calls it exactly like a local run.

.PARAMETER Version
	Full semantic version, e.g. 0.1.0 or 0.2.0-rc.1. The numeric X.Y.Z part becomes the
	MSI ProductVersion and the exe file version; the full string becomes the exe
	informational version and the installer file name.

.PARAMETER Configuration
	Build configuration (default Release).

.PARAMETER SkipPublish
	Reuse the existing publish output in bin/publish/win-x64 instead of publishing again.

.EXAMPLE
	./installer/build-installer.ps1 -Version 0.1.0
#>
[CmdletBinding()]
param(
	[Parameter(Mandatory)][string]$Version,
	[string]$Configuration = 'Release',
	[switch]$SkipPublish
)

$ErrorActionPreference = 'Stop'

if ($Version -notmatch '^(?<base>\d+\.\d+\.\d+)(-[0-9A-Za-z.-]+)?$') {
	throw "Version '$Version' is not a semantic version (expected X.Y.Z or X.Y.Z-prerelease)."
}
$baseVersion = $Matches.base

$repoRoot = Split-Path -Parent $PSScriptRoot
$tfm = 'net10.0-windows10.0.19041.0'
$publishDir = Join-Path $repoRoot 'bin/publish/win-x64'

if (-not $SkipPublish) {
	Write-Host "Publishing $tfm ($Configuration, win-x64, self-contained) as $Version ..."
	dotnet publish (Join-Path $repoRoot 'Ficsit.Schematics.csproj') `
		-f $tfm `
		-p:PublishProfile=win-x64 `
		-p:Configuration=$Configuration `
		-p:ApplicationDisplayVersion=$baseVersion `
		-p:Version=$Version
	if ($LASTEXITCODE -ne 0) { throw 'dotnet publish failed.' }
}

$exe = Join-Path $publishDir 'Ficsit.Schematics.exe'
if (-not (Test-Path $exe)) {
	throw "Publish output not found at $exe - run without -SkipPublish."
}

# The ARP/shortcut icon: MAUI's resizetizer generates appicon.ico during the build.
$icon = Get-ChildItem (Join-Path $repoRoot 'obj') -Recurse -Filter 'appicon.ico' -ErrorAction SilentlyContinue |
	Sort-Object LastWriteTime -Descending | Select-Object -First 1
if (-not $icon) {
	throw "appicon.ico not found under obj/ - it is generated by the app build (run without -SkipPublish)."
}

Write-Host 'Restoring the wix tool from the manifest ...'
Push-Location $repoRoot
try {
	dotnet tool restore
	if ($LASTEXITCODE -ne 0) { throw 'dotnet tool restore failed.' }

	$outDir = Join-Path $PSScriptRoot 'out'
	New-Item -ItemType Directory -Force $outDir | Out-Null
	$msi = Join-Path $outDir "FicsitSchematics-Setup-$Version.msi"

	Write-Host "Building $msi (MSI ProductVersion $baseVersion) ..."
	dotnet wix build (Join-Path $PSScriptRoot 'Product.wxs') `
		-arch x64 `
		-d "Version=$baseVersion" `
		-d "PublishDir=$publishDir" `
		-d "IconPath=$($icon.FullName)" `
		-o $msi
	if ($LASTEXITCODE -ne 0) { throw 'wix build failed.' }

	Write-Host "Installer ready: $msi"
	$msi
}
finally {
	Pop-Location
}
